package com.chinasofti.cetp.admin.dao;

import com.chinasofti.cetp.admin.model.Class;
import com.chinasofti.cetp.admin.model.ClassExample;
import com.chinasofti.cetp.admin.model.MoreClass;
import com.chinasofti.cetp.admin.model.Org;

import java.util.HashMap;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ClassMapper {

	// 查询所有
	List<MoreClass> selectAllClass(Integer orgId);

	// 查询加载
	List<MoreClass> selectAllClassF();

	// 模糊查找
	List<MoreClass> queryClass(HashMap<String, Object> map, RowBounds rowBounds);

	List<MoreClass> queryClassByorgId(HashMap<String, Object> map,
			RowBounds rowBounds);

	// 删除
	int deleteByPrimaryKey(Integer classId);

	int countByExample(ClassExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_class
	 * 
	 * @mbggenerated Thu Jul 25 19:01:39 CST 2013
	 */
	int deleteByExample(ClassExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_class
	 * 
	 * @mbggenerated Thu Jul 25 19:01:39 CST 2013
	 */

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_class
	 * 
	 * @mbggenerated Thu Jul 25 19:01:39 CST 2013
	 */
	int insert(Class record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_class
	 * 
	 * @mbggenerated Thu Jul 25 19:01:39 CST 2013
	 */
	int insertSelective(Class record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_class
	 * 
	 * @mbggenerated Thu Jul 25 19:01:39 CST 2013
	 */
	List<Class> selectByExample(ClassExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_class
	 * 
	 * @mbggenerated Thu Jul 25 19:01:39 CST 2013
	 */
	Class selectByPrimaryKey(Integer classId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_class
	 * 
	 * @mbggenerated Thu Jul 25 19:01:39 CST 2013
	 */
	int updateByExampleSelective(@Param("record") Class record,
			@Param("example") ClassExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_class
	 * 
	 * @mbggenerated Thu Jul 25 19:01:39 CST 2013
	 */
	int updateByExample(@Param("record") Class record,
			@Param("example") ClassExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_class
	 * 
	 * @mbggenerated Thu Jul 25 19:01:39 CST 2013
	 */
	int updateByPrimaryKeySelective(Class record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_class
	 * 
	 * @mbggenerated Thu Jul 25 19:01:39 CST 2013
	 */
	int updateByPrimaryKey(Class record);

	/*------------------------班级选课需要------------------------------*/
	List<MoreClass> selectClassNotWithSpecCourse(
			@Param("specId") Integer specId, @Param("orgId") Integer orgId,
			@Param("orgList") List<Org> orgList, RowBounds rb);

	List<MoreClass> selectClassWithSpecCourse(int specId, RowBounds rb);

	// -----------------------------------------
	List<MoreClass> selectClassByPrec(int specId);
}