package com.chinasofti.cetp.admin.dao;

import com.chinasofti.cetp.admin.model.Major;
import com.chinasofti.cetp.admin.model.MajorExample;

import java.util.HashMap;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MajorMapper {
	
	/*-------------------- 接口 CRUD方法 ----------------------*/
	
	//查询所有
	List<Major> selectAllMajor();
	
	//条件查询
	List<Major>  QureyMajor(HashMap<String,Object> map);
	
	List<Major> QureyMajorForSomething(HashMap<String, Object> map,RowBounds rb);
	
	//加载“所属专业”ComboBox
	List<Major> loadMajorParent();
	
	//删除
	int deleteByPrimaryKey(String majorCode);
	
	//添加
	int addMajor(Major major);
	
	//修改
	void updateMajor(HashMap<String,Object> map);
	
	/*-------------------- 接口 CRUD方法 ----------------------*/
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_major
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int countByExample(MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_major
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int deleteByExample(MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_major
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_major
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int insert(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_major
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int insertSelective(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_major
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
  

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_major
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    Major selectByPrimaryKey(String majorCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_major
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int updateByExampleSelective(@Param("record") Major record, @Param("example") MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_major
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int updateByExample(@Param("record") Major record, @Param("example") MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_major
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int updateByPrimaryKeySelective(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_major
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int updateByPrimaryKey(Major record);
}