package com.chinasofti.cetp.admin.dao;

import com.chinasofti.cetp.admin.model.Module;
import com.chinasofti.cetp.admin.model.ModuleExample;
import com.chinasofti.cetp.admin.model.MoreModule;
import com.chinasofti.cetp.survey.model.MoreModelQue;

import java.util.HashMap;
import java.util.List;
import org.apache.ibatis.annotations.Param;
/**
 * 
 * @Company : ICS&S DL-ETC
 *
 * @Author : HuangQi
 * @Version : 1.0
 * @Create : 20132013-9-18上午10:03:27
 * TODO :模块管理，管理菜单的url，图标，名字，和每个角色所对应的的后台菜单
 */
public interface ModuleMapper {
	
	//加载菜单-根菜单
	List<MoreModule> getRootMenuByRole(String userId);
	
	//加载菜单-二级菜单
	List<MoreModule> getSubMenuByRole(String userId);
	
	//查询所有
	List<MoreModule>  selectAllModule();
	
	//根据角色查询模块
	List<MoreModule> selectByRole(String roleId);
	
	//查询一级目录
	List<MoreModule> selectRootModule();
	
	//查询二级目录
	List<MoreModule> selectSubModule();
	
	//模糊查询
	List<MoreModule> queryModule(HashMap<String,Object> map);
	
	//加载下拉框
	List<MoreModule> getModuleParent();
	
	//删除
	int deleteByPrimaryKey(String moudleId);
	
	//1,插入模块
	int insertModule_01(MoreModule module);
	
	//2,查询模块ID
	List<MoreModule> queryModuleId(HashMap<String,Object> map);
	
	//添加
	int insertSelective(MoreModule module);
	
	//修改
	int updateByPrimaryKeySelective(MoreModule module);
	
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_module
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int countByExample(ModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_module
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int deleteByExample(ModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_module
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int deleteByPrimaryKey(Integer mdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_module
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int insert(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_module
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_module
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    List<Module> selectByExample(ModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_module
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    Module selectByPrimaryKey(Integer mdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_module
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int updateByExampleSelective(@Param("record") Module record, @Param("example") ModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_module
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int updateByExample(@Param("record") Module record, @Param("example") ModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_module
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_module
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int updateByPrimaryKey(Module record);
}