package com.chinasofti.cetp.admin.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.chinasofti.cetp.admin.model.MoreOrg;
import com.chinasofti.cetp.admin.model.Org;
import com.chinasofti.cetp.admin.model.OrgExample;

public interface OrgMapper {
	
	List<MoreOrg> selectAllOrg();
	List<MoreOrg> loadOrgParebt();
	
	List<Org> selectAllOrgF();
	List<Org> loadOrgForClass(@Param("orgId") Integer orgId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_org
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int countByExample(OrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_org
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int deleteByExample(OrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_org
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int deleteByPrimaryKey(Integer orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_org
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int insert(Org record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_org
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int insertSelective(Org record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_org
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    List<Org> selectByExample(OrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_org
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    Org selectByPrimaryKey(Integer orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_org
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int updateByExampleSelective(@Param("record") Org record, @Param("example") OrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_org
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int updateByExample(@Param("record") Org record, @Param("example") OrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_org
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int updateByPrimaryKeySelective(Org record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_org
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int updateByPrimaryKey(Org record);
}