package com.chinasofti.cetp.study.model;

import java.util.Date;

public class CourseStu extends CourseStuKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_course_stu.CT_STATUS
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    private String ctStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_course_stu.CT_STUDY_TIME
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    private Long ctStudyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_course_stu.CT_REGTIME
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    private Date ctRegtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_course_stu.CT_STATUS
     *
     * @return the value of tp_course_stu.CT_STATUS
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public String getCtStatus() {
        return ctStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_course_stu.CT_STATUS
     *
     * @param ctStatus the value for tp_course_stu.CT_STATUS
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public void setCtStatus(String ctStatus) {
        this.ctStatus = ctStatus == null ? null : ctStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_course_stu.CT_STUDY_TIME
     *
     * @return the value of tp_course_stu.CT_STUDY_TIME
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public Long getCtStudyTime() {
        return ctStudyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_course_stu.CT_STUDY_TIME
     *
     * @param ctStudyTime the value for tp_course_stu.CT_STUDY_TIME
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public void setCtStudyTime(Long ctStudyTime) {
        this.ctStudyTime = ctStudyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_course_stu.CT_REGTIME
     *
     * @return the value of tp_course_stu.CT_REGTIME
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public Date getCtRegtime() {
        return ctRegtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_course_stu.CT_REGTIME
     *
     * @param ctRegtime the value for tp_course_stu.CT_REGTIME
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public void setCtRegtime(Date ctRegtime) {
        this.ctRegtime = ctRegtime;
    }
}