package com.chinasofti.cetp.practice.dao;

import com.chinasofti.cetp.practice.model.MoreTeamAchivement;
import com.chinasofti.cetp.practice.model.TeamAchivement;
import com.chinasofti.cetp.practice.model.TeamAchivementExample;

import java.util.HashMap;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TeamAchivementMapper {
	//add by yf 2013-9-22
	List<MoreTeamAchivement> selectMoreByExample(TeamAchivementExample example,RowBounds rowBounds);
	//end
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int countByExample(TeamAchivementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int deleteByExample(TeamAchivementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int deleteByPrimaryKey(Integer achResultId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int insert(TeamAchivement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int insertSelective(TeamAchivement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    List<TeamAchivement> selectByExample(TeamAchivementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    TeamAchivement selectByPrimaryKey(Integer achResultId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int updateByExampleSelective(@Param("record") TeamAchivement record, @Param("example") TeamAchivementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int updateByExample(@Param("record") TeamAchivement record, @Param("example") TeamAchivementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int updateByPrimaryKeySelective(TeamAchivement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int updateByPrimaryKey(TeamAchivement record);
    
    /**
     * 获取团队成果物
     */
    List<MoreTeamAchivement> getTeamAchivementList(HashMap<String, Object>map,RowBounds rb);
}