package com.chinasofti.cetp.study.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.chinasofti.cetp.study.model.SpecClass;
import com.chinasofti.cetp.study.model.SpecClassExample;
import com.chinasofti.cetp.study.model.SpecClassKey;

public interface SpecClassMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_spec_class
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int countByExample(SpecClassExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_spec_class
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int deleteByExample(SpecClassExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_spec_class
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int deleteByPrimaryKey(SpecClassKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_spec_class
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int insert(SpecClass record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_spec_class
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int insertSelective(SpecClass record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_spec_class
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	List<SpecClass> selectByExample(SpecClassExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_spec_class
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	SpecClass selectByPrimaryKey(SpecClassKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_spec_class
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int updateByExampleSelective(@Param("record") SpecClass record,
			@Param("example") SpecClassExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_spec_class
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int updateByExample(@Param("record") SpecClass record,
			@Param("example") SpecClassExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_spec_class
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int updateByPrimaryKeySelective(SpecClass record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_spec_class
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int updateByPrimaryKey(SpecClass record);
}