package com.chinasofti.cetp.practice.dao;

import com.chinasofti.cetp.practice.model.TaskDoc;
import com.chinasofti.cetp.practice.model.TaskDocExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TaskDocMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_doc
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int countByExample(TaskDocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_doc
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByExample(TaskDocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_doc
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByPrimaryKey(Integer tdDocId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_doc
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insert(TaskDoc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_doc
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insertSelective(TaskDoc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_doc
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	List<TaskDoc> selectByExample(TaskDocExample example);

	List<TaskDoc> selectByExample(TaskDocExample example, RowBounds rowbounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_doc
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	TaskDoc selectByPrimaryKey(Integer tdDocId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_doc
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExampleSelective(@Param("record") TaskDoc record,
			@Param("example") TaskDocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_doc
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExample(@Param("record") TaskDoc record,
			@Param("example") TaskDocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_doc
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKeySelective(TaskDoc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_doc
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKey(TaskDoc record);
	
	int copyItems(@Param("from") Integer from, @Param("to") Integer to);
}