package com.chinasofti.cetp.ability.model;

import java.util.Date;

public class Evaluation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_evaluation.EVAL_ID
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    private Integer evalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_evaluation.EVAL_PROF_ID
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    private Integer evalProfId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_evaluation.EVAL_STU_ID
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    private Integer evalStuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_evaluation.EVAL_REGTIME
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    private Date evalRegtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_evaluation.EVAL_ID
     *
     * @return the value of tp_evaluation.EVAL_ID
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    public Integer getEvalId() {
        return evalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_evaluation.EVAL_ID
     *
     * @param evalId the value for tp_evaluation.EVAL_ID
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    public void setEvalId(Integer evalId) {
        this.evalId = evalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_evaluation.EVAL_PROF_ID
     *
     * @return the value of tp_evaluation.EVAL_PROF_ID
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    public Integer getEvalProfId() {
        return evalProfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_evaluation.EVAL_PROF_ID
     *
     * @param evalProfId the value for tp_evaluation.EVAL_PROF_ID
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    public void setEvalProfId(Integer evalProfId) {
        this.evalProfId = evalProfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_evaluation.EVAL_STU_ID
     *
     * @return the value of tp_evaluation.EVAL_STU_ID
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    public Integer getEvalStuId() {
        return evalStuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_evaluation.EVAL_STU_ID
     *
     * @param evalStuId the value for tp_evaluation.EVAL_STU_ID
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    public void setEvalStuId(Integer evalStuId) {
        this.evalStuId = evalStuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_evaluation.EVAL_REGTIME
     *
     * @return the value of tp_evaluation.EVAL_REGTIME
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    public Date getEvalRegtime() {
        return evalRegtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_evaluation.EVAL_REGTIME
     *
     * @param evalRegtime the value for tp_evaluation.EVAL_REGTIME
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    public void setEvalRegtime(Date evalRegtime) {
        this.evalRegtime = evalRegtime;
    }
}