package com.chinasofti.cetp.ability.dao;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.chinasofti.cetp.ability.model.MoreWconAbitem;
import com.chinasofti.cetp.ability.model.WconAbitem;
import com.chinasofti.cetp.ability.model.WconAbitemExample;
import com.chinasofti.cetp.ability.model.WconAbitemKey;

public interface WconAbitemMapper {
	/**
	 * <p>
	 * 		method:getWconAbitemgriddata
	 * 		<br>
	 * 		description:获取工作内容已选择的能力项列表的方法
	 * </p>
	 * @param wconId Integer
	 * @return List<MoreWconAbitem>
	 * */
	List<MoreWconAbitem> getWconAbitemgriddata(Integer wconId,RowBounds rowBounds);
	/**
	 * <p>
	 * 		method:getWconAbitemgriddata
	 * 		<br>
	 * 		description:获取能力项列表的方法
	 * </p>
	 * @param abiId Integer
	 * @return List<MoreWconAbitem>
	 * */
	List<MoreWconAbitem> getSelAbilityItemWcongriddata(Integer abiId);
	/**
	 * <p>
	 * 		method:getWconAbitemgriddata
	 * 		<br>
	 * 		description:修改能力项的方法
	 * </p>
	 * @param wconId Integer
	 * @return int
	 * */
	int updAbilityItem(MoreWconAbitem wconAbitem);
	/**
	 * <p>
	 * 		method:getAbilityTreeData
	 * 		<br>
	 * 		description:获取能力分类的方法
	 * </p>
	 * @param map HashMap
	 * @return List<MoreWconAbitem>
	 * */
	List<MoreWconAbitem> getAbilityTreeData(HashMap map);
	/**
	 * <p>
	 * 		method:insSaveAbilityTree
	 * 		<br>
	 * 		description:新建能力项的方法
	 * </p>
	 * @param map HashMap
	 * @return int
	 * */
	int insSaveAbilityTree(HashMap map);
	/**
	 * <p>
	 * 		method:selectAbIdExists
	 * 		<br>
	 * 		description:查找能力项的方法
	 * </p>
	 * @param abId Integer
	 * @return int
	 * */
	int selectAbIdExists(Integer abId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_wcon_abitem
     *
     * @mbggenerated Wed Aug 28 17:11:10 CST 2013
     */
    int countByExample(WconAbitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_wcon_abitem
     *
     * @mbggenerated Wed Aug 28 17:11:10 CST 2013
     */
    int deleteByExample(WconAbitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_wcon_abitem
     *
     * @mbggenerated Wed Aug 28 17:11:10 CST 2013
     */
    int deleteByPrimaryKey(WconAbitemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_wcon_abitem
     *
     * @mbggenerated Wed Aug 28 17:11:10 CST 2013
     */
    int insert(WconAbitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_wcon_abitem
     *
     * @mbggenerated Wed Aug 28 17:11:10 CST 2013
     */
    int insertSelective(WconAbitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_wcon_abitem
     *
     * @mbggenerated Wed Aug 28 17:11:10 CST 2013
     */
    List<WconAbitem> selectByExample(WconAbitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_wcon_abitem
     *
     * @mbggenerated Wed Aug 28 17:11:10 CST 2013
     */
    WconAbitem selectByPrimaryKey(WconAbitemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_wcon_abitem
     *
     * @mbggenerated Wed Aug 28 17:11:10 CST 2013
     */
    int updateByExampleSelective(@Param("record") WconAbitem record, @Param("example") WconAbitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_wcon_abitem
     *
     * @mbggenerated Wed Aug 28 17:11:10 CST 2013
     */
    int updateByExample(@Param("record") WconAbitem record, @Param("example") WconAbitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_wcon_abitem
     *
     * @mbggenerated Wed Aug 28 17:11:10 CST 2013
     */
    int updateByPrimaryKeySelective(WconAbitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_wcon_abitem
     *
     * @mbggenerated Wed Aug 28 17:11:10 CST 2013
     */
    int updateByPrimaryKey(WconAbitem record);
}