package com.chinasofti.cetp.ability.dao;

import com.chinasofti.cetp.ability.model.WorkContent;
import com.chinasofti.cetp.ability.model.WorkContentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WorkContentMapper {
	/**
	 * <p>
	 * 		method:selectWorkContent
	 * 		<br>
	 * 		description:获取工作内容列表的方法
	 * </p>
	 * @param delWconId int
	 * @return int
	 * */
	int selectWorkContent(Integer delWconId);
	/**
	 * <p>
	 * 		method:selectWorkContent1
	 * 		<br>
	 * 		description:获取工作内容列表的方法
	 * </p>
	 * @param delWconId int
	 * @return int
	 * */
	int selectWorkContent1(Integer delWconId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_work_content
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int countByExample(WorkContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_work_content
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int deleteByExample(WorkContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_work_content
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int deleteByPrimaryKey(Integer wconId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_work_content
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int insert(WorkContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_work_content
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int insertSelective(WorkContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_work_content
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    List<WorkContent> selectByExample(WorkContentExample example);
    List<WorkContent> selectByExample(WorkContentExample example,RowBounds rowBounds);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_work_content
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    WorkContent selectByPrimaryKey(Integer wconId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_work_content
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int updateByExampleSelective(@Param("record") WorkContent record, @Param("example") WorkContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_work_content
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int updateByExample(@Param("record") WorkContent record, @Param("example") WorkContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_work_content
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int updateByPrimaryKeySelective(WorkContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_work_content
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int updateByPrimaryKey(WorkContent record);
}