package com.chinasofti.cetp.study.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CourseStuExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_course_stu
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_course_stu
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_course_stu
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_course_stu
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public CourseStuExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_course_stu
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_course_stu
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_course_stu
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_course_stu
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_course_stu
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_course_stu
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_course_stu
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_course_stu
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_course_stu
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_course_stu
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_course_stu
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCtCourseIdIsNull() {
            addCriterion("CT_COURSE_ID is null");
            return (Criteria) this;
        }

        public Criteria andCtCourseIdIsNotNull() {
            addCriterion("CT_COURSE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCtCourseIdEqualTo(Integer value) {
            addCriterion("CT_COURSE_ID =", value, "ctCourseId");
            return (Criteria) this;
        }

        public Criteria andCtCourseIdNotEqualTo(Integer value) {
            addCriterion("CT_COURSE_ID <>", value, "ctCourseId");
            return (Criteria) this;
        }

        public Criteria andCtCourseIdGreaterThan(Integer value) {
            addCriterion("CT_COURSE_ID >", value, "ctCourseId");
            return (Criteria) this;
        }

        public Criteria andCtCourseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("CT_COURSE_ID >=", value, "ctCourseId");
            return (Criteria) this;
        }

        public Criteria andCtCourseIdLessThan(Integer value) {
            addCriterion("CT_COURSE_ID <", value, "ctCourseId");
            return (Criteria) this;
        }

        public Criteria andCtCourseIdLessThanOrEqualTo(Integer value) {
            addCriterion("CT_COURSE_ID <=", value, "ctCourseId");
            return (Criteria) this;
        }

        public Criteria andCtCourseIdIn(List<Integer> values) {
            addCriterion("CT_COURSE_ID in", values, "ctCourseId");
            return (Criteria) this;
        }

        public Criteria andCtCourseIdNotIn(List<Integer> values) {
            addCriterion("CT_COURSE_ID not in", values, "ctCourseId");
            return (Criteria) this;
        }

        public Criteria andCtCourseIdBetween(Integer value1, Integer value2) {
            addCriterion("CT_COURSE_ID between", value1, value2, "ctCourseId");
            return (Criteria) this;
        }

        public Criteria andCtCourseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("CT_COURSE_ID not between", value1, value2, "ctCourseId");
            return (Criteria) this;
        }

        public Criteria andCtStuIdIsNull() {
            addCriterion("CT_STU_ID is null");
            return (Criteria) this;
        }

        public Criteria andCtStuIdIsNotNull() {
            addCriterion("CT_STU_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCtStuIdEqualTo(Integer value) {
            addCriterion("CT_STU_ID =", value, "ctStuId");
            return (Criteria) this;
        }

        public Criteria andCtStuIdNotEqualTo(Integer value) {
            addCriterion("CT_STU_ID <>", value, "ctStuId");
            return (Criteria) this;
        }

        public Criteria andCtStuIdGreaterThan(Integer value) {
            addCriterion("CT_STU_ID >", value, "ctStuId");
            return (Criteria) this;
        }

        public Criteria andCtStuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("CT_STU_ID >=", value, "ctStuId");
            return (Criteria) this;
        }

        public Criteria andCtStuIdLessThan(Integer value) {
            addCriterion("CT_STU_ID <", value, "ctStuId");
            return (Criteria) this;
        }

        public Criteria andCtStuIdLessThanOrEqualTo(Integer value) {
            addCriterion("CT_STU_ID <=", value, "ctStuId");
            return (Criteria) this;
        }

        public Criteria andCtStuIdIn(List<Integer> values) {
            addCriterion("CT_STU_ID in", values, "ctStuId");
            return (Criteria) this;
        }

        public Criteria andCtStuIdNotIn(List<Integer> values) {
            addCriterion("CT_STU_ID not in", values, "ctStuId");
            return (Criteria) this;
        }

        public Criteria andCtStuIdBetween(Integer value1, Integer value2) {
            addCriterion("CT_STU_ID between", value1, value2, "ctStuId");
            return (Criteria) this;
        }

        public Criteria andCtStuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("CT_STU_ID not between", value1, value2, "ctStuId");
            return (Criteria) this;
        }

        public Criteria andCtStatusIsNull() {
            addCriterion("CT_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andCtStatusIsNotNull() {
            addCriterion("CT_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andCtStatusEqualTo(String value) {
            addCriterion("CT_STATUS =", value, "ctStatus");
            return (Criteria) this;
        }

        public Criteria andCtStatusNotEqualTo(String value) {
            addCriterion("CT_STATUS <>", value, "ctStatus");
            return (Criteria) this;
        }

        public Criteria andCtStatusGreaterThan(String value) {
            addCriterion("CT_STATUS >", value, "ctStatus");
            return (Criteria) this;
        }

        public Criteria andCtStatusGreaterThanOrEqualTo(String value) {
            addCriterion("CT_STATUS >=", value, "ctStatus");
            return (Criteria) this;
        }

        public Criteria andCtStatusLessThan(String value) {
            addCriterion("CT_STATUS <", value, "ctStatus");
            return (Criteria) this;
        }

        public Criteria andCtStatusLessThanOrEqualTo(String value) {
            addCriterion("CT_STATUS <=", value, "ctStatus");
            return (Criteria) this;
        }

        public Criteria andCtStatusLike(String value) {
            addCriterion("CT_STATUS like", value, "ctStatus");
            return (Criteria) this;
        }

        public Criteria andCtStatusNotLike(String value) {
            addCriterion("CT_STATUS not like", value, "ctStatus");
            return (Criteria) this;
        }

        public Criteria andCtStatusIn(List<String> values) {
            addCriterion("CT_STATUS in", values, "ctStatus");
            return (Criteria) this;
        }

        public Criteria andCtStatusNotIn(List<String> values) {
            addCriterion("CT_STATUS not in", values, "ctStatus");
            return (Criteria) this;
        }

        public Criteria andCtStatusBetween(String value1, String value2) {
            addCriterion("CT_STATUS between", value1, value2, "ctStatus");
            return (Criteria) this;
        }

        public Criteria andCtStatusNotBetween(String value1, String value2) {
            addCriterion("CT_STATUS not between", value1, value2, "ctStatus");
            return (Criteria) this;
        }

        public Criteria andCtStudyTimeIsNull() {
            addCriterion("CT_STUDY_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCtStudyTimeIsNotNull() {
            addCriterion("CT_STUDY_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCtStudyTimeEqualTo(Long value) {
            addCriterion("CT_STUDY_TIME =", value, "ctStudyTime");
            return (Criteria) this;
        }

        public Criteria andCtStudyTimeNotEqualTo(Long value) {
            addCriterion("CT_STUDY_TIME <>", value, "ctStudyTime");
            return (Criteria) this;
        }

        public Criteria andCtStudyTimeGreaterThan(Long value) {
            addCriterion("CT_STUDY_TIME >", value, "ctStudyTime");
            return (Criteria) this;
        }

        public Criteria andCtStudyTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("CT_STUDY_TIME >=", value, "ctStudyTime");
            return (Criteria) this;
        }

        public Criteria andCtStudyTimeLessThan(Long value) {
            addCriterion("CT_STUDY_TIME <", value, "ctStudyTime");
            return (Criteria) this;
        }

        public Criteria andCtStudyTimeLessThanOrEqualTo(Long value) {
            addCriterion("CT_STUDY_TIME <=", value, "ctStudyTime");
            return (Criteria) this;
        }

        public Criteria andCtStudyTimeIn(List<Long> values) {
            addCriterion("CT_STUDY_TIME in", values, "ctStudyTime");
            return (Criteria) this;
        }

        public Criteria andCtStudyTimeNotIn(List<Long> values) {
            addCriterion("CT_STUDY_TIME not in", values, "ctStudyTime");
            return (Criteria) this;
        }

        public Criteria andCtStudyTimeBetween(Long value1, Long value2) {
            addCriterion("CT_STUDY_TIME between", value1, value2, "ctStudyTime");
            return (Criteria) this;
        }

        public Criteria andCtStudyTimeNotBetween(Long value1, Long value2) {
            addCriterion("CT_STUDY_TIME not between", value1, value2, "ctStudyTime");
            return (Criteria) this;
        }

        public Criteria andCtRegtimeIsNull() {
            addCriterion("CT_REGTIME is null");
            return (Criteria) this;
        }

        public Criteria andCtRegtimeIsNotNull() {
            addCriterion("CT_REGTIME is not null");
            return (Criteria) this;
        }

        public Criteria andCtRegtimeEqualTo(Date value) {
            addCriterion("CT_REGTIME =", value, "ctRegtime");
            return (Criteria) this;
        }

        public Criteria andCtRegtimeNotEqualTo(Date value) {
            addCriterion("CT_REGTIME <>", value, "ctRegtime");
            return (Criteria) this;
        }

        public Criteria andCtRegtimeGreaterThan(Date value) {
            addCriterion("CT_REGTIME >", value, "ctRegtime");
            return (Criteria) this;
        }

        public Criteria andCtRegtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CT_REGTIME >=", value, "ctRegtime");
            return (Criteria) this;
        }

        public Criteria andCtRegtimeLessThan(Date value) {
            addCriterion("CT_REGTIME <", value, "ctRegtime");
            return (Criteria) this;
        }

        public Criteria andCtRegtimeLessThanOrEqualTo(Date value) {
            addCriterion("CT_REGTIME <=", value, "ctRegtime");
            return (Criteria) this;
        }

        public Criteria andCtRegtimeIn(List<Date> values) {
            addCriterion("CT_REGTIME in", values, "ctRegtime");
            return (Criteria) this;
        }

        public Criteria andCtRegtimeNotIn(List<Date> values) {
            addCriterion("CT_REGTIME not in", values, "ctRegtime");
            return (Criteria) this;
        }

        public Criteria andCtRegtimeBetween(Date value1, Date value2) {
            addCriterion("CT_REGTIME between", value1, value2, "ctRegtime");
            return (Criteria) this;
        }

        public Criteria andCtRegtimeNotBetween(Date value1, Date value2) {
            addCriterion("CT_REGTIME not between", value1, value2, "ctRegtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_course_stu
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 25 19:26:27 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_course_stu
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}