package com.chinasofti.cetp.study.model;

import java.util.Date;

public class Courseware {

	@Override
	public String toString() {
		return "Courseware [courseId=" + courseId + ", courseName="
				+ courseName + ", courseStyle=" + courseStyle
				+ ", courseVideoType=" + courseVideoType + ", courseTypeId="
				+ courseTypeId + ", courseLang=" + courseLang
				+ ", courseSpeaker=" + courseSpeaker + ", courseUrl="
				+ courseUrl + ", courseDocUrl=" + courseDocUrl
				+ ", coursePrice=" + coursePrice + ", courseTime=" + courseTime
				+ ", courseDiff=" + courseDiff + ", courseParent="
				+ courseParent + ", courseKryword=" + courseKryword
				+ ", courseLevel=" + courseLevel + ", coursePoint="
				+ coursePoint + ", courseMajors=" + courseMajors
				+ ", courseTarget=" + courseTarget + ", courseIntro="
				+ courseIntro + ", courseDemand=" + courseDemand
				+ ", courseRefCourse=" + courseRefCourse + ", courseRefDemand="
				+ courseRefDemand + ", courseObject=" + courseObject
				+ ", courseUserNo=" + courseUserNo + ", coursewareRegtime="
				+ coursewareRegtime + "]";
	}

	// 课件编号
	private Integer courseId;

	// 课件名称
	private String courseName;

	// 课件风格，1:单视频 2:多视频 3:视频+练习 4:HTML 5:PPT 6.其它
	private String courseStyle;

	// 视频类型 1:flash 2:wmv 3:rmvb
	private String courseVideoType;

	// 课件分类 TechType.TechTypeId
	private Integer courseTypeId;

	// 语种 ZH:中文 EN:英文 JP:日文
	private String courseLang;

	// 主讲人
	private String courseSpeaker;

	// 课程访问地址
	private String courseUrl;

	// 课程文档访问地址
	private String courseDocUrl;

	// 课件价格
	private Double coursePrice;

	// 课件时长
	private Integer courseTime;

	// 难度级别 0:易 1:中 2:难
	private String courseDiff;

	// 课件归属 1:系统 2:学校
	private String courseParent;

	// 关键字
	private String courseKryword;

	// 课件地位 0:理解 1:掌握 2:熟练 3:精通
	private String courseLevel;

	// 课程重点
	private String coursePoint;

	// 专业列表
	private String courseMajors;

	// 学习目标
	private String courseTarget;

	// 简介
	private String courseIntro;

	// 学员要求 学习此课件需要何种知识
	private String courseDemand;

	// 相关课程
	private String courseRefCourse;

	// 相关要求
	private String courseRefDemand;

	// 适用对象
	private String courseObject;

	// 记录创建人 外键 TP_USER.USER_NO
	private Integer courseUserNo;

	// 记录创建时间 DEFAULT: CURRENT_TIMESTAMP
	private Date coursewareRegtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_courseware.COURSE_ID
	 * 
	 * @return the value of tp_courseware.COURSE_ID
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public Integer getCourseId() {
		return courseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_courseware.COURSE_ID
	 * 
	 * @param courseId
	 *            the value for tp_courseware.COURSE_ID
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_courseware.COURSE_NAME
	 * 
	 * @return the value of tp_courseware.COURSE_NAME
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public String getCourseName() {
		return courseName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_courseware.COURSE_NAME
	 * 
	 * @param courseName
	 *            the value for tp_courseware.COURSE_NAME
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setCourseName(String courseName) {
		this.courseName = courseName == null ? null : courseName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_courseware.COURSE_STYLE
	 * 
	 * @return the value of tp_courseware.COURSE_STYLE
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public String getCourseStyle() {
		return courseStyle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_courseware.COURSE_STYLE
	 * 
	 * @param courseStyle
	 *            the value for tp_courseware.COURSE_STYLE
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setCourseStyle(String courseStyle) {
		this.courseStyle = courseStyle == null ? null : courseStyle.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_courseware.COURSE_VIDEO_TYPE
	 * 
	 * @return the value of tp_courseware.COURSE_VIDEO_TYPE
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public String getCourseVideoType() {
		return courseVideoType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_courseware.COURSE_VIDEO_TYPE
	 * 
	 * @param courseVideoType
	 *            the value for tp_courseware.COURSE_VIDEO_TYPE
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setCourseVideoType(String courseVideoType) {
		this.courseVideoType = courseVideoType == null ? null : courseVideoType
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_courseware.COURSE_TYPE_ID
	 * 
	 * @return the value of tp_courseware.COURSE_TYPE_ID
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public Integer getCourseTypeId() {
		return courseTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_courseware.COURSE_TYPE_ID
	 * 
	 * @param courseTypeId
	 *            the value for tp_courseware.COURSE_TYPE_ID
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setCourseTypeId(Integer courseTypeId) {
		this.courseTypeId = courseTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_courseware.COURSE_LANG
	 * 
	 * @return the value of tp_courseware.COURSE_LANG
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public String getCourseLang() {
		return courseLang;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_courseware.COURSE_LANG
	 * 
	 * @param courseLang
	 *            the value for tp_courseware.COURSE_LANG
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setCourseLang(String courseLang) {
		this.courseLang = courseLang == null ? null : courseLang.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_courseware.COURSE_SPEAKER
	 * 
	 * @return the value of tp_courseware.COURSE_SPEAKER
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public String getCourseSpeaker() {
		return courseSpeaker;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_courseware.COURSE_SPEAKER
	 * 
	 * @param courseSpeaker
	 *            the value for tp_courseware.COURSE_SPEAKER
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setCourseSpeaker(String courseSpeaker) {
		this.courseSpeaker = courseSpeaker == null ? null : courseSpeaker
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_courseware.COURSE_URL
	 * 
	 * @return the value of tp_courseware.COURSE_URL
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public String getCourseUrl() {
		return courseUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_courseware.COURSE_URL
	 * 
	 * @param courseUrl
	 *            the value for tp_courseware.COURSE_URL
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setCourseUrl(String courseUrl) {
		this.courseUrl = courseUrl == null ? null : courseUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_courseware.COURSE_DOC_URL
	 * 
	 * @return the value of tp_courseware.COURSE_DOC_URL
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public String getCourseDocUrl() {
		return courseDocUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_courseware.COURSE_DOC_URL
	 * 
	 * @param courseDocUrl
	 *            the value for tp_courseware.COURSE_DOC_URL
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setCourseDocUrl(String courseDocUrl) {
		this.courseDocUrl = courseDocUrl == null ? null : courseDocUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_courseware.COURSE_PRICE
	 * 
	 * @return the value of tp_courseware.COURSE_PRICE
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public Double getCoursePrice() {
		return coursePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_courseware.COURSE_PRICE
	 * 
	 * @param coursePrice
	 *            the value for tp_courseware.COURSE_PRICE
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setCoursePrice(Double coursePrice) {
		this.coursePrice = coursePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_courseware.COURSE_TIME
	 * 
	 * @return the value of tp_courseware.COURSE_TIME
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public Integer getCourseTime() {
		return courseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_courseware.COURSE_TIME
	 * 
	 * @param courseTime
	 *            the value for tp_courseware.COURSE_TIME
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setCourseTime(Integer courseTime) {
		this.courseTime = courseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_courseware.COURSE_DIFF
	 * 
	 * @return the value of tp_courseware.COURSE_DIFF
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public String getCourseDiff() {
		return courseDiff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_courseware.COURSE_DIFF
	 * 
	 * @param courseDiff
	 *            the value for tp_courseware.COURSE_DIFF
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setCourseDiff(String courseDiff) {
		this.courseDiff = courseDiff == null ? null : courseDiff.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_courseware.COURSE_PARENT
	 * 
	 * @return the value of tp_courseware.COURSE_PARENT
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public String getCourseParent() {
		return courseParent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_courseware.COURSE_PARENT
	 * 
	 * @param courseParent
	 *            the value for tp_courseware.COURSE_PARENT
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setCourseParent(String courseParent) {
		this.courseParent = courseParent == null ? null : courseParent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_courseware.COURSE_KRYWORD
	 * 
	 * @return the value of tp_courseware.COURSE_KRYWORD
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public String getCourseKryword() {
		return courseKryword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_courseware.COURSE_KRYWORD
	 * 
	 * @param courseKryword
	 *            the value for tp_courseware.COURSE_KRYWORD
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setCourseKryword(String courseKryword) {
		this.courseKryword = courseKryword == null ? null : courseKryword
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_courseware.COURSE_LEVEL
	 * 
	 * @return the value of tp_courseware.COURSE_LEVEL
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public String getCourseLevel() {
		return courseLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_courseware.COURSE_LEVEL
	 * 
	 * @param courseLevel
	 *            the value for tp_courseware.COURSE_LEVEL
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setCourseLevel(String courseLevel) {
		this.courseLevel = courseLevel == null ? null : courseLevel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_courseware.COURSE_POINT
	 * 
	 * @return the value of tp_courseware.COURSE_POINT
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public String getCoursePoint() {
		return coursePoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_courseware.COURSE_POINT
	 * 
	 * @param coursePoint
	 *            the value for tp_courseware.COURSE_POINT
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setCoursePoint(String coursePoint) {
		this.coursePoint = coursePoint == null ? null : coursePoint.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_courseware.COURSE_MAJORS
	 * 
	 * @return the value of tp_courseware.COURSE_MAJORS
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public String getCourseMajors() {
		return courseMajors;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_courseware.COURSE_MAJORS
	 * 
	 * @param courseMajors
	 *            the value for tp_courseware.COURSE_MAJORS
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setCourseMajors(String courseMajors) {
		this.courseMajors = courseMajors == null ? null : courseMajors.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_courseware.COURSE_TARGET
	 * 
	 * @return the value of tp_courseware.COURSE_TARGET
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public String getCourseTarget() {
		return courseTarget;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_courseware.COURSE_TARGET
	 * 
	 * @param courseTarget
	 *            the value for tp_courseware.COURSE_TARGET
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setCourseTarget(String courseTarget) {
		this.courseTarget = courseTarget == null ? null : courseTarget.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_courseware.COURSE_INTRO
	 * 
	 * @return the value of tp_courseware.COURSE_INTRO
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public String getCourseIntro() {
		return courseIntro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_courseware.COURSE_INTRO
	 * 
	 * @param courseIntro
	 *            the value for tp_courseware.COURSE_INTRO
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setCourseIntro(String courseIntro) {
		this.courseIntro = courseIntro == null ? null : courseIntro.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_courseware.COURSE_DEMAND
	 * 
	 * @return the value of tp_courseware.COURSE_DEMAND
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public String getCourseDemand() {
		return courseDemand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_courseware.COURSE_DEMAND
	 * 
	 * @param courseDemand
	 *            the value for tp_courseware.COURSE_DEMAND
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setCourseDemand(String courseDemand) {
		this.courseDemand = courseDemand == null ? null : courseDemand.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_courseware.COURSE_REF_COURSE
	 * 
	 * @return the value of tp_courseware.COURSE_REF_COURSE
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public String getCourseRefCourse() {
		return courseRefCourse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_courseware.COURSE_REF_COURSE
	 * 
	 * @param courseRefCourse
	 *            the value for tp_courseware.COURSE_REF_COURSE
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setCourseRefCourse(String courseRefCourse) {
		this.courseRefCourse = courseRefCourse == null ? null : courseRefCourse
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_courseware.COURSE_REF_DEMAND
	 * 
	 * @return the value of tp_courseware.COURSE_REF_DEMAND
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public String getCourseRefDemand() {
		return courseRefDemand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_courseware.COURSE_REF_DEMAND
	 * 
	 * @param courseRefDemand
	 *            the value for tp_courseware.COURSE_REF_DEMAND
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setCourseRefDemand(String courseRefDemand) {
		this.courseRefDemand = courseRefDemand == null ? null : courseRefDemand
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_courseware.COURSE_OBJECT
	 * 
	 * @return the value of tp_courseware.COURSE_OBJECT
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public String getCourseObject() {
		return courseObject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_courseware.COURSE_OBJECT
	 * 
	 * @param courseObject
	 *            the value for tp_courseware.COURSE_OBJECT
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setCourseObject(String courseObject) {
		this.courseObject = courseObject == null ? null : courseObject.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_courseware.COURSE_USER_NO
	 * 
	 * @return the value of tp_courseware.COURSE_USER_NO
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public Integer getCourseUserNo() {
		return courseUserNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_courseware.COURSE_USER_NO
	 * 
	 * @param courseUserNo
	 *            the value for tp_courseware.COURSE_USER_NO
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setCourseUserNo(Integer courseUserNo) {
		this.courseUserNo = courseUserNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_courseware.COURSEWARE_REGTIME
	 * 
	 * @return the value of tp_courseware.COURSEWARE_REGTIME
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public Date getCoursewareRegtime() {
		return coursewareRegtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_courseware.COURSEWARE_REGTIME
	 * 
	 * @param coursewareRegtime
	 *            the value for tp_courseware.COURSEWARE_REGTIME
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setCoursewareRegtime(Date coursewareRegtime) {
		this.coursewareRegtime = coursewareRegtime;
	}
}