package com.chinasofti.cetp.practice.dao;

import com.chinasofti.cetp.practice.model.MoreMorePractice;
import com.chinasofti.cetp.practice.model.MorePractice;
import com.chinasofti.cetp.practice.model.MorePro;
import com.chinasofti.cetp.practice.model.MoreStuLog;
import com.chinasofti.cetp.practice.model.Practice;
import com.chinasofti.cetp.practice.model.PracticeExample;

import java.util.HashMap;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PracticeMapper {
	int insertPersonTask(HashMap map);

	int insertPersonPro(HashMap map);

	int updatePersonPro(HashMap map);

	int insertPersonPro1(HashMap map);

	List<MoreMorePractice> getSelectedStuList(HashMap map, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_practice
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int countByExample(PracticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_practice
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByExample(PracticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_practice
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByPrimaryKey(Integer pracId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_practice
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insert(Practice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_practice
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insertSelective(Practice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_practice
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	List<Practice> selectByExample(PracticeExample example);

	List<Practice> selectByExample(PracticeExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_practice
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	Practice selectByPrimaryKey(Integer pracId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_practice
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExampleSelective(@Param("record") Practice record, @Param("example") PracticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_practice
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExample(@Param("record") Practice record, @Param("example") PracticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_practice
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKeySelective(Practice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_practice
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKey(Practice record);

	List<MorePractice> selectQueryTrainingMng(HashMap map, RowBounds rowBounds);

	MorePractice selectThisMsg(Integer pracId);

	// List<MorePractice> selectTrainingMng();

	public List<Practice> selectPer();

	public List<MoreMorePractice> selectPerP(HashMap map, RowBounds rowBounds);

	public List<MoreMorePractice> selectPerP1(HashMap map, RowBounds rowBounds);

	public List<Practice> selectQueryPer(HashMap map, RowBounds rowBounds);

	public List<MoreMorePractice> selectQueryPerP(HashMap map);

	MorePractice selectByPrimaryKeyDetail(Integer pracId);

	MoreMorePractice selectByPrimaryKeyDetailP(Integer pracId);

	MorePro selectByPrimaryKeyP(Integer proId);

	/* start add by wang-hw 2013-08-09 */
	List<MorePractice> selectCanselectPro(int pracId, RowBounds rowBounds); // 项目选择

	MorePractice selectPracType(HashMap map);

	MorePractice checkForTeamLeader(Integer studentNumber);

	int checkSelPro(HashMap map);

	// -------------------根据学号查实训
	List<MorePractice> checkPracticeForStuNo(HashMap<String, Object> map);

	/* end */

	/* start add by yf 2013-09-12 */
	List<MorePractice> selectMoreByExample(PracticeExample example, RowBounds rowBounds);

	/* end */

	// add by YF 2014-7-9
	List<MorePractice> getPracListForStu(@Param("techType") String techType, @Param("pracIsTeam") String pracIsTeam, RowBounds rowBounds);
	List<MorePractice> getPracListByTeacher(Integer userNo);

	List<MorePractice> getStuPracList(Integer stuNo);

	List<MoreMorePractice> getPersonPracInfo(@Param("pracId") Integer pracId, @Param("stuNo") Integer stuNo, @Param("stuUserid") String stuUserid, RowBounds rowBounds);

	Practice getPracByClassId(Integer classId);

}