package com.chinasofti.cetp.practice.model;

import java.util.Date;

public class AvailPro extends AvailProKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_avail_pro.AP_USER_NO
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    private Integer apUserNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_avail_pro.AP_REGTIME
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    private Date apRegtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_avail_pro.AP_USER_NO
     *
     * @return the value of tp_avail_pro.AP_USER_NO
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public Integer getApUserNo() {
        return apUserNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_avail_pro.AP_USER_NO
     *
     * @param apUserNo the value for tp_avail_pro.AP_USER_NO
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public void setApUserNo(Integer apUserNo) {
        this.apUserNo = apUserNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_avail_pro.AP_REGTIME
     *
     * @return the value of tp_avail_pro.AP_REGTIME
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public Date getApRegtime() {
        return apRegtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_avail_pro.AP_REGTIME
     *
     * @param apRegtime the value for tp_avail_pro.AP_REGTIME
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public void setApRegtime(Date apRegtime) {
        this.apRegtime = apRegtime;
    }
}