package com.chinasofti.cetp.practice.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AvailProExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_avail_pro
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_avail_pro
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_avail_pro
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_avail_pro
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public AvailProExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_avail_pro
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_avail_pro
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_avail_pro
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_avail_pro
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_avail_pro
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_avail_pro
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_avail_pro
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_avail_pro
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_avail_pro
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_avail_pro
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_avail_pro
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andApPracIdIsNull() {
            addCriterion("AP_PRAC_ID is null");
            return (Criteria) this;
        }

        public Criteria andApPracIdIsNotNull() {
            addCriterion("AP_PRAC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andApPracIdEqualTo(Integer value) {
            addCriterion("AP_PRAC_ID =", value, "apPracId");
            return (Criteria) this;
        }

        public Criteria andApPracIdNotEqualTo(Integer value) {
            addCriterion("AP_PRAC_ID <>", value, "apPracId");
            return (Criteria) this;
        }

        public Criteria andApPracIdGreaterThan(Integer value) {
            addCriterion("AP_PRAC_ID >", value, "apPracId");
            return (Criteria) this;
        }

        public Criteria andApPracIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("AP_PRAC_ID >=", value, "apPracId");
            return (Criteria) this;
        }

        public Criteria andApPracIdLessThan(Integer value) {
            addCriterion("AP_PRAC_ID <", value, "apPracId");
            return (Criteria) this;
        }

        public Criteria andApPracIdLessThanOrEqualTo(Integer value) {
            addCriterion("AP_PRAC_ID <=", value, "apPracId");
            return (Criteria) this;
        }

        public Criteria andApPracIdIn(List<Integer> values) {
            addCriterion("AP_PRAC_ID in", values, "apPracId");
            return (Criteria) this;
        }

        public Criteria andApPracIdNotIn(List<Integer> values) {
            addCriterion("AP_PRAC_ID not in", values, "apPracId");
            return (Criteria) this;
        }

        public Criteria andApPracIdBetween(Integer value1, Integer value2) {
            addCriterion("AP_PRAC_ID between", value1, value2, "apPracId");
            return (Criteria) this;
        }

        public Criteria andApPracIdNotBetween(Integer value1, Integer value2) {
            addCriterion("AP_PRAC_ID not between", value1, value2, "apPracId");
            return (Criteria) this;
        }

        public Criteria andApProIdIsNull() {
            addCriterion("AP_PRO_ID is null");
            return (Criteria) this;
        }

        public Criteria andApProIdIsNotNull() {
            addCriterion("AP_PRO_ID is not null");
            return (Criteria) this;
        }

        public Criteria andApProIdEqualTo(Integer value) {
            addCriterion("AP_PRO_ID =", value, "apProId");
            return (Criteria) this;
        }

        public Criteria andApProIdNotEqualTo(Integer value) {
            addCriterion("AP_PRO_ID <>", value, "apProId");
            return (Criteria) this;
        }

        public Criteria andApProIdGreaterThan(Integer value) {
            addCriterion("AP_PRO_ID >", value, "apProId");
            return (Criteria) this;
        }

        public Criteria andApProIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("AP_PRO_ID >=", value, "apProId");
            return (Criteria) this;
        }

        public Criteria andApProIdLessThan(Integer value) {
            addCriterion("AP_PRO_ID <", value, "apProId");
            return (Criteria) this;
        }

        public Criteria andApProIdLessThanOrEqualTo(Integer value) {
            addCriterion("AP_PRO_ID <=", value, "apProId");
            return (Criteria) this;
        }

        public Criteria andApProIdIn(List<Integer> values) {
            addCriterion("AP_PRO_ID in", values, "apProId");
            return (Criteria) this;
        }

        public Criteria andApProIdNotIn(List<Integer> values) {
            addCriterion("AP_PRO_ID not in", values, "apProId");
            return (Criteria) this;
        }

        public Criteria andApProIdBetween(Integer value1, Integer value2) {
            addCriterion("AP_PRO_ID between", value1, value2, "apProId");
            return (Criteria) this;
        }

        public Criteria andApProIdNotBetween(Integer value1, Integer value2) {
            addCriterion("AP_PRO_ID not between", value1, value2, "apProId");
            return (Criteria) this;
        }

        public Criteria andApUserNoIsNull() {
            addCriterion("AP_USER_NO is null");
            return (Criteria) this;
        }

        public Criteria andApUserNoIsNotNull() {
            addCriterion("AP_USER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andApUserNoEqualTo(Integer value) {
            addCriterion("AP_USER_NO =", value, "apUserNo");
            return (Criteria) this;
        }

        public Criteria andApUserNoNotEqualTo(Integer value) {
            addCriterion("AP_USER_NO <>", value, "apUserNo");
            return (Criteria) this;
        }

        public Criteria andApUserNoGreaterThan(Integer value) {
            addCriterion("AP_USER_NO >", value, "apUserNo");
            return (Criteria) this;
        }

        public Criteria andApUserNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("AP_USER_NO >=", value, "apUserNo");
            return (Criteria) this;
        }

        public Criteria andApUserNoLessThan(Integer value) {
            addCriterion("AP_USER_NO <", value, "apUserNo");
            return (Criteria) this;
        }

        public Criteria andApUserNoLessThanOrEqualTo(Integer value) {
            addCriterion("AP_USER_NO <=", value, "apUserNo");
            return (Criteria) this;
        }

        public Criteria andApUserNoIn(List<Integer> values) {
            addCriterion("AP_USER_NO in", values, "apUserNo");
            return (Criteria) this;
        }

        public Criteria andApUserNoNotIn(List<Integer> values) {
            addCriterion("AP_USER_NO not in", values, "apUserNo");
            return (Criteria) this;
        }

        public Criteria andApUserNoBetween(Integer value1, Integer value2) {
            addCriterion("AP_USER_NO between", value1, value2, "apUserNo");
            return (Criteria) this;
        }

        public Criteria andApUserNoNotBetween(Integer value1, Integer value2) {
            addCriterion("AP_USER_NO not between", value1, value2, "apUserNo");
            return (Criteria) this;
        }

        public Criteria andApRegtimeIsNull() {
            addCriterion("AP_REGTIME is null");
            return (Criteria) this;
        }

        public Criteria andApRegtimeIsNotNull() {
            addCriterion("AP_REGTIME is not null");
            return (Criteria) this;
        }

        public Criteria andApRegtimeEqualTo(Date value) {
            addCriterion("AP_REGTIME =", value, "apRegtime");
            return (Criteria) this;
        }

        public Criteria andApRegtimeNotEqualTo(Date value) {
            addCriterion("AP_REGTIME <>", value, "apRegtime");
            return (Criteria) this;
        }

        public Criteria andApRegtimeGreaterThan(Date value) {
            addCriterion("AP_REGTIME >", value, "apRegtime");
            return (Criteria) this;
        }

        public Criteria andApRegtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("AP_REGTIME >=", value, "apRegtime");
            return (Criteria) this;
        }

        public Criteria andApRegtimeLessThan(Date value) {
            addCriterion("AP_REGTIME <", value, "apRegtime");
            return (Criteria) this;
        }

        public Criteria andApRegtimeLessThanOrEqualTo(Date value) {
            addCriterion("AP_REGTIME <=", value, "apRegtime");
            return (Criteria) this;
        }

        public Criteria andApRegtimeIn(List<Date> values) {
            addCriterion("AP_REGTIME in", values, "apRegtime");
            return (Criteria) this;
        }

        public Criteria andApRegtimeNotIn(List<Date> values) {
            addCriterion("AP_REGTIME not in", values, "apRegtime");
            return (Criteria) this;
        }

        public Criteria andApRegtimeBetween(Date value1, Date value2) {
            addCriterion("AP_REGTIME between", value1, value2, "apRegtime");
            return (Criteria) this;
        }

        public Criteria andApRegtimeNotBetween(Date value1, Date value2) {
            addCriterion("AP_REGTIME not between", value1, value2, "apRegtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_avail_pro
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 25 19:47:24 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_avail_pro
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}