package com.chinasofti.cetp.practice.model;

import java.util.Date;

public class TaskCourse extends TaskCourseKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_task_course.TR_REGTIME
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    private Date trRegtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_task_course.TR_REGTIME
     *
     * @return the value of tp_task_course.TR_REGTIME
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public Date getTrRegtime() {
        return trRegtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_task_course.TR_REGTIME
     *
     * @param trRegtime the value for tp_task_course.TR_REGTIME
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public void setTrRegtime(Date trRegtime) {
        this.trRegtime = trRegtime;
    }
}