package com.chinasofti.cetp.admin.model;

import java.util.Date;

public class UserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_user_role.UR_USER_ID
     *
     * @mbggenerated Mon Aug 05 13:49:53 CST 2013
     */
    private Integer urUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_user_role.UR_ROLE_ID
     *
     * @mbggenerated Mon Aug 05 13:49:53 CST 2013
     */
    private Integer urRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_user_role.UR_REGTIME
     *
     * @mbggenerated Mon Aug 05 13:49:53 CST 2013
     */
    private Date urRegtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_user_role.UR_USER_ID
     *
     * @return the value of tp_user_role.UR_USER_ID
     *
     * @mbggenerated Mon Aug 05 13:49:53 CST 2013
     */
    public Integer getUrUserId() {
        return urUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_user_role.UR_USER_ID
     *
     * @param urUserId the value for tp_user_role.UR_USER_ID
     *
     * @mbggenerated Mon Aug 05 13:49:53 CST 2013
     */
    public void setUrUserId(Integer urUserId) {
        this.urUserId = urUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_user_role.UR_ROLE_ID
     *
     * @return the value of tp_user_role.UR_ROLE_ID
     *
     * @mbggenerated Mon Aug 05 13:49:53 CST 2013
     */
    public Integer getUrRoleId() {
        return urRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_user_role.UR_ROLE_ID
     *
     * @param urRoleId the value for tp_user_role.UR_ROLE_ID
     *
     * @mbggenerated Mon Aug 05 13:49:53 CST 2013
     */
    public void setUrRoleId(Integer urRoleId) {
        this.urRoleId = urRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_user_role.UR_REGTIME
     *
     * @return the value of tp_user_role.UR_REGTIME
     *
     * @mbggenerated Mon Aug 05 13:49:53 CST 2013
     */
    public Date getUrRegtime() {
        return urRegtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_user_role.UR_REGTIME
     *
     * @param urRegtime the value for tp_user_role.UR_REGTIME
     *
     * @mbggenerated Mon Aug 05 13:49:53 CST 2013
     */
    public void setUrRegtime(Date urRegtime) {
        this.urRegtime = urRegtime;
    }
}