package com.chinasofti.cetp.admin.dao;

import com.chinasofti.cetp.admin.model.Certificate;
import com.chinasofti.cetp.admin.model.CertificateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CertificateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_certificate
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int countByExample(CertificateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_certificate
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int deleteByExample(CertificateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_certificate
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int deleteByPrimaryKey(Integer certId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_certificate
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int insert(Certificate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_certificate
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int insertSelective(Certificate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_certificate
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    List<Certificate> selectByExample(CertificateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_certificate
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    Certificate selectByPrimaryKey(Integer certId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_certificate
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int updateByExampleSelective(@Param("record") Certificate record, @Param("example") CertificateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_certificate
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int updateByExample(@Param("record") Certificate record, @Param("example") CertificateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_certificate
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int updateByPrimaryKeySelective(Certificate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_certificate
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int updateByPrimaryKey(Certificate record);
}