package com.chinasofti.cetp.survey.dao;

import com.chinasofti.cetp.survey.model.ModelQue;
import com.chinasofti.cetp.survey.model.ModelQueExample;
import com.chinasofti.cetp.survey.model.ModelQueKey;
import com.chinasofti.cetp.survey.model.MoreModelQue;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ModelQueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_model_que
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    int countByExample(ModelQueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_model_que
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    int deleteByExample(ModelQueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_model_que
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    int deleteByPrimaryKey(ModelQueKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_model_que
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    int insert(ModelQue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_model_que
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    int insertSelective(ModelQue record);
    
    //Add by YF, to insert a MoreModelQue record 
    int insertSelectiveMore(MoreModelQue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_model_que
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    List<ModelQue> selectByExample(ModelQueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_model_que
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    ModelQue selectByPrimaryKey(ModelQueKey key);

    //Add by YF, select by mqModelId
    List<MoreModelQue> selectByModelId(Integer mqModelId);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_model_que
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    int updateByExampleSelective(@Param("record") ModelQue record, @Param("example") ModelQueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_model_que
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    int updateByExample(@Param("record") ModelQue record, @Param("example") ModelQueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_model_que
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    int updateByPrimaryKeySelective(ModelQue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_model_que
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    int updateByPrimaryKey(ModelQue record);
}