package com.chinasofti.cetp.survey.dao;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import com.chinasofti.cetp.survey.model.ChartModel;
import com.chinasofti.cetp.survey.model.SurveyInstDetail;
import com.chinasofti.cetp.survey.model.SurveyInstDetailExample;

public interface SurveyInstDetailMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tp_survey_inst_detail
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int countByExample(SurveyInstDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tp_survey_inst_detail
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int deleteByExample(SurveyInstDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tp_survey_inst_detail
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int deleteByPrimaryKey(Integer idDetailId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tp_survey_inst_detail
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int insert(SurveyInstDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tp_survey_inst_detail
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int insertSelective(SurveyInstDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tp_survey_inst_detail
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	List<SurveyInstDetail> selectByExampleWithBLOBs(SurveyInstDetailExample example);

	List<SurveyInstDetail> selectByExampleWithBLOBs(SurveyInstDetailExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tp_survey_inst_detail
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	List<SurveyInstDetail> selectByExample(SurveyInstDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tp_survey_inst_detail
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	SurveyInstDetail selectByPrimaryKey(Integer idDetailId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tp_survey_inst_detail
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int updateByExampleSelective(@Param("record") SurveyInstDetail record, @Param("example") SurveyInstDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tp_survey_inst_detail
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int updateByExampleWithBLOBs(@Param("record") SurveyInstDetail record, @Param("example") SurveyInstDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tp_survey_inst_detail
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int updateByExample(@Param("record") SurveyInstDetail record, @Param("example") SurveyInstDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tp_survey_inst_detail
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int updateByPrimaryKeySelective(SurveyInstDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tp_survey_inst_detail
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int updateByPrimaryKeyWithBLOBs(SurveyInstDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tp_survey_inst_detail
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int updateByPrimaryKey(SurveyInstDetail record);

	List<ChartModel> getChartModel(Map<String, Object> map);
}