package com.chinasofti.cetp.survey.dao;

import com.chinasofti.cetp.survey.model.MoreSurveyQue;
import com.chinasofti.cetp.survey.model.SurveyQue;
import com.chinasofti.cetp.survey.model.SurveyQueExample;
import com.chinasofti.cetp.survey.model.SurveyQueKey;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SurveyQueMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey_que
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int countByExample(SurveyQueExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey_que
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int deleteByExample(SurveyQueExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey_que
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int deleteByPrimaryKey(SurveyQueKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey_que
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int insert(SurveyQue record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey_que
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int insertSelective(SurveyQue record);

	// Add by YF, to insert a MoreSurveyQue record
	int insertSelectiveMore(MoreSurveyQue record);

	// Add by YF, to insert by model
	int insertByMQ(@Param("sqaSurveyId") Integer sqaSurveyId,
			@Param("fromId") Integer fromId, @Param("fromMQ") Boolean fromMQ);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey_que
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	List<SurveyQue> selectByExample(SurveyQueExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey_que
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	SurveyQue selectByPrimaryKey(SurveyQueKey key);

	// Add by YF, select by sqaSurveyId
	List<MoreSurveyQue> selectBySurveyId(Integer sqaSurveyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey_que
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int updateByExampleSelective(@Param("record") SurveyQue record,
			@Param("example") SurveyQueExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey_que
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int updateByExample(@Param("record") SurveyQue record,
			@Param("example") SurveyQueExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey_que
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int updateByPrimaryKeySelective(SurveyQue record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey_que
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int updateByPrimaryKey(SurveyQue record);

}