package com.chinasofti.cetp.survey.dao;

import com.chinasofti.cetp.survey.model.MoreModelQue;
import com.chinasofti.cetp.survey.model.SurveyQueItem;
import com.chinasofti.cetp.survey.model.SurveyQueItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SurveyQueItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_survey_que_item
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    int countByExample(SurveyQueItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_survey_que_item
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    int deleteByExample(SurveyQueItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_survey_que_item
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    int deleteByPrimaryKey(Integer sqiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_survey_que_item
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    int insert(SurveyQueItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_survey_que_item
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    int insertSelective(SurveyQueItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_survey_que_item
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    List<SurveyQueItem> selectByExample(SurveyQueItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_survey_que_item
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    SurveyQueItem selectByPrimaryKey(Integer sqiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_survey_que_item
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    int updateByExampleSelective(@Param("record") SurveyQueItem record, @Param("example") SurveyQueItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_survey_que_item
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    int updateByExample(@Param("record") SurveyQueItem record, @Param("example") SurveyQueItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_survey_que_item
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    int updateByPrimaryKeySelective(SurveyQueItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_survey_que_item
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    int updateByPrimaryKey(SurveyQueItem record);
    
    List<MoreModelQue> selectByQaId(Integer sqiQaId);
}