package com.chinasofti.cetp.survey.dao;

import com.chinasofti.cetp.survey.model.SurveyModel;
import com.chinasofti.cetp.survey.model.SurveyModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SurveyModelMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey_model
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int countByExample(SurveyModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey_model
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int deleteByExample(SurveyModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey_model
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int deleteByPrimaryKey(Integer smModelId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey_model
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int insert(SurveyModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey_model
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int insertSelective(SurveyModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey_model
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	List<SurveyModel> selectByExample(SurveyModelExample example);

	
	/**
	 * add by YF 2013-10-11
	 * @param example
	 * @param rowBounds
	 * @return
	 */
	List<SurveyModel> selectByExample(SurveyModelExample example,
			RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey_model
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	SurveyModel selectByPrimaryKey(Integer smModelId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey_model
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int updateByExampleSelective(@Param("record") SurveyModel record,
			@Param("example") SurveyModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey_model
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int updateByExample(@Param("record") SurveyModel record,
			@Param("example") SurveyModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey_model
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int updateByPrimaryKeySelective(SurveyModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey_model
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int updateByPrimaryKey(SurveyModel record);
}