package com.chinasofti.cetp.practice.dao;

import com.chinasofti.cetp.practice.model.TeamPhaseCheck;
import com.chinasofti.cetp.practice.model.TeamPhaseCheckExample;
import com.chinasofti.cetp.practice.model.TeamPhaseCheckKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeamPhaseCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_phase_check
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int countByExample(TeamPhaseCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_phase_check
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int deleteByExample(TeamPhaseCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_phase_check
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int deleteByPrimaryKey(TeamPhaseCheckKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_phase_check
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int insert(TeamPhaseCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_phase_check
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int insertSelective(TeamPhaseCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_phase_check
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    List<TeamPhaseCheck> selectByExample(TeamPhaseCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_phase_check
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    TeamPhaseCheck selectByPrimaryKey(TeamPhaseCheckKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_phase_check
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int updateByExampleSelective(@Param("record") TeamPhaseCheck record, @Param("example") TeamPhaseCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_phase_check
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int updateByExample(@Param("record") TeamPhaseCheck record, @Param("example") TeamPhaseCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_phase_check
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int updateByPrimaryKeySelective(TeamPhaseCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_phase_check
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int updateByPrimaryKey(TeamPhaseCheck record);
    
    //add by yf 2013-11-26
    Integer getTeamRealScore(Integer teamId);
}