package com.chinasofti.cetp.admin.dao;

import com.chinasofti.cetp.admin.model.Url;
import com.chinasofti.cetp.admin.model.UrlExample;

import java.util.HashMap;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UrlMapper {
	
	List<Url> queryUrlId(HashMap<String,Object> map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_url
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int countByExample(UrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_url
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int deleteByExample(UrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_url
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int deleteByPrimaryKey(Integer urlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_url
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int insert(Url record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_url
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int insertSelective(Url record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_url
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    List<Url> selectByExample(UrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_url
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    Url selectByPrimaryKey(Integer urlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_url
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int updateByExampleSelective(@Param("record") Url record, @Param("example") UrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_url
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int updateByExample(@Param("record") Url record, @Param("example") UrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_url
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int updateByPrimaryKeySelective(Url record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_url
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int updateByPrimaryKey(Url record);
}