package com.chinasofti.cetp.practice.dao;


import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.chinasofti.cetp.practice.model.AvailPro;
import com.chinasofti.cetp.practice.model.AvailProExample;
import com.chinasofti.cetp.practice.model.AvailProKey;
import com.chinasofti.cetp.practice.model.MoreAvailPro;

public interface AvailProMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_avail_pro
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int countByExample(AvailProExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_avail_pro
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int deleteByExample(AvailProExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_avail_pro
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int deleteByPrimaryKey(AvailProKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_avail_pro
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int insert(AvailPro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_avail_pro
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int insertSelective(AvailPro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_avail_pro
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    List<AvailPro> selectByExample(AvailProExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_avail_pro
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    AvailPro selectByPrimaryKey(AvailProKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_avail_pro
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int updateByExampleSelective(@Param("record") AvailPro record, @Param("example") AvailProExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_avail_pro
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int updateByExample(@Param("record") AvailPro record, @Param("example") AvailProExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_avail_pro
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int updateByPrimaryKeySelective(AvailPro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_avail_pro
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int updateByPrimaryKey(AvailPro record);
    // selectQueryNotProMng
    /*star add by wang-hw  2013-08-07*/
    List<MoreAvailPro> selectPro(Integer pracId,RowBounds rowBounds);
   
    List<MoreAvailPro> notSelectPro(Integer pracId,RowBounds rowBounds);
    
    List<MoreAvailPro> selectQueryNotProMng(HashMap map,RowBounds rowBounds);
    /*end*/
    
}