package com.chinasofti.cetp.admin.dao;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.chinasofti.cetp.admin.model.Area;
import com.chinasofti.cetp.admin.model.AreaExample;
import com.chinasofti.cetp.admin.model.MoreArea;

public interface AreaMapper {
	/**
	 * <p>
	 * 		method:selectAllArea
	 * 		<br>
	 * 		description:获取地区列表的方法
	 * </p>
	 * @return List<MoreArea>
	 * */
	List<MoreArea> getStuProvince();
	List<MoreArea> selectAllArea(Integer parentId);
	/**
	 * <p>
	 * 		method:selectConitionArea
	 * 		<br>
	 * 		description:获取查询条件地区列表的方法
	 * </p>
	 * @param map HashMap 
	 * @return List<MoreArea>
	 * */
	List<MoreArea> selectConitionArea(HashMap map);
	/**
	 * <p>
	 * 		method:insertSave
	 * 		<br>
	 * 		description:新建地区数据的方法
	 * </p>
	 * @param map HashMap 
	 * @returnint
	 * */
	int insertSave(HashMap map);
	/**
	 * <p>
	 * 		method:updateSave
	 * 		<br>
	 * 		description:修改地区数据的方法
	 * </p>
	 * @param map HashMap 
	 * @int
	 * */
	int updateSave(HashMap map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_area
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int countByExample(AreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_area
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int deleteByExample(AreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_area
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int deleteByPrimaryKey(String areaCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_area
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int insert(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_area
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int insertSelective(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_area
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    List<Area> selectByExample(AreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_area
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    Area selectByPrimaryKey(String areaCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_area
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int updateByExampleSelective(@Param("record") Area record, @Param("example") AreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_area
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int updateByExample(@Param("record") Area record, @Param("example") AreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_area
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int updateByPrimaryKeySelective(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_area
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    int updateByPrimaryKey(Area record);
}