package com.chinasofti.cetp.practice.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TeamAchivementExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_team_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_team_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_team_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public TeamAchivementExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_team_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_team_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAchResultIdIsNull() {
            addCriterion("ACH_RESULT_ID is null");
            return (Criteria) this;
        }

        public Criteria andAchResultIdIsNotNull() {
            addCriterion("ACH_RESULT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAchResultIdEqualTo(Integer value) {
            addCriterion("ACH_RESULT_ID =", value, "achResultId");
            return (Criteria) this;
        }

        public Criteria andAchResultIdNotEqualTo(Integer value) {
            addCriterion("ACH_RESULT_ID <>", value, "achResultId");
            return (Criteria) this;
        }

        public Criteria andAchResultIdGreaterThan(Integer value) {
            addCriterion("ACH_RESULT_ID >", value, "achResultId");
            return (Criteria) this;
        }

        public Criteria andAchResultIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ACH_RESULT_ID >=", value, "achResultId");
            return (Criteria) this;
        }

        public Criteria andAchResultIdLessThan(Integer value) {
            addCriterion("ACH_RESULT_ID <", value, "achResultId");
            return (Criteria) this;
        }

        public Criteria andAchResultIdLessThanOrEqualTo(Integer value) {
            addCriterion("ACH_RESULT_ID <=", value, "achResultId");
            return (Criteria) this;
        }

        public Criteria andAchResultIdIn(List<Integer> values) {
            addCriterion("ACH_RESULT_ID in", values, "achResultId");
            return (Criteria) this;
        }

        public Criteria andAchResultIdNotIn(List<Integer> values) {
            addCriterion("ACH_RESULT_ID not in", values, "achResultId");
            return (Criteria) this;
        }

        public Criteria andAchResultIdBetween(Integer value1, Integer value2) {
            addCriterion("ACH_RESULT_ID between", value1, value2, "achResultId");
            return (Criteria) this;
        }

        public Criteria andAchResultIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ACH_RESULT_ID not between", value1, value2, "achResultId");
            return (Criteria) this;
        }

        public Criteria andAchTeamIdIsNull() {
            addCriterion("ACH_TEAM_ID is null");
            return (Criteria) this;
        }

        public Criteria andAchTeamIdIsNotNull() {
            addCriterion("ACH_TEAM_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAchTeamIdEqualTo(Integer value) {
            addCriterion("ACH_TEAM_ID =", value, "achTeamId");
            return (Criteria) this;
        }

        public Criteria andAchTeamIdNotEqualTo(Integer value) {
            addCriterion("ACH_TEAM_ID <>", value, "achTeamId");
            return (Criteria) this;
        }

        public Criteria andAchTeamIdGreaterThan(Integer value) {
            addCriterion("ACH_TEAM_ID >", value, "achTeamId");
            return (Criteria) this;
        }

        public Criteria andAchTeamIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ACH_TEAM_ID >=", value, "achTeamId");
            return (Criteria) this;
        }

        public Criteria andAchTeamIdLessThan(Integer value) {
            addCriterion("ACH_TEAM_ID <", value, "achTeamId");
            return (Criteria) this;
        }

        public Criteria andAchTeamIdLessThanOrEqualTo(Integer value) {
            addCriterion("ACH_TEAM_ID <=", value, "achTeamId");
            return (Criteria) this;
        }

        public Criteria andAchTeamIdIn(List<Integer> values) {
            addCriterion("ACH_TEAM_ID in", values, "achTeamId");
            return (Criteria) this;
        }

        public Criteria andAchTeamIdNotIn(List<Integer> values) {
            addCriterion("ACH_TEAM_ID not in", values, "achTeamId");
            return (Criteria) this;
        }

        public Criteria andAchTeamIdBetween(Integer value1, Integer value2) {
            addCriterion("ACH_TEAM_ID between", value1, value2, "achTeamId");
            return (Criteria) this;
        }

        public Criteria andAchTeamIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ACH_TEAM_ID not between", value1, value2, "achTeamId");
            return (Criteria) this;
        }

        public Criteria andAchProIdIsNull() {
            addCriterion("ACH_PRO_ID is null");
            return (Criteria) this;
        }

        public Criteria andAchProIdIsNotNull() {
            addCriterion("ACH_PRO_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAchProIdEqualTo(Integer value) {
            addCriterion("ACH_PRO_ID =", value, "achProId");
            return (Criteria) this;
        }

        public Criteria andAchProIdNotEqualTo(Integer value) {
            addCriterion("ACH_PRO_ID <>", value, "achProId");
            return (Criteria) this;
        }

        public Criteria andAchProIdGreaterThan(Integer value) {
            addCriterion("ACH_PRO_ID >", value, "achProId");
            return (Criteria) this;
        }

        public Criteria andAchProIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ACH_PRO_ID >=", value, "achProId");
            return (Criteria) this;
        }

        public Criteria andAchProIdLessThan(Integer value) {
            addCriterion("ACH_PRO_ID <", value, "achProId");
            return (Criteria) this;
        }

        public Criteria andAchProIdLessThanOrEqualTo(Integer value) {
            addCriterion("ACH_PRO_ID <=", value, "achProId");
            return (Criteria) this;
        }

        public Criteria andAchProIdIn(List<Integer> values) {
            addCriterion("ACH_PRO_ID in", values, "achProId");
            return (Criteria) this;
        }

        public Criteria andAchProIdNotIn(List<Integer> values) {
            addCriterion("ACH_PRO_ID not in", values, "achProId");
            return (Criteria) this;
        }

        public Criteria andAchProIdBetween(Integer value1, Integer value2) {
            addCriterion("ACH_PRO_ID between", value1, value2, "achProId");
            return (Criteria) this;
        }

        public Criteria andAchProIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ACH_PRO_ID not between", value1, value2, "achProId");
            return (Criteria) this;
        }

        public Criteria andAchResultNameIsNull() {
            addCriterion("ACH_RESULT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andAchResultNameIsNotNull() {
            addCriterion("ACH_RESULT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andAchResultNameEqualTo(String value) {
            addCriterion("ACH_RESULT_NAME =", value, "achResultName");
            return (Criteria) this;
        }

        public Criteria andAchResultNameNotEqualTo(String value) {
            addCriterion("ACH_RESULT_NAME <>", value, "achResultName");
            return (Criteria) this;
        }

        public Criteria andAchResultNameGreaterThan(String value) {
            addCriterion("ACH_RESULT_NAME >", value, "achResultName");
            return (Criteria) this;
        }

        public Criteria andAchResultNameGreaterThanOrEqualTo(String value) {
            addCriterion("ACH_RESULT_NAME >=", value, "achResultName");
            return (Criteria) this;
        }

        public Criteria andAchResultNameLessThan(String value) {
            addCriterion("ACH_RESULT_NAME <", value, "achResultName");
            return (Criteria) this;
        }

        public Criteria andAchResultNameLessThanOrEqualTo(String value) {
            addCriterion("ACH_RESULT_NAME <=", value, "achResultName");
            return (Criteria) this;
        }

        public Criteria andAchResultNameLike(String value) {
            addCriterion("ACH_RESULT_NAME like", value, "achResultName");
            return (Criteria) this;
        }

        public Criteria andAchResultNameNotLike(String value) {
            addCriterion("ACH_RESULT_NAME not like", value, "achResultName");
            return (Criteria) this;
        }

        public Criteria andAchResultNameIn(List<String> values) {
            addCriterion("ACH_RESULT_NAME in", values, "achResultName");
            return (Criteria) this;
        }

        public Criteria andAchResultNameNotIn(List<String> values) {
            addCriterion("ACH_RESULT_NAME not in", values, "achResultName");
            return (Criteria) this;
        }

        public Criteria andAchResultNameBetween(String value1, String value2) {
            addCriterion("ACH_RESULT_NAME between", value1, value2, "achResultName");
            return (Criteria) this;
        }

        public Criteria andAchResultNameNotBetween(String value1, String value2) {
            addCriterion("ACH_RESULT_NAME not between", value1, value2, "achResultName");
            return (Criteria) this;
        }

        public Criteria andAchResultUrlIsNull() {
            addCriterion("ACH_RESULT_URL is null");
            return (Criteria) this;
        }

        public Criteria andAchResultUrlIsNotNull() {
            addCriterion("ACH_RESULT_URL is not null");
            return (Criteria) this;
        }

        public Criteria andAchResultUrlEqualTo(String value) {
            addCriterion("ACH_RESULT_URL =", value, "achResultUrl");
            return (Criteria) this;
        }

        public Criteria andAchResultUrlNotEqualTo(String value) {
            addCriterion("ACH_RESULT_URL <>", value, "achResultUrl");
            return (Criteria) this;
        }

        public Criteria andAchResultUrlGreaterThan(String value) {
            addCriterion("ACH_RESULT_URL >", value, "achResultUrl");
            return (Criteria) this;
        }

        public Criteria andAchResultUrlGreaterThanOrEqualTo(String value) {
            addCriterion("ACH_RESULT_URL >=", value, "achResultUrl");
            return (Criteria) this;
        }

        public Criteria andAchResultUrlLessThan(String value) {
            addCriterion("ACH_RESULT_URL <", value, "achResultUrl");
            return (Criteria) this;
        }

        public Criteria andAchResultUrlLessThanOrEqualTo(String value) {
            addCriterion("ACH_RESULT_URL <=", value, "achResultUrl");
            return (Criteria) this;
        }

        public Criteria andAchResultUrlLike(String value) {
            addCriterion("ACH_RESULT_URL like", value, "achResultUrl");
            return (Criteria) this;
        }

        public Criteria andAchResultUrlNotLike(String value) {
            addCriterion("ACH_RESULT_URL not like", value, "achResultUrl");
            return (Criteria) this;
        }

        public Criteria andAchResultUrlIn(List<String> values) {
            addCriterion("ACH_RESULT_URL in", values, "achResultUrl");
            return (Criteria) this;
        }

        public Criteria andAchResultUrlNotIn(List<String> values) {
            addCriterion("ACH_RESULT_URL not in", values, "achResultUrl");
            return (Criteria) this;
        }

        public Criteria andAchResultUrlBetween(String value1, String value2) {
            addCriterion("ACH_RESULT_URL between", value1, value2, "achResultUrl");
            return (Criteria) this;
        }

        public Criteria andAchResultUrlNotBetween(String value1, String value2) {
            addCriterion("ACH_RESULT_URL not between", value1, value2, "achResultUrl");
            return (Criteria) this;
        }

        public Criteria andAchResultVideoUrlIsNull() {
            addCriterion("ACH_RESULT_VIDEO_URL is null");
            return (Criteria) this;
        }

        public Criteria andAchResultVideoUrlIsNotNull() {
            addCriterion("ACH_RESULT_VIDEO_URL is not null");
            return (Criteria) this;
        }

        public Criteria andAchResultVideoUrlEqualTo(String value) {
            addCriterion("ACH_RESULT_VIDEO_URL =", value, "achResultVideoUrl");
            return (Criteria) this;
        }

        public Criteria andAchResultVideoUrlNotEqualTo(String value) {
            addCriterion("ACH_RESULT_VIDEO_URL <>", value, "achResultVideoUrl");
            return (Criteria) this;
        }

        public Criteria andAchResultVideoUrlGreaterThan(String value) {
            addCriterion("ACH_RESULT_VIDEO_URL >", value, "achResultVideoUrl");
            return (Criteria) this;
        }

        public Criteria andAchResultVideoUrlGreaterThanOrEqualTo(String value) {
            addCriterion("ACH_RESULT_VIDEO_URL >=", value, "achResultVideoUrl");
            return (Criteria) this;
        }

        public Criteria andAchResultVideoUrlLessThan(String value) {
            addCriterion("ACH_RESULT_VIDEO_URL <", value, "achResultVideoUrl");
            return (Criteria) this;
        }

        public Criteria andAchResultVideoUrlLessThanOrEqualTo(String value) {
            addCriterion("ACH_RESULT_VIDEO_URL <=", value, "achResultVideoUrl");
            return (Criteria) this;
        }

        public Criteria andAchResultVideoUrlLike(String value) {
            addCriterion("ACH_RESULT_VIDEO_URL like", value, "achResultVideoUrl");
            return (Criteria) this;
        }

        public Criteria andAchResultVideoUrlNotLike(String value) {
            addCriterion("ACH_RESULT_VIDEO_URL not like", value, "achResultVideoUrl");
            return (Criteria) this;
        }

        public Criteria andAchResultVideoUrlIn(List<String> values) {
            addCriterion("ACH_RESULT_VIDEO_URL in", values, "achResultVideoUrl");
            return (Criteria) this;
        }

        public Criteria andAchResultVideoUrlNotIn(List<String> values) {
            addCriterion("ACH_RESULT_VIDEO_URL not in", values, "achResultVideoUrl");
            return (Criteria) this;
        }

        public Criteria andAchResultVideoUrlBetween(String value1, String value2) {
            addCriterion("ACH_RESULT_VIDEO_URL between", value1, value2, "achResultVideoUrl");
            return (Criteria) this;
        }

        public Criteria andAchResultVideoUrlNotBetween(String value1, String value2) {
            addCriterion("ACH_RESULT_VIDEO_URL not between", value1, value2, "achResultVideoUrl");
            return (Criteria) this;
        }

        public Criteria andAchResultTypeIsNull() {
            addCriterion("ACH_RESULT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andAchResultTypeIsNotNull() {
            addCriterion("ACH_RESULT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andAchResultTypeEqualTo(String value) {
            addCriterion("ACH_RESULT_TYPE =", value, "achResultType");
            return (Criteria) this;
        }

        public Criteria andAchResultTypeNotEqualTo(String value) {
            addCriterion("ACH_RESULT_TYPE <>", value, "achResultType");
            return (Criteria) this;
        }

        public Criteria andAchResultTypeGreaterThan(String value) {
            addCriterion("ACH_RESULT_TYPE >", value, "achResultType");
            return (Criteria) this;
        }

        public Criteria andAchResultTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ACH_RESULT_TYPE >=", value, "achResultType");
            return (Criteria) this;
        }

        public Criteria andAchResultTypeLessThan(String value) {
            addCriterion("ACH_RESULT_TYPE <", value, "achResultType");
            return (Criteria) this;
        }

        public Criteria andAchResultTypeLessThanOrEqualTo(String value) {
            addCriterion("ACH_RESULT_TYPE <=", value, "achResultType");
            return (Criteria) this;
        }

        public Criteria andAchResultTypeLike(String value) {
            addCriterion("ACH_RESULT_TYPE like", value, "achResultType");
            return (Criteria) this;
        }

        public Criteria andAchResultTypeNotLike(String value) {
            addCriterion("ACH_RESULT_TYPE not like", value, "achResultType");
            return (Criteria) this;
        }

        public Criteria andAchResultTypeIn(List<String> values) {
            addCriterion("ACH_RESULT_TYPE in", values, "achResultType");
            return (Criteria) this;
        }

        public Criteria andAchResultTypeNotIn(List<String> values) {
            addCriterion("ACH_RESULT_TYPE not in", values, "achResultType");
            return (Criteria) this;
        }

        public Criteria andAchResultTypeBetween(String value1, String value2) {
            addCriterion("ACH_RESULT_TYPE between", value1, value2, "achResultType");
            return (Criteria) this;
        }

        public Criteria andAchResultTypeNotBetween(String value1, String value2) {
            addCriterion("ACH_RESULT_TYPE not between", value1, value2, "achResultType");
            return (Criteria) this;
        }

        public Criteria andAchUserNoIsNull() {
            addCriterion("ACH_USER_NO is null");
            return (Criteria) this;
        }

        public Criteria andAchUserNoIsNotNull() {
            addCriterion("ACH_USER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andAchUserNoEqualTo(Integer value) {
            addCriterion("ACH_USER_NO =", value, "achUserNo");
            return (Criteria) this;
        }

        public Criteria andAchUserNoNotEqualTo(Integer value) {
            addCriterion("ACH_USER_NO <>", value, "achUserNo");
            return (Criteria) this;
        }

        public Criteria andAchUserNoGreaterThan(Integer value) {
            addCriterion("ACH_USER_NO >", value, "achUserNo");
            return (Criteria) this;
        }

        public Criteria andAchUserNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("ACH_USER_NO >=", value, "achUserNo");
            return (Criteria) this;
        }

        public Criteria andAchUserNoLessThan(Integer value) {
            addCriterion("ACH_USER_NO <", value, "achUserNo");
            return (Criteria) this;
        }

        public Criteria andAchUserNoLessThanOrEqualTo(Integer value) {
            addCriterion("ACH_USER_NO <=", value, "achUserNo");
            return (Criteria) this;
        }

        public Criteria andAchUserNoIn(List<Integer> values) {
            addCriterion("ACH_USER_NO in", values, "achUserNo");
            return (Criteria) this;
        }

        public Criteria andAchUserNoNotIn(List<Integer> values) {
            addCriterion("ACH_USER_NO not in", values, "achUserNo");
            return (Criteria) this;
        }

        public Criteria andAchUserNoBetween(Integer value1, Integer value2) {
            addCriterion("ACH_USER_NO between", value1, value2, "achUserNo");
            return (Criteria) this;
        }

        public Criteria andAchUserNoNotBetween(Integer value1, Integer value2) {
            addCriterion("ACH_USER_NO not between", value1, value2, "achUserNo");
            return (Criteria) this;
        }

        public Criteria andAchRegtimeIsNull() {
            addCriterion("ACH_REGTIME is null");
            return (Criteria) this;
        }

        public Criteria andAchRegtimeIsNotNull() {
            addCriterion("ACH_REGTIME is not null");
            return (Criteria) this;
        }

        public Criteria andAchRegtimeEqualTo(Date value) {
            addCriterion("ACH_REGTIME =", value, "achRegtime");
            return (Criteria) this;
        }

        public Criteria andAchRegtimeNotEqualTo(Date value) {
            addCriterion("ACH_REGTIME <>", value, "achRegtime");
            return (Criteria) this;
        }

        public Criteria andAchRegtimeGreaterThan(Date value) {
            addCriterion("ACH_REGTIME >", value, "achRegtime");
            return (Criteria) this;
        }

        public Criteria andAchRegtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ACH_REGTIME >=", value, "achRegtime");
            return (Criteria) this;
        }

        public Criteria andAchRegtimeLessThan(Date value) {
            addCriterion("ACH_REGTIME <", value, "achRegtime");
            return (Criteria) this;
        }

        public Criteria andAchRegtimeLessThanOrEqualTo(Date value) {
            addCriterion("ACH_REGTIME <=", value, "achRegtime");
            return (Criteria) this;
        }

        public Criteria andAchRegtimeIn(List<Date> values) {
            addCriterion("ACH_REGTIME in", values, "achRegtime");
            return (Criteria) this;
        }

        public Criteria andAchRegtimeNotIn(List<Date> values) {
            addCriterion("ACH_REGTIME not in", values, "achRegtime");
            return (Criteria) this;
        }

        public Criteria andAchRegtimeBetween(Date value1, Date value2) {
            addCriterion("ACH_REGTIME between", value1, value2, "achRegtime");
            return (Criteria) this;
        }

        public Criteria andAchRegtimeNotBetween(Date value1, Date value2) {
            addCriterion("ACH_REGTIME not between", value1, value2, "achRegtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_team_achivement
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 25 19:47:24 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_team_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}