package com.chinasofti.cetp.practice.dao;

import com.chinasofti.cetp.practice.model.MorePro;
import com.chinasofti.cetp.practice.model.Pro;
import com.chinasofti.cetp.practice.model.ProExample;
import com.chinasofti.cetp.practice.model.ProWithBLOBs;

import java.util.HashMap;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ProMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int countByExample(ProExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByExample(ProExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByPrimaryKey(Integer proId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insert(MorePro record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insertSelective(ProWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	List<ProWithBLOBs> selectByExampleWithBLOBs(ProExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	List<Pro> selectByExample(ProExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	MorePro selectByPrimaryKey(Integer proId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExampleSelective(@Param("record") ProWithBLOBs record, @Param("example") ProExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExampleWithBLOBs(@Param("record") ProWithBLOBs record, @Param("example") ProExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExample(@Param("record") Pro record, @Param("example") ProExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKeySelective(ProWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKeyWithBLOBs(ProWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKey(Pro record);

	public List<MorePro> selectPro();

	public List<MorePro> selectQueryPro(HashMap map);

	int getMaxProId();

	// add by YF
	public List<MorePro> selectMoreByExample(ProExample example, RowBounds rowbounds);

	Integer getProUserNo(Integer proId);
	List<MorePro> getPracPro(Integer pracId);
	
	List<MorePro> getProListForStu(@Param("techType") Integer techType, @Param("proIsTeam") String proIsTeam, RowBounds rowBounds);
}