package com.chinasofti.cetp.admin.dao;

import com.chinasofti.cetp.admin.model.RoleModule;
import com.chinasofti.cetp.admin.model.RoleModuleExample;
import com.chinasofti.cetp.admin.model.RootModule;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleModuleMapper {
	
	List<RootModule> selectAllRootModule();
	
	int insertRootModuleByRoleId(@Param("roleId") Integer roleId ,@Param("rootModuleId") Integer rootModuleId );
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_role_module
     *
     * @mbggenerated Mon Aug 05 13:49:53 CST 2013
     */
    int countByExample(RoleModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_role_module
     *
     * @mbggenerated Mon Aug 05 13:49:53 CST 2013
     */
    int deleteByExample(RoleModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_role_module
     *
     * @mbggenerated Mon Aug 05 13:49:53 CST 2013
     */
    int insert(RoleModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_role_module
     *
     * @mbggenerated Mon Aug 05 13:49:53 CST 2013
     */
    int insertSelective(RoleModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_role_module
     *
     * @mbggenerated Mon Aug 05 13:49:53 CST 2013
     */
    List<RoleModule> selectByExample(RoleModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_role_module
     *
     * @mbggenerated Mon Aug 05 13:49:53 CST 2013
     */
    int updateByExampleSelective(@Param("record") RoleModule record, @Param("example") RoleModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_role_module
     *
     * @mbggenerated Mon Aug 05 13:49:53 CST 2013
     */
    int updateByExample(@Param("record") RoleModule record, @Param("example") RoleModuleExample example);
}