package com.chinasofti.cetp.study.dao;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.chinasofti.cetp.study.model.NormalScore;
import com.chinasofti.cetp.study.model.NormalScoreExample;
import com.chinasofti.cetp.study.model.NormalScoreKey;

public interface NormalScoreMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_normal_score
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int countByExample(NormalScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_normal_score
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int deleteByExample(NormalScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_normal_score
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int deleteByPrimaryKey(NormalScoreKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_normal_score
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int insert(NormalScore record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_normal_score
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int insertSelective(NormalScore record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_normal_score
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	List<NormalScore> selectByExample(NormalScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_normal_score
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	NormalScore selectByPrimaryKey(NormalScoreKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_normal_score
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int updateByExampleSelective(@Param("record") NormalScore record,
			@Param("example") NormalScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_normal_score
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int updateByExample(@Param("record") NormalScore record,
			@Param("example") NormalScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_normal_score
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int updateByPrimaryKeySelective(NormalScore record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_normal_score
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int updateByPrimaryKey(NormalScore record);

	Integer selectNormalSumForStuNoAndSpecId(HashMap<String, Object> map);
}