package com.chinasofti.cetp.study.model;

import java.util.Date;

public class SpecClass extends SpecClassKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_spec_class.SS_FLAG
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    private String ssFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_spec_class.SS_TEACHER_ID
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    private Integer ssTeacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_spec_class.SS_REGTIME
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    private Date ssRegtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_spec_class.SS_FLAG
     *
     * @return the value of tp_spec_class.SS_FLAG
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public String getSsFlag() {
        return ssFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_spec_class.SS_FLAG
     *
     * @param ssFlag the value for tp_spec_class.SS_FLAG
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public void setSsFlag(String ssFlag) {
        this.ssFlag = ssFlag == null ? null : ssFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_spec_class.SS_TEACHER_ID
     *
     * @return the value of tp_spec_class.SS_TEACHER_ID
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public Integer getSsTeacherId() {
        return ssTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_spec_class.SS_TEACHER_ID
     *
     * @param ssTeacherId the value for tp_spec_class.SS_TEACHER_ID
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public void setSsTeacherId(Integer ssTeacherId) {
        this.ssTeacherId = ssTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_spec_class.SS_REGTIME
     *
     * @return the value of tp_spec_class.SS_REGTIME
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public Date getSsRegtime() {
        return ssRegtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_spec_class.SS_REGTIME
     *
     * @param ssRegtime the value for tp_spec_class.SS_REGTIME
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public void setSsRegtime(Date ssRegtime) {
        this.ssRegtime = ssRegtime;
    }
}