package com.chinasofti.cetp.practice.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.chinasofti.cetp.practice.model.MoreProTask;
import com.chinasofti.cetp.practice.model.MoreTreePersonProTask;
import com.chinasofti.cetp.practice.model.MoreTreeProTask;
import com.chinasofti.cetp.practice.model.MoreTreeTeamProTask;
import com.chinasofti.cetp.practice.model.ProTask;
import com.chinasofti.cetp.practice.model.ProTaskExample;
import com.chinasofti.cetp.practice.model.TreeProTask;

public interface ProTaskMapper {
	int updateScore(MoreProTask moreprotask);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_task
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int countByExample(ProTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_task
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByExample(ProTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_task
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByPrimaryKey(Integer taskId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_task
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insert(ProTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_task
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insertSelective(ProTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_task
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	List<ProTask> selectByExampleWithBLOBs(ProTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_task
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	List<ProTask> selectByExample(ProTaskExample example);

	// add by yf
	List<TreeProTask> selectTreeByExample(ProTaskExample example);

	List<MoreProTask> selectTree(MoreProTask protask);

	List<MoreProTask> selectTree1(MoreProTask protask);

	List<MoreProTask> selectTree2(MoreProTask protask);

	List<MoreTreeProTask> selectMoreTreeByExample(ProTaskExample example);

	int insSaveTaskScore(MoreProTask moreProTask);

	int insSaveStepTaskScore(MoreProTask moreProTask);

	int updSaveStepTaskScore(MoreProTask moreProTask);

	int selTaskScore(MoreProTask moreProTask);

	List<MoreProTask> selectTask(MoreProTask protask);

	List<MoreProTask> selectTask1(MoreProTask protask);

	int insSaveTaskScore1(MoreProTask moreProTask);

	// add by YF 2013-10-30
	List<MoreTreePersonProTask> selectMoreTreePerson(
			@Param("stuNo") Integer stuNo, @Param("proId") Integer proId,
			@Param("parentId") Integer parentId);

	List<MoreTreeTeamProTask> selectMoreTreeTeam(
			@Param("teamId") Integer teamId, @Param("proId") Integer proId,
			@Param("parentId") Integer parentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_task
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	ProTask selectByPrimaryKey(Integer taskId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_task
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExampleSelective(@Param("record") ProTask record,
			@Param("example") ProTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_task
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExampleWithBLOBs(@Param("record") ProTask record,
			@Param("example") ProTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_task
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExample(@Param("record") ProTask record,
			@Param("example") ProTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_task
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKeySelective(ProTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_task
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKeyWithBLOBs(ProTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_task
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKey(ProTask record);
}