package com.chinasofti.cetp.practice.dao;

import com.chinasofti.cetp.practice.model.MoreTASKABILITY;
import com.chinasofti.cetp.practice.model.TASKABILITY;
import com.chinasofti.cetp.practice.model.TASKABILITYExample;
import com.chinasofti.cetp.practice.model.TASKABILITYKey;
import com.chinasofti.cetp.utils.TreeVO;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TASKABILITYMapper {
	// add by YF 2013-10-24
	List<MoreTASKABILITY> selectMoreByTaskId(Integer taskId);

	List<TreeVO> getAbilityTreeData(@Param("abiParent") Integer abiParent,
			@Param("taskId") Integer taskId);

	Integer saveTaskAbiTree(@Param("taskId") Integer taskId,
			@Param("abiIdList") List<Integer> abiIdList);

	int copyItems(@Param("from") Integer from, @Param("to") Integer to);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_ability
	 * 
	 * @mbggenerated Thu Aug 08 17:28:26 CST 2013
	 */
	int countByExample(TASKABILITYExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_ability
	 * 
	 * @mbggenerated Thu Aug 08 17:28:26 CST 2013
	 */
	int deleteByExample(TASKABILITYExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_ability
	 * 
	 * @mbggenerated Thu Aug 08 17:28:26 CST 2013
	 */
	int deleteByPrimaryKey(TASKABILITYKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_ability
	 * 
	 * @mbggenerated Thu Aug 08 17:28:26 CST 2013
	 */
	int insert(TASKABILITY record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_ability
	 * 
	 * @mbggenerated Thu Aug 08 17:28:26 CST 2013
	 */
	int insertSelective(TASKABILITY record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_ability
	 * 
	 * @mbggenerated Thu Aug 08 17:28:26 CST 2013
	 */
	List<TASKABILITY> selectByExample(TASKABILITYExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_ability
	 * 
	 * @mbggenerated Thu Aug 08 17:28:26 CST 2013
	 */
	TASKABILITY selectByPrimaryKey(TASKABILITYKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_ability
	 * 
	 * @mbggenerated Thu Aug 08 17:28:26 CST 2013
	 */
	int updateByExampleSelective(@Param("record") TASKABILITY record,
			@Param("example") TASKABILITYExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_ability
	 * 
	 * @mbggenerated Thu Aug 08 17:28:26 CST 2013
	 */
	int updateByExample(@Param("record") TASKABILITY record,
			@Param("example") TASKABILITYExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_ability
	 * 
	 * @mbggenerated Thu Aug 08 17:28:26 CST 2013
	 */
	int updateByPrimaryKeySelective(TASKABILITY record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_ability
	 * 
	 * @mbggenerated Thu Aug 08 17:28:26 CST 2013
	 */
	int updateByPrimaryKey(TASKABILITY record);
}