package com.chinasofti.cetp.study.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SpecClassExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_spec_class
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_spec_class
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_spec_class
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_spec_class
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public SpecClassExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_spec_class
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_spec_class
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_spec_class
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_spec_class
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_spec_class
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_spec_class
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_spec_class
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_spec_class
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_spec_class
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_spec_class
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_spec_class
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSsSpecIdIsNull() {
            addCriterion("SS_SPEC_ID is null");
            return (Criteria) this;
        }

        public Criteria andSsSpecIdIsNotNull() {
            addCriterion("SS_SPEC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSsSpecIdEqualTo(Integer value) {
            addCriterion("SS_SPEC_ID =", value, "ssSpecId");
            return (Criteria) this;
        }

        public Criteria andSsSpecIdNotEqualTo(Integer value) {
            addCriterion("SS_SPEC_ID <>", value, "ssSpecId");
            return (Criteria) this;
        }

        public Criteria andSsSpecIdGreaterThan(Integer value) {
            addCriterion("SS_SPEC_ID >", value, "ssSpecId");
            return (Criteria) this;
        }

        public Criteria andSsSpecIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("SS_SPEC_ID >=", value, "ssSpecId");
            return (Criteria) this;
        }

        public Criteria andSsSpecIdLessThan(Integer value) {
            addCriterion("SS_SPEC_ID <", value, "ssSpecId");
            return (Criteria) this;
        }

        public Criteria andSsSpecIdLessThanOrEqualTo(Integer value) {
            addCriterion("SS_SPEC_ID <=", value, "ssSpecId");
            return (Criteria) this;
        }

        public Criteria andSsSpecIdIn(List<Integer> values) {
            addCriterion("SS_SPEC_ID in", values, "ssSpecId");
            return (Criteria) this;
        }

        public Criteria andSsSpecIdNotIn(List<Integer> values) {
            addCriterion("SS_SPEC_ID not in", values, "ssSpecId");
            return (Criteria) this;
        }

        public Criteria andSsSpecIdBetween(Integer value1, Integer value2) {
            addCriterion("SS_SPEC_ID between", value1, value2, "ssSpecId");
            return (Criteria) this;
        }

        public Criteria andSsSpecIdNotBetween(Integer value1, Integer value2) {
            addCriterion("SS_SPEC_ID not between", value1, value2, "ssSpecId");
            return (Criteria) this;
        }

        public Criteria andSsClassIdIsNull() {
            addCriterion("SS_CLASS_ID is null");
            return (Criteria) this;
        }

        public Criteria andSsClassIdIsNotNull() {
            addCriterion("SS_CLASS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSsClassIdEqualTo(Integer value) {
            addCriterion("SS_CLASS_ID =", value, "ssClassId");
            return (Criteria) this;
        }

        public Criteria andSsClassIdNotEqualTo(Integer value) {
            addCriterion("SS_CLASS_ID <>", value, "ssClassId");
            return (Criteria) this;
        }

        public Criteria andSsClassIdGreaterThan(Integer value) {
            addCriterion("SS_CLASS_ID >", value, "ssClassId");
            return (Criteria) this;
        }

        public Criteria andSsClassIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("SS_CLASS_ID >=", value, "ssClassId");
            return (Criteria) this;
        }

        public Criteria andSsClassIdLessThan(Integer value) {
            addCriterion("SS_CLASS_ID <", value, "ssClassId");
            return (Criteria) this;
        }

        public Criteria andSsClassIdLessThanOrEqualTo(Integer value) {
            addCriterion("SS_CLASS_ID <=", value, "ssClassId");
            return (Criteria) this;
        }

        public Criteria andSsClassIdIn(List<Integer> values) {
            addCriterion("SS_CLASS_ID in", values, "ssClassId");
            return (Criteria) this;
        }

        public Criteria andSsClassIdNotIn(List<Integer> values) {
            addCriterion("SS_CLASS_ID not in", values, "ssClassId");
            return (Criteria) this;
        }

        public Criteria andSsClassIdBetween(Integer value1, Integer value2) {
            addCriterion("SS_CLASS_ID between", value1, value2, "ssClassId");
            return (Criteria) this;
        }

        public Criteria andSsClassIdNotBetween(Integer value1, Integer value2) {
            addCriterion("SS_CLASS_ID not between", value1, value2, "ssClassId");
            return (Criteria) this;
        }

        public Criteria andSsFlagIsNull() {
            addCriterion("SS_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andSsFlagIsNotNull() {
            addCriterion("SS_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andSsFlagEqualTo(String value) {
            addCriterion("SS_FLAG =", value, "ssFlag");
            return (Criteria) this;
        }

        public Criteria andSsFlagNotEqualTo(String value) {
            addCriterion("SS_FLAG <>", value, "ssFlag");
            return (Criteria) this;
        }

        public Criteria andSsFlagGreaterThan(String value) {
            addCriterion("SS_FLAG >", value, "ssFlag");
            return (Criteria) this;
        }

        public Criteria andSsFlagGreaterThanOrEqualTo(String value) {
            addCriterion("SS_FLAG >=", value, "ssFlag");
            return (Criteria) this;
        }

        public Criteria andSsFlagLessThan(String value) {
            addCriterion("SS_FLAG <", value, "ssFlag");
            return (Criteria) this;
        }

        public Criteria andSsFlagLessThanOrEqualTo(String value) {
            addCriterion("SS_FLAG <=", value, "ssFlag");
            return (Criteria) this;
        }

        public Criteria andSsFlagLike(String value) {
            addCriterion("SS_FLAG like", value, "ssFlag");
            return (Criteria) this;
        }

        public Criteria andSsFlagNotLike(String value) {
            addCriterion("SS_FLAG not like", value, "ssFlag");
            return (Criteria) this;
        }

        public Criteria andSsFlagIn(List<String> values) {
            addCriterion("SS_FLAG in", values, "ssFlag");
            return (Criteria) this;
        }

        public Criteria andSsFlagNotIn(List<String> values) {
            addCriterion("SS_FLAG not in", values, "ssFlag");
            return (Criteria) this;
        }

        public Criteria andSsFlagBetween(String value1, String value2) {
            addCriterion("SS_FLAG between", value1, value2, "ssFlag");
            return (Criteria) this;
        }

        public Criteria andSsFlagNotBetween(String value1, String value2) {
            addCriterion("SS_FLAG not between", value1, value2, "ssFlag");
            return (Criteria) this;
        }

        public Criteria andSsTeacherIdIsNull() {
            addCriterion("SS_TEACHER_ID is null");
            return (Criteria) this;
        }

        public Criteria andSsTeacherIdIsNotNull() {
            addCriterion("SS_TEACHER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSsTeacherIdEqualTo(Integer value) {
            addCriterion("SS_TEACHER_ID =", value, "ssTeacherId");
            return (Criteria) this;
        }

        public Criteria andSsTeacherIdNotEqualTo(Integer value) {
            addCriterion("SS_TEACHER_ID <>", value, "ssTeacherId");
            return (Criteria) this;
        }

        public Criteria andSsTeacherIdGreaterThan(Integer value) {
            addCriterion("SS_TEACHER_ID >", value, "ssTeacherId");
            return (Criteria) this;
        }

        public Criteria andSsTeacherIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("SS_TEACHER_ID >=", value, "ssTeacherId");
            return (Criteria) this;
        }

        public Criteria andSsTeacherIdLessThan(Integer value) {
            addCriterion("SS_TEACHER_ID <", value, "ssTeacherId");
            return (Criteria) this;
        }

        public Criteria andSsTeacherIdLessThanOrEqualTo(Integer value) {
            addCriterion("SS_TEACHER_ID <=", value, "ssTeacherId");
            return (Criteria) this;
        }

        public Criteria andSsTeacherIdIn(List<Integer> values) {
            addCriterion("SS_TEACHER_ID in", values, "ssTeacherId");
            return (Criteria) this;
        }

        public Criteria andSsTeacherIdNotIn(List<Integer> values) {
            addCriterion("SS_TEACHER_ID not in", values, "ssTeacherId");
            return (Criteria) this;
        }

        public Criteria andSsTeacherIdBetween(Integer value1, Integer value2) {
            addCriterion("SS_TEACHER_ID between", value1, value2, "ssTeacherId");
            return (Criteria) this;
        }

        public Criteria andSsTeacherIdNotBetween(Integer value1, Integer value2) {
            addCriterion("SS_TEACHER_ID not between", value1, value2, "ssTeacherId");
            return (Criteria) this;
        }

        public Criteria andSsRegtimeIsNull() {
            addCriterion("SS_REGTIME is null");
            return (Criteria) this;
        }

        public Criteria andSsRegtimeIsNotNull() {
            addCriterion("SS_REGTIME is not null");
            return (Criteria) this;
        }

        public Criteria andSsRegtimeEqualTo(Date value) {
            addCriterion("SS_REGTIME =", value, "ssRegtime");
            return (Criteria) this;
        }

        public Criteria andSsRegtimeNotEqualTo(Date value) {
            addCriterion("SS_REGTIME <>", value, "ssRegtime");
            return (Criteria) this;
        }

        public Criteria andSsRegtimeGreaterThan(Date value) {
            addCriterion("SS_REGTIME >", value, "ssRegtime");
            return (Criteria) this;
        }

        public Criteria andSsRegtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SS_REGTIME >=", value, "ssRegtime");
            return (Criteria) this;
        }

        public Criteria andSsRegtimeLessThan(Date value) {
            addCriterion("SS_REGTIME <", value, "ssRegtime");
            return (Criteria) this;
        }

        public Criteria andSsRegtimeLessThanOrEqualTo(Date value) {
            addCriterion("SS_REGTIME <=", value, "ssRegtime");
            return (Criteria) this;
        }

        public Criteria andSsRegtimeIn(List<Date> values) {
            addCriterion("SS_REGTIME in", values, "ssRegtime");
            return (Criteria) this;
        }

        public Criteria andSsRegtimeNotIn(List<Date> values) {
            addCriterion("SS_REGTIME not in", values, "ssRegtime");
            return (Criteria) this;
        }

        public Criteria andSsRegtimeBetween(Date value1, Date value2) {
            addCriterion("SS_REGTIME between", value1, value2, "ssRegtime");
            return (Criteria) this;
        }

        public Criteria andSsRegtimeNotBetween(Date value1, Date value2) {
            addCriterion("SS_REGTIME not between", value1, value2, "ssRegtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_spec_class
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 25 19:26:27 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_spec_class
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}