package com.chinasofti.cetp.practice.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.chinasofti.cetp.practice.model.TaskCourse;
import com.chinasofti.cetp.practice.model.TaskCourseExample;
import com.chinasofti.cetp.practice.model.TaskCourseKey;
import com.chinasofti.cetp.resource.model.VideoWithBLOBs;

public interface TaskCourseMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_course
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int countByExample(TaskCourseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_course
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByExample(TaskCourseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_course
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByPrimaryKey(TaskCourseKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_course
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insert(TaskCourse record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_course
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insertSelective(TaskCourse record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_course
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	List<TaskCourse> selectByExample(TaskCourseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_course
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	TaskCourse selectByPrimaryKey(TaskCourseKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_course
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExampleSelective(@Param("record") TaskCourse record,
			@Param("example") TaskCourseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_course
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExample(@Param("record") TaskCourse record,
			@Param("example") TaskCourseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_course
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKeySelective(TaskCourse record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_course
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKey(TaskCourse record);

	// add by YF
	List<VideoWithBLOBs> selectCourseByTaskId(Integer taskId,
			RowBounds rowbounds);
	
	List<VideoWithBLOBs> selectCourseByTaskId(Integer taskId);

	List<VideoWithBLOBs> selectCourseByTaskIdNotSelected(Integer taskId,
			RowBounds rowbounds);
	
	int copyItems(@Param("from") Integer from, @Param("to") Integer to);
}