package com.chinasofti.cetp.ability.model;

import java.util.Date;

public class SysEvaluation extends SysEvaluationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_sys_evaluation.SYEV_AB_ID
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    private Integer syevAbId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_sys_evaluation.SYEV_VALUE
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    private Integer syevValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_sys_evaluation.SYEV_TOTAL_VALUE
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    private Integer syevTotalValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_sys_evaluation.SYEV_REGTIME
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    private Date syevRegtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_sys_evaluation.SYEV_AB_ID
     *
     * @return the value of tp_sys_evaluation.SYEV_AB_ID
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    public Integer getSyevAbId() {
        return syevAbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_sys_evaluation.SYEV_AB_ID
     *
     * @param syevAbId the value for tp_sys_evaluation.SYEV_AB_ID
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    public void setSyevAbId(Integer syevAbId) {
        this.syevAbId = syevAbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_sys_evaluation.SYEV_VALUE
     *
     * @return the value of tp_sys_evaluation.SYEV_VALUE
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    public Integer getSyevValue() {
        return syevValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_sys_evaluation.SYEV_VALUE
     *
     * @param syevValue the value for tp_sys_evaluation.SYEV_VALUE
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    public void setSyevValue(Integer syevValue) {
        this.syevValue = syevValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_sys_evaluation.SYEV_TOTAL_VALUE
     *
     * @return the value of tp_sys_evaluation.SYEV_TOTAL_VALUE
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    public Integer getSyevTotalValue() {
        return syevTotalValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_sys_evaluation.SYEV_TOTAL_VALUE
     *
     * @param syevTotalValue the value for tp_sys_evaluation.SYEV_TOTAL_VALUE
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    public void setSyevTotalValue(Integer syevTotalValue) {
        this.syevTotalValue = syevTotalValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_sys_evaluation.SYEV_REGTIME
     *
     * @return the value of tp_sys_evaluation.SYEV_REGTIME
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    public Date getSyevRegtime() {
        return syevRegtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_sys_evaluation.SYEV_REGTIME
     *
     * @param syevRegtime the value for tp_sys_evaluation.SYEV_REGTIME
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    public void setSyevRegtime(Date syevRegtime) {
        this.syevRegtime = syevRegtime;
    }
}