package com.chinasofti.cetp.practice.model;

public class TaskCourseKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_task_course.TR_TASK_ID
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    private Integer trTaskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_task_course.TR_COURSE_ID
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    private Integer trCourseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_task_course.TR_TASK_ID
     *
     * @return the value of tp_task_course.TR_TASK_ID
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public Integer getTrTaskId() {
        return trTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_task_course.TR_TASK_ID
     *
     * @param trTaskId the value for tp_task_course.TR_TASK_ID
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public void setTrTaskId(Integer trTaskId) {
        this.trTaskId = trTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_task_course.TR_COURSE_ID
     *
     * @return the value of tp_task_course.TR_COURSE_ID
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public Integer getTrCourseId() {
        return trCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_task_course.TR_COURSE_ID
     *
     * @param trCourseId the value for tp_task_course.TR_COURSE_ID
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public void setTrCourseId(Integer trCourseId) {
        this.trCourseId = trCourseId;
    }
}