package com.chinasofti.cetp.ability.model;

import java.util.Date;

public class PabWcon extends PabWconKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_pab_wcon.PABW_REGTIME
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    private Date pabwRegtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_pab_wcon.PABW_REGTIME
     *
     * @return the value of tp_pab_wcon.PABW_REGTIME
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    public Date getPabwRegtime() {
        return pabwRegtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_pab_wcon.PABW_REGTIME
     *
     * @param pabwRegtime the value for tp_pab_wcon.PABW_REGTIME
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    public void setPabwRegtime(Date pabwRegtime) {
        this.pabwRegtime = pabwRegtime;
    }
}