package com.chinasofti.cetp.ability.dao;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.chinasofti.cetp.ability.model.AbilityItem;
import com.chinasofti.cetp.ability.model.AbilityItemExample;
import com.chinasofti.cetp.ability.model.MoreAbilityItem;

public interface AbilityItemMapper {
	// add by YF 2013-10-28
	Integer getAbIdByScore(@Param("abiId") Integer abiId,
			@Param("abScore") Integer abScore);

	// end

	/**
	 * <p>
	 * method:getAbilityTreeData <br>
	 * description:获取能力分类的方法
	 * </p>
	 * 
	 * @param map
	 *            HashMap
	 * @return List<MoreAbilityItem>
	 * */
	List<MoreAbilityItem> getAbilityTreeData(HashMap map);

	/**
	 * <p>
	 * method:selectExistAbilityItem <br>
	 * description:获取能力是否关联的方法
	 * </p>
	 * 
	 * @param abId
	 *            Integer
	 * @return int
	 * */
	int selectExistAbilityItem(Integer abId);

	/**
	 * <p>
	 * method:selectExistAbilityItem <br>
	 * description:获取能力是否关联的方法
	 * </p>
	 * 
	 * @param abId
	 *            Integer
	 * @return int
	 * */
	int selectExistAbilityItem1(Integer abId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_ability_item
	 * 
	 * @mbggenerated Fri Aug 09 09:51:47 CST 2013
	 */
	int countByExample(AbilityItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_ability_item
	 * 
	 * @mbggenerated Fri Aug 09 09:51:47 CST 2013
	 */
	int deleteByExample(AbilityItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_ability_item
	 * 
	 * @mbggenerated Fri Aug 09 09:51:47 CST 2013
	 */
	int deleteByPrimaryKey(Integer abId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_ability_item
	 * 
	 * @mbggenerated Fri Aug 09 09:51:47 CST 2013
	 */
	int insert(AbilityItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_ability_item
	 * 
	 * @mbggenerated Fri Aug 09 09:51:47 CST 2013
	 */
	int insertSelective(AbilityItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_ability_item
	 * 
	 * @mbggenerated Fri Aug 09 09:51:47 CST 2013
	 */
	List<AbilityItem> selectByExample(AbilityItemExample example);

	List<AbilityItem> selectByExample(AbilityItemExample example,
			RowBounds rowBounds);
	
	List<AbilityItem> selectByExampleWithAbiName(AbilityItemExample example,
			RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_ability_item
	 * 
	 * @mbggenerated Fri Aug 09 09:51:47 CST 2013
	 */
	AbilityItem selectByPrimaryKey(Integer abId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_ability_item
	 * 
	 * @mbggenerated Fri Aug 09 09:51:47 CST 2013
	 */
	int updateByExampleSelective(@Param("record") AbilityItem record,
			@Param("example") AbilityItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_ability_item
	 * 
	 * @mbggenerated Fri Aug 09 09:51:47 CST 2013
	 */
	int updateByExample(@Param("record") AbilityItem record,
			@Param("example") AbilityItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_ability_item
	 * 
	 * @mbggenerated Fri Aug 09 09:51:47 CST 2013
	 */
	int updateByPrimaryKeySelective(AbilityItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_ability_item
	 * 
	 * @mbggenerated Fri Aug 09 09:51:47 CST 2013
	 */
	int updateByPrimaryKey(AbilityItem record);
}