package com.chinasofti.cetp.ability.dao;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.chinasofti.cetp.ability.model.Evaluation;
import com.chinasofti.cetp.ability.model.EvaluationExample;
import com.chinasofti.cetp.ability.model.MoreEvaluation;

public interface EvaluationMapper {
	/**
	 * <p>
	 * 		method:selectEvaluation
	 * 		<br>
	 * 		description:获取评价职位信息的方法
	 * </p>
	 * @param rowBounds RowBounds
	 * @return List<MoreEvaluation>
	 * */
	List<MoreEvaluation> selectEvaluation(HashMap map,RowBounds rowBounds);
	/**
	 * <p>
	 * 		method:insertSaveEvaluation
	 * 		<br>
	 * 		description:选择职位的方法
	 * </p>
	 * @param map HashMap
	 * @return int
	 * */
	int insertSaveEvaluation(HashMap map);
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_evaluation
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int countByExample(EvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_evaluation
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int deleteByExample(EvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_evaluation
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int deleteByPrimaryKey(Integer evalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_evaluation
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int insert(Evaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_evaluation
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int insertSelective(Evaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_evaluation
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    List<Evaluation> selectByExample(EvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_evaluation
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    Evaluation selectByPrimaryKey(Integer evalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_evaluation
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int updateByExampleSelective(@Param("record") Evaluation record, @Param("example") EvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_evaluation
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int updateByExample(@Param("record") Evaluation record, @Param("example") EvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_evaluation
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int updateByPrimaryKeySelective(Evaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_evaluation
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int updateByPrimaryKey(Evaluation record);
}