package com.chinasofti.cetp.ability.dao;

import com.chinasofti.cetp.ability.model.ProfessionAbility;
import com.chinasofti.cetp.ability.model.ProfessionAbilityExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ProfessionAbilityMapper {
	/**
	 * <p>
	 * 		method:selectProfessionAbility
	 * 		<br>
	 * 		description:获取职业功能列表的方法
	 * </p>
	 * @return int
	 * */
	int selectProfessionAbility(Integer padId);
	/**
	 * <p>
	 * 		method:selectProfessionAbility
	 * 		<br>
	 * 		description:获取职业功能列表的方法
	 * </p>
	 * @return int
	 * */
	int selectProfessionAbility1(Integer padId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_profession_ability
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int countByExample(ProfessionAbilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_profession_ability
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int deleteByExample(ProfessionAbilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_profession_ability
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int deleteByPrimaryKey(Integer pabId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_profession_ability
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int insert(ProfessionAbility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_profession_ability
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int insertSelective(ProfessionAbility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_profession_ability
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    List<ProfessionAbility> selectByExample(ProfessionAbilityExample example);
    List<ProfessionAbility> selectByExample(ProfessionAbilityExample example,RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_profession_ability
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    ProfessionAbility selectByPrimaryKey(Integer pabId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_profession_ability
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int updateByExampleSelective(@Param("record") ProfessionAbility record, @Param("example") ProfessionAbilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_profession_ability
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int updateByExample(@Param("record") ProfessionAbility record, @Param("example") ProfessionAbilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_profession_ability
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int updateByPrimaryKeySelective(ProfessionAbility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_profession_ability
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int updateByPrimaryKey(ProfessionAbility record);
}