package com.chinasofti.cetp.ability.dao;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.chinasofti.cetp.ability.model.MoreSelfEvaluation;
import com.chinasofti.cetp.ability.model.SelfEvaluation;
import com.chinasofti.cetp.ability.model.SelfEvaluationExample;

public interface SelfEvaluationMapper {
	
	/**
	 * <p>
	 * 		method:selectProf
	 * 		<br>
	 * 		description:获取测评职业名称
	 * </p>
	 * @param map HashMap
	 * @return List<MoreSelfEvaluation>
	 * */
	List<MoreSelfEvaluation> selectProf(HashMap map);
	/**
	 * <p>
	 * 		method:selectRatioEvaluation
	 * 		<br>
	 * 		description:获取对比列表的方法
	 * </p>
	 * @param map HashMap
	 * @return List<MoreSelfEvaluation>
	 * */
	List<MoreSelfEvaluation> selectRatioEvaluation(HashMap map);
	/**
	 * <p>
	 * 		method:selectStandard
	 * 		<br>
	 * 		description:获取标准评价的方法
	 * </p>
	 * @param map HashMap
	 * @return List<MoreSelfEvaluation>
	 * */
	List<MoreSelfEvaluation> selectStandard(HashMap map);
	/**
	 * <p>
	 * 		method:selectSelfEvaluation
	 * 		<br>
	 * 		description:获取自我评价的方法
	 * </p>
	 * @param map HashMap
	 * @return List<MoreSelfEvaluation>
	 * */
	List<MoreSelfEvaluation> selectSelfEvaluation(HashMap map);
	/**
	 * <p>
	 * 		method:selectSelfType
	 * 		<br>
	 * 		description:获取要评价的能力的方法
	 * </p>
	 * @param map HashMap
	 * @return List<MoreSelfEvaluation>
	 * */
	List<MoreSelfEvaluation> selectSelfType(HashMap map);
	/**
	 * <p>
	 * 		method:selectSelfItem
	 * 		<br>
	 * 		description:获取要评价的能力项的方法
	 * </p>
	 * @param selAbiId Integer
	 * @return List<MoreSelfEvaluation>
	 * */
	List<MoreSelfEvaluation> selectSelfItem(Integer selAbiId);
	/**
	 * <p>
	 * 		method:selectExitEval
	 * 		<br>
	 * 		description:判断评价表是否存在的方法
	 * </p>
	 * @param map HashMap
	 * @return List<MoreSelfEvaluation>
	 * */
	List<MoreSelfEvaluation> selectExitEval(HashMap map);
	/**
	 * <p>
	 * 		method:selectExitSelfEvaluation
	 * 		<br>
	 * 		description:判断评价表值是否存在的方法
	 * </p>
	 * @param map HashMap
	 * @return List<MoreSelfEvaluation>
	 * */
	List<MoreSelfEvaluation> selectExitSelfEvaluation(HashMap map);
	/**
	 * <p>
	 * 		method:insertSaveEvaluation
	 * 		<br>
	 * 		description:选择职位的方法
	 * </p>
	 * @param map HashMap
	 * @return int
	 * */
	int insertSaveEvaluation(HashMap map);
	/**
	 * <p>
	 * 		method:updateSaveSelfEvaluation
	 * 		<br>
	 * 		description:自我评价的方法
	 * </p>
	 * @param map HashMap
	 * @return int
	 * */
	int updateSaveSelfEvaluation(HashMap map);
	/**
	 * <p>
	 * 		method:insertSaveSelfEvaluation
	 * 		<br>
	 * 		description:自我评价的方法
	 * </p>
	 * @param map HashMap
	 * @return int
	 * */
	int insertSaveSelfEvaluation(HashMap map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_self_evaluation
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int countByExample(SelfEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_self_evaluation
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int deleteByExample(SelfEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_self_evaluation
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int deleteByPrimaryKey(Integer sevId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_self_evaluation
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int insert(SelfEvaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_self_evaluation
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int insertSelective(SelfEvaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_self_evaluation
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    List<SelfEvaluation> selectByExample(SelfEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_self_evaluation
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    SelfEvaluation selectByPrimaryKey(Integer sevId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_self_evaluation
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int updateByExampleSelective(@Param("record") SelfEvaluation record, @Param("example") SelfEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_self_evaluation
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int updateByExample(@Param("record") SelfEvaluation record, @Param("example") SelfEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_self_evaluation
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int updateByPrimaryKeySelective(SelfEvaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_self_evaluation
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int updateByPrimaryKey(SelfEvaluation record);
}