package com.chinasofti.cetp.practice.dao;

import com.chinasofti.cetp.practice.model.ProDoc;
import com.chinasofti.cetp.practice.model.ProDocExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ProDocMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_doc
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int countByExample(ProDocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_doc
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByExample(ProDocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_doc
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByPrimaryKey(Integer pdDocId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_doc
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insert(ProDoc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_doc
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insertSelective(ProDoc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_doc
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	List<ProDoc> selectByExample(ProDocExample example);

	List<ProDoc> selectByExample(ProDocExample example, RowBounds rowbounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_doc
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	ProDoc selectByPrimaryKey(Integer pdDocId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_doc
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExampleSelective(@Param("record") ProDoc record,
			@Param("example") ProDocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_doc
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExample(@Param("record") ProDoc record,
			@Param("example") ProDocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_doc
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKeySelective(ProDoc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_doc
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKey(ProDoc record);
	
	int copyItems(@Param("from") Integer from, @Param("to") Integer to);
}