package com.chinasofti.cetp.study.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SimulateTestExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_simulate_test
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_simulate_test
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_simulate_test
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_simulate_test
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public SimulateTestExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_simulate_test
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_simulate_test
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_simulate_test
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_simulate_test
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_simulate_test
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_simulate_test
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_simulate_test
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_simulate_test
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_simulate_test
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_simulate_test
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_simulate_test
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSimuIdIsNull() {
            addCriterion("SIMU_ID is null");
            return (Criteria) this;
        }

        public Criteria andSimuIdIsNotNull() {
            addCriterion("SIMU_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSimuIdEqualTo(Integer value) {
            addCriterion("SIMU_ID =", value, "simuId");
            return (Criteria) this;
        }

        public Criteria andSimuIdNotEqualTo(Integer value) {
            addCriterion("SIMU_ID <>", value, "simuId");
            return (Criteria) this;
        }

        public Criteria andSimuIdGreaterThan(Integer value) {
            addCriterion("SIMU_ID >", value, "simuId");
            return (Criteria) this;
        }

        public Criteria andSimuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("SIMU_ID >=", value, "simuId");
            return (Criteria) this;
        }

        public Criteria andSimuIdLessThan(Integer value) {
            addCriterion("SIMU_ID <", value, "simuId");
            return (Criteria) this;
        }

        public Criteria andSimuIdLessThanOrEqualTo(Integer value) {
            addCriterion("SIMU_ID <=", value, "simuId");
            return (Criteria) this;
        }

        public Criteria andSimuIdIn(List<Integer> values) {
            addCriterion("SIMU_ID in", values, "simuId");
            return (Criteria) this;
        }

        public Criteria andSimuIdNotIn(List<Integer> values) {
            addCriterion("SIMU_ID not in", values, "simuId");
            return (Criteria) this;
        }

        public Criteria andSimuIdBetween(Integer value1, Integer value2) {
            addCriterion("SIMU_ID between", value1, value2, "simuId");
            return (Criteria) this;
        }

        public Criteria andSimuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("SIMU_ID not between", value1, value2, "simuId");
            return (Criteria) this;
        }

        public Criteria andSimuCourseIdIsNull() {
            addCriterion("SIMU_COURSE_ID is null");
            return (Criteria) this;
        }

        public Criteria andSimuCourseIdIsNotNull() {
            addCriterion("SIMU_COURSE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSimuCourseIdEqualTo(Integer value) {
            addCriterion("SIMU_COURSE_ID =", value, "simuCourseId");
            return (Criteria) this;
        }

        public Criteria andSimuCourseIdNotEqualTo(Integer value) {
            addCriterion("SIMU_COURSE_ID <>", value, "simuCourseId");
            return (Criteria) this;
        }

        public Criteria andSimuCourseIdGreaterThan(Integer value) {
            addCriterion("SIMU_COURSE_ID >", value, "simuCourseId");
            return (Criteria) this;
        }

        public Criteria andSimuCourseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("SIMU_COURSE_ID >=", value, "simuCourseId");
            return (Criteria) this;
        }

        public Criteria andSimuCourseIdLessThan(Integer value) {
            addCriterion("SIMU_COURSE_ID <", value, "simuCourseId");
            return (Criteria) this;
        }

        public Criteria andSimuCourseIdLessThanOrEqualTo(Integer value) {
            addCriterion("SIMU_COURSE_ID <=", value, "simuCourseId");
            return (Criteria) this;
        }

        public Criteria andSimuCourseIdIn(List<Integer> values) {
            addCriterion("SIMU_COURSE_ID in", values, "simuCourseId");
            return (Criteria) this;
        }

        public Criteria andSimuCourseIdNotIn(List<Integer> values) {
            addCriterion("SIMU_COURSE_ID not in", values, "simuCourseId");
            return (Criteria) this;
        }

        public Criteria andSimuCourseIdBetween(Integer value1, Integer value2) {
            addCriterion("SIMU_COURSE_ID between", value1, value2, "simuCourseId");
            return (Criteria) this;
        }

        public Criteria andSimuCourseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("SIMU_COURSE_ID not between", value1, value2, "simuCourseId");
            return (Criteria) this;
        }

        public Criteria andSimuExamIdIsNull() {
            addCriterion("SIMU_EXAM_ID is null");
            return (Criteria) this;
        }

        public Criteria andSimuExamIdIsNotNull() {
            addCriterion("SIMU_EXAM_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSimuExamIdEqualTo(Integer value) {
            addCriterion("SIMU_EXAM_ID =", value, "simuExamId");
            return (Criteria) this;
        }

        public Criteria andSimuExamIdNotEqualTo(Integer value) {
            addCriterion("SIMU_EXAM_ID <>", value, "simuExamId");
            return (Criteria) this;
        }

        public Criteria andSimuExamIdGreaterThan(Integer value) {
            addCriterion("SIMU_EXAM_ID >", value, "simuExamId");
            return (Criteria) this;
        }

        public Criteria andSimuExamIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("SIMU_EXAM_ID >=", value, "simuExamId");
            return (Criteria) this;
        }

        public Criteria andSimuExamIdLessThan(Integer value) {
            addCriterion("SIMU_EXAM_ID <", value, "simuExamId");
            return (Criteria) this;
        }

        public Criteria andSimuExamIdLessThanOrEqualTo(Integer value) {
            addCriterion("SIMU_EXAM_ID <=", value, "simuExamId");
            return (Criteria) this;
        }

        public Criteria andSimuExamIdIn(List<Integer> values) {
            addCriterion("SIMU_EXAM_ID in", values, "simuExamId");
            return (Criteria) this;
        }

        public Criteria andSimuExamIdNotIn(List<Integer> values) {
            addCriterion("SIMU_EXAM_ID not in", values, "simuExamId");
            return (Criteria) this;
        }

        public Criteria andSimuExamIdBetween(Integer value1, Integer value2) {
            addCriterion("SIMU_EXAM_ID between", value1, value2, "simuExamId");
            return (Criteria) this;
        }

        public Criteria andSimuExamIdNotBetween(Integer value1, Integer value2) {
            addCriterion("SIMU_EXAM_ID not between", value1, value2, "simuExamId");
            return (Criteria) this;
        }

        public Criteria andSimuStuIdIsNull() {
            addCriterion("SIMU_STU_ID is null");
            return (Criteria) this;
        }

        public Criteria andSimuStuIdIsNotNull() {
            addCriterion("SIMU_STU_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSimuStuIdEqualTo(Integer value) {
            addCriterion("SIMU_STU_ID =", value, "simuStuId");
            return (Criteria) this;
        }

        public Criteria andSimuStuIdNotEqualTo(Integer value) {
            addCriterion("SIMU_STU_ID <>", value, "simuStuId");
            return (Criteria) this;
        }

        public Criteria andSimuStuIdGreaterThan(Integer value) {
            addCriterion("SIMU_STU_ID >", value, "simuStuId");
            return (Criteria) this;
        }

        public Criteria andSimuStuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("SIMU_STU_ID >=", value, "simuStuId");
            return (Criteria) this;
        }

        public Criteria andSimuStuIdLessThan(Integer value) {
            addCriterion("SIMU_STU_ID <", value, "simuStuId");
            return (Criteria) this;
        }

        public Criteria andSimuStuIdLessThanOrEqualTo(Integer value) {
            addCriterion("SIMU_STU_ID <=", value, "simuStuId");
            return (Criteria) this;
        }

        public Criteria andSimuStuIdIn(List<Integer> values) {
            addCriterion("SIMU_STU_ID in", values, "simuStuId");
            return (Criteria) this;
        }

        public Criteria andSimuStuIdNotIn(List<Integer> values) {
            addCriterion("SIMU_STU_ID not in", values, "simuStuId");
            return (Criteria) this;
        }

        public Criteria andSimuStuIdBetween(Integer value1, Integer value2) {
            addCriterion("SIMU_STU_ID between", value1, value2, "simuStuId");
            return (Criteria) this;
        }

        public Criteria andSimuStuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("SIMU_STU_ID not between", value1, value2, "simuStuId");
            return (Criteria) this;
        }

        public Criteria andSimuStatusIsNull() {
            addCriterion("SIMU_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andSimuStatusIsNotNull() {
            addCriterion("SIMU_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andSimuStatusEqualTo(String value) {
            addCriterion("SIMU_STATUS =", value, "simuStatus");
            return (Criteria) this;
        }

        public Criteria andSimuStatusNotEqualTo(String value) {
            addCriterion("SIMU_STATUS <>", value, "simuStatus");
            return (Criteria) this;
        }

        public Criteria andSimuStatusGreaterThan(String value) {
            addCriterion("SIMU_STATUS >", value, "simuStatus");
            return (Criteria) this;
        }

        public Criteria andSimuStatusGreaterThanOrEqualTo(String value) {
            addCriterion("SIMU_STATUS >=", value, "simuStatus");
            return (Criteria) this;
        }

        public Criteria andSimuStatusLessThan(String value) {
            addCriterion("SIMU_STATUS <", value, "simuStatus");
            return (Criteria) this;
        }

        public Criteria andSimuStatusLessThanOrEqualTo(String value) {
            addCriterion("SIMU_STATUS <=", value, "simuStatus");
            return (Criteria) this;
        }

        public Criteria andSimuStatusLike(String value) {
            addCriterion("SIMU_STATUS like", value, "simuStatus");
            return (Criteria) this;
        }

        public Criteria andSimuStatusNotLike(String value) {
            addCriterion("SIMU_STATUS not like", value, "simuStatus");
            return (Criteria) this;
        }

        public Criteria andSimuStatusIn(List<String> values) {
            addCriterion("SIMU_STATUS in", values, "simuStatus");
            return (Criteria) this;
        }

        public Criteria andSimuStatusNotIn(List<String> values) {
            addCriterion("SIMU_STATUS not in", values, "simuStatus");
            return (Criteria) this;
        }

        public Criteria andSimuStatusBetween(String value1, String value2) {
            addCriterion("SIMU_STATUS between", value1, value2, "simuStatus");
            return (Criteria) this;
        }

        public Criteria andSimuStatusNotBetween(String value1, String value2) {
            addCriterion("SIMU_STATUS not between", value1, value2, "simuStatus");
            return (Criteria) this;
        }

        public Criteria andSimuTextAnswerIsNull() {
            addCriterion("SIMU_TEXT_ANSWER is null");
            return (Criteria) this;
        }

        public Criteria andSimuTextAnswerIsNotNull() {
            addCriterion("SIMU_TEXT_ANSWER is not null");
            return (Criteria) this;
        }

        public Criteria andSimuTextAnswerEqualTo(String value) {
            addCriterion("SIMU_TEXT_ANSWER =", value, "simuTextAnswer");
            return (Criteria) this;
        }

        public Criteria andSimuTextAnswerNotEqualTo(String value) {
            addCriterion("SIMU_TEXT_ANSWER <>", value, "simuTextAnswer");
            return (Criteria) this;
        }

        public Criteria andSimuTextAnswerGreaterThan(String value) {
            addCriterion("SIMU_TEXT_ANSWER >", value, "simuTextAnswer");
            return (Criteria) this;
        }

        public Criteria andSimuTextAnswerGreaterThanOrEqualTo(String value) {
            addCriterion("SIMU_TEXT_ANSWER >=", value, "simuTextAnswer");
            return (Criteria) this;
        }

        public Criteria andSimuTextAnswerLessThan(String value) {
            addCriterion("SIMU_TEXT_ANSWER <", value, "simuTextAnswer");
            return (Criteria) this;
        }

        public Criteria andSimuTextAnswerLessThanOrEqualTo(String value) {
            addCriterion("SIMU_TEXT_ANSWER <=", value, "simuTextAnswer");
            return (Criteria) this;
        }

        public Criteria andSimuTextAnswerLike(String value) {
            addCriterion("SIMU_TEXT_ANSWER like", value, "simuTextAnswer");
            return (Criteria) this;
        }

        public Criteria andSimuTextAnswerNotLike(String value) {
            addCriterion("SIMU_TEXT_ANSWER not like", value, "simuTextAnswer");
            return (Criteria) this;
        }

        public Criteria andSimuTextAnswerIn(List<String> values) {
            addCriterion("SIMU_TEXT_ANSWER in", values, "simuTextAnswer");
            return (Criteria) this;
        }

        public Criteria andSimuTextAnswerNotIn(List<String> values) {
            addCriterion("SIMU_TEXT_ANSWER not in", values, "simuTextAnswer");
            return (Criteria) this;
        }

        public Criteria andSimuTextAnswerBetween(String value1, String value2) {
            addCriterion("SIMU_TEXT_ANSWER between", value1, value2, "simuTextAnswer");
            return (Criteria) this;
        }

        public Criteria andSimuTextAnswerNotBetween(String value1, String value2) {
            addCriterion("SIMU_TEXT_ANSWER not between", value1, value2, "simuTextAnswer");
            return (Criteria) this;
        }

        public Criteria andSimuAttachAnswerIsNull() {
            addCriterion("SIMU_ATTACH_ANSWER is null");
            return (Criteria) this;
        }

        public Criteria andSimuAttachAnswerIsNotNull() {
            addCriterion("SIMU_ATTACH_ANSWER is not null");
            return (Criteria) this;
        }

        public Criteria andSimuAttachAnswerEqualTo(String value) {
            addCriterion("SIMU_ATTACH_ANSWER =", value, "simuAttachAnswer");
            return (Criteria) this;
        }

        public Criteria andSimuAttachAnswerNotEqualTo(String value) {
            addCriterion("SIMU_ATTACH_ANSWER <>", value, "simuAttachAnswer");
            return (Criteria) this;
        }

        public Criteria andSimuAttachAnswerGreaterThan(String value) {
            addCriterion("SIMU_ATTACH_ANSWER >", value, "simuAttachAnswer");
            return (Criteria) this;
        }

        public Criteria andSimuAttachAnswerGreaterThanOrEqualTo(String value) {
            addCriterion("SIMU_ATTACH_ANSWER >=", value, "simuAttachAnswer");
            return (Criteria) this;
        }

        public Criteria andSimuAttachAnswerLessThan(String value) {
            addCriterion("SIMU_ATTACH_ANSWER <", value, "simuAttachAnswer");
            return (Criteria) this;
        }

        public Criteria andSimuAttachAnswerLessThanOrEqualTo(String value) {
            addCriterion("SIMU_ATTACH_ANSWER <=", value, "simuAttachAnswer");
            return (Criteria) this;
        }

        public Criteria andSimuAttachAnswerLike(String value) {
            addCriterion("SIMU_ATTACH_ANSWER like", value, "simuAttachAnswer");
            return (Criteria) this;
        }

        public Criteria andSimuAttachAnswerNotLike(String value) {
            addCriterion("SIMU_ATTACH_ANSWER not like", value, "simuAttachAnswer");
            return (Criteria) this;
        }

        public Criteria andSimuAttachAnswerIn(List<String> values) {
            addCriterion("SIMU_ATTACH_ANSWER in", values, "simuAttachAnswer");
            return (Criteria) this;
        }

        public Criteria andSimuAttachAnswerNotIn(List<String> values) {
            addCriterion("SIMU_ATTACH_ANSWER not in", values, "simuAttachAnswer");
            return (Criteria) this;
        }

        public Criteria andSimuAttachAnswerBetween(String value1, String value2) {
            addCriterion("SIMU_ATTACH_ANSWER between", value1, value2, "simuAttachAnswer");
            return (Criteria) this;
        }

        public Criteria andSimuAttachAnswerNotBetween(String value1, String value2) {
            addCriterion("SIMU_ATTACH_ANSWER not between", value1, value2, "simuAttachAnswer");
            return (Criteria) this;
        }

        public Criteria andSimuCommitTimeIsNull() {
            addCriterion("SIMU_COMMIT_TIME is null");
            return (Criteria) this;
        }

        public Criteria andSimuCommitTimeIsNotNull() {
            addCriterion("SIMU_COMMIT_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andSimuCommitTimeEqualTo(Date value) {
            addCriterion("SIMU_COMMIT_TIME =", value, "simuCommitTime");
            return (Criteria) this;
        }

        public Criteria andSimuCommitTimeNotEqualTo(Date value) {
            addCriterion("SIMU_COMMIT_TIME <>", value, "simuCommitTime");
            return (Criteria) this;
        }

        public Criteria andSimuCommitTimeGreaterThan(Date value) {
            addCriterion("SIMU_COMMIT_TIME >", value, "simuCommitTime");
            return (Criteria) this;
        }

        public Criteria andSimuCommitTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SIMU_COMMIT_TIME >=", value, "simuCommitTime");
            return (Criteria) this;
        }

        public Criteria andSimuCommitTimeLessThan(Date value) {
            addCriterion("SIMU_COMMIT_TIME <", value, "simuCommitTime");
            return (Criteria) this;
        }

        public Criteria andSimuCommitTimeLessThanOrEqualTo(Date value) {
            addCriterion("SIMU_COMMIT_TIME <=", value, "simuCommitTime");
            return (Criteria) this;
        }

        public Criteria andSimuCommitTimeIn(List<Date> values) {
            addCriterion("SIMU_COMMIT_TIME in", values, "simuCommitTime");
            return (Criteria) this;
        }

        public Criteria andSimuCommitTimeNotIn(List<Date> values) {
            addCriterion("SIMU_COMMIT_TIME not in", values, "simuCommitTime");
            return (Criteria) this;
        }

        public Criteria andSimuCommitTimeBetween(Date value1, Date value2) {
            addCriterion("SIMU_COMMIT_TIME between", value1, value2, "simuCommitTime");
            return (Criteria) this;
        }

        public Criteria andSimuCommitTimeNotBetween(Date value1, Date value2) {
            addCriterion("SIMU_COMMIT_TIME not between", value1, value2, "simuCommitTime");
            return (Criteria) this;
        }

        public Criteria andSimuIsRightIsNull() {
            addCriterion("SIMU_IS_RIGHT is null");
            return (Criteria) this;
        }

        public Criteria andSimuIsRightIsNotNull() {
            addCriterion("SIMU_IS_RIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andSimuIsRightEqualTo(String value) {
            addCriterion("SIMU_IS_RIGHT =", value, "simuIsRight");
            return (Criteria) this;
        }

        public Criteria andSimuIsRightNotEqualTo(String value) {
            addCriterion("SIMU_IS_RIGHT <>", value, "simuIsRight");
            return (Criteria) this;
        }

        public Criteria andSimuIsRightGreaterThan(String value) {
            addCriterion("SIMU_IS_RIGHT >", value, "simuIsRight");
            return (Criteria) this;
        }

        public Criteria andSimuIsRightGreaterThanOrEqualTo(String value) {
            addCriterion("SIMU_IS_RIGHT >=", value, "simuIsRight");
            return (Criteria) this;
        }

        public Criteria andSimuIsRightLessThan(String value) {
            addCriterion("SIMU_IS_RIGHT <", value, "simuIsRight");
            return (Criteria) this;
        }

        public Criteria andSimuIsRightLessThanOrEqualTo(String value) {
            addCriterion("SIMU_IS_RIGHT <=", value, "simuIsRight");
            return (Criteria) this;
        }

        public Criteria andSimuIsRightLike(String value) {
            addCriterion("SIMU_IS_RIGHT like", value, "simuIsRight");
            return (Criteria) this;
        }

        public Criteria andSimuIsRightNotLike(String value) {
            addCriterion("SIMU_IS_RIGHT not like", value, "simuIsRight");
            return (Criteria) this;
        }

        public Criteria andSimuIsRightIn(List<String> values) {
            addCriterion("SIMU_IS_RIGHT in", values, "simuIsRight");
            return (Criteria) this;
        }

        public Criteria andSimuIsRightNotIn(List<String> values) {
            addCriterion("SIMU_IS_RIGHT not in", values, "simuIsRight");
            return (Criteria) this;
        }

        public Criteria andSimuIsRightBetween(String value1, String value2) {
            addCriterion("SIMU_IS_RIGHT between", value1, value2, "simuIsRight");
            return (Criteria) this;
        }

        public Criteria andSimuIsRightNotBetween(String value1, String value2) {
            addCriterion("SIMU_IS_RIGHT not between", value1, value2, "simuIsRight");
            return (Criteria) this;
        }

        public Criteria andSimuScoreIsNull() {
            addCriterion("SIMU_SCORE is null");
            return (Criteria) this;
        }

        public Criteria andSimuScoreIsNotNull() {
            addCriterion("SIMU_SCORE is not null");
            return (Criteria) this;
        }

        public Criteria andSimuScoreEqualTo(Integer value) {
            addCriterion("SIMU_SCORE =", value, "simuScore");
            return (Criteria) this;
        }

        public Criteria andSimuScoreNotEqualTo(Integer value) {
            addCriterion("SIMU_SCORE <>", value, "simuScore");
            return (Criteria) this;
        }

        public Criteria andSimuScoreGreaterThan(Integer value) {
            addCriterion("SIMU_SCORE >", value, "simuScore");
            return (Criteria) this;
        }

        public Criteria andSimuScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("SIMU_SCORE >=", value, "simuScore");
            return (Criteria) this;
        }

        public Criteria andSimuScoreLessThan(Integer value) {
            addCriterion("SIMU_SCORE <", value, "simuScore");
            return (Criteria) this;
        }

        public Criteria andSimuScoreLessThanOrEqualTo(Integer value) {
            addCriterion("SIMU_SCORE <=", value, "simuScore");
            return (Criteria) this;
        }

        public Criteria andSimuScoreIn(List<Integer> values) {
            addCriterion("SIMU_SCORE in", values, "simuScore");
            return (Criteria) this;
        }

        public Criteria andSimuScoreNotIn(List<Integer> values) {
            addCriterion("SIMU_SCORE not in", values, "simuScore");
            return (Criteria) this;
        }

        public Criteria andSimuScoreBetween(Integer value1, Integer value2) {
            addCriterion("SIMU_SCORE between", value1, value2, "simuScore");
            return (Criteria) this;
        }

        public Criteria andSimuScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("SIMU_SCORE not between", value1, value2, "simuScore");
            return (Criteria) this;
        }

        public Criteria andSimuCheckFlagIsNull() {
            addCriterion("SIMU_CHECK_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andSimuCheckFlagIsNotNull() {
            addCriterion("SIMU_CHECK_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andSimuCheckFlagEqualTo(String value) {
            addCriterion("SIMU_CHECK_FLAG =", value, "simuCheckFlag");
            return (Criteria) this;
        }

        public Criteria andSimuCheckFlagNotEqualTo(String value) {
            addCriterion("SIMU_CHECK_FLAG <>", value, "simuCheckFlag");
            return (Criteria) this;
        }

        public Criteria andSimuCheckFlagGreaterThan(String value) {
            addCriterion("SIMU_CHECK_FLAG >", value, "simuCheckFlag");
            return (Criteria) this;
        }

        public Criteria andSimuCheckFlagGreaterThanOrEqualTo(String value) {
            addCriterion("SIMU_CHECK_FLAG >=", value, "simuCheckFlag");
            return (Criteria) this;
        }

        public Criteria andSimuCheckFlagLessThan(String value) {
            addCriterion("SIMU_CHECK_FLAG <", value, "simuCheckFlag");
            return (Criteria) this;
        }

        public Criteria andSimuCheckFlagLessThanOrEqualTo(String value) {
            addCriterion("SIMU_CHECK_FLAG <=", value, "simuCheckFlag");
            return (Criteria) this;
        }

        public Criteria andSimuCheckFlagLike(String value) {
            addCriterion("SIMU_CHECK_FLAG like", value, "simuCheckFlag");
            return (Criteria) this;
        }

        public Criteria andSimuCheckFlagNotLike(String value) {
            addCriterion("SIMU_CHECK_FLAG not like", value, "simuCheckFlag");
            return (Criteria) this;
        }

        public Criteria andSimuCheckFlagIn(List<String> values) {
            addCriterion("SIMU_CHECK_FLAG in", values, "simuCheckFlag");
            return (Criteria) this;
        }

        public Criteria andSimuCheckFlagNotIn(List<String> values) {
            addCriterion("SIMU_CHECK_FLAG not in", values, "simuCheckFlag");
            return (Criteria) this;
        }

        public Criteria andSimuCheckFlagBetween(String value1, String value2) {
            addCriterion("SIMU_CHECK_FLAG between", value1, value2, "simuCheckFlag");
            return (Criteria) this;
        }

        public Criteria andSimuCheckFlagNotBetween(String value1, String value2) {
            addCriterion("SIMU_CHECK_FLAG not between", value1, value2, "simuCheckFlag");
            return (Criteria) this;
        }

        public Criteria andSimuUserIdIsNull() {
            addCriterion("SIMU_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andSimuUserIdIsNotNull() {
            addCriterion("SIMU_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSimuUserIdEqualTo(Integer value) {
            addCriterion("SIMU_USER_ID =", value, "simuUserId");
            return (Criteria) this;
        }

        public Criteria andSimuUserIdNotEqualTo(Integer value) {
            addCriterion("SIMU_USER_ID <>", value, "simuUserId");
            return (Criteria) this;
        }

        public Criteria andSimuUserIdGreaterThan(Integer value) {
            addCriterion("SIMU_USER_ID >", value, "simuUserId");
            return (Criteria) this;
        }

        public Criteria andSimuUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("SIMU_USER_ID >=", value, "simuUserId");
            return (Criteria) this;
        }

        public Criteria andSimuUserIdLessThan(Integer value) {
            addCriterion("SIMU_USER_ID <", value, "simuUserId");
            return (Criteria) this;
        }

        public Criteria andSimuUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("SIMU_USER_ID <=", value, "simuUserId");
            return (Criteria) this;
        }

        public Criteria andSimuUserIdIn(List<Integer> values) {
            addCriterion("SIMU_USER_ID in", values, "simuUserId");
            return (Criteria) this;
        }

        public Criteria andSimuUserIdNotIn(List<Integer> values) {
            addCriterion("SIMU_USER_ID not in", values, "simuUserId");
            return (Criteria) this;
        }

        public Criteria andSimuUserIdBetween(Integer value1, Integer value2) {
            addCriterion("SIMU_USER_ID between", value1, value2, "simuUserId");
            return (Criteria) this;
        }

        public Criteria andSimuUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("SIMU_USER_ID not between", value1, value2, "simuUserId");
            return (Criteria) this;
        }

        public Criteria andSimuCheckTimeIsNull() {
            addCriterion("SIMU_CHECK_TIME is null");
            return (Criteria) this;
        }

        public Criteria andSimuCheckTimeIsNotNull() {
            addCriterion("SIMU_CHECK_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andSimuCheckTimeEqualTo(Date value) {
            addCriterion("SIMU_CHECK_TIME =", value, "simuCheckTime");
            return (Criteria) this;
        }

        public Criteria andSimuCheckTimeNotEqualTo(Date value) {
            addCriterion("SIMU_CHECK_TIME <>", value, "simuCheckTime");
            return (Criteria) this;
        }

        public Criteria andSimuCheckTimeGreaterThan(Date value) {
            addCriterion("SIMU_CHECK_TIME >", value, "simuCheckTime");
            return (Criteria) this;
        }

        public Criteria andSimuCheckTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SIMU_CHECK_TIME >=", value, "simuCheckTime");
            return (Criteria) this;
        }

        public Criteria andSimuCheckTimeLessThan(Date value) {
            addCriterion("SIMU_CHECK_TIME <", value, "simuCheckTime");
            return (Criteria) this;
        }

        public Criteria andSimuCheckTimeLessThanOrEqualTo(Date value) {
            addCriterion("SIMU_CHECK_TIME <=", value, "simuCheckTime");
            return (Criteria) this;
        }

        public Criteria andSimuCheckTimeIn(List<Date> values) {
            addCriterion("SIMU_CHECK_TIME in", values, "simuCheckTime");
            return (Criteria) this;
        }

        public Criteria andSimuCheckTimeNotIn(List<Date> values) {
            addCriterion("SIMU_CHECK_TIME not in", values, "simuCheckTime");
            return (Criteria) this;
        }

        public Criteria andSimuCheckTimeBetween(Date value1, Date value2) {
            addCriterion("SIMU_CHECK_TIME between", value1, value2, "simuCheckTime");
            return (Criteria) this;
        }

        public Criteria andSimuCheckTimeNotBetween(Date value1, Date value2) {
            addCriterion("SIMU_CHECK_TIME not between", value1, value2, "simuCheckTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_simulate_test
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 25 19:26:27 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_simulate_test
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}