package com.chinasofti.cetp.study.dao;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.chinasofti.cetp.study.model.MoreTechType;
import com.chinasofti.cetp.study.model.TechType;
import com.chinasofti.cetp.study.model.TechTypeExample;

public interface TechTypeMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_tech_type
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int countByExample(TechTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_tech_type
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int deleteByExample(TechTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_tech_type
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int deleteByPrimaryKey(Integer techTypeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_tech_type
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int insert(TechType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_tech_type
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int insertSelective(TechType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_tech_type
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	List<TechType> selectByExample(TechTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_tech_type
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	TechType selectByPrimaryKey(Integer techTypeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_tech_type
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int updateByExampleSelective(@Param("record") TechType record,
			@Param("example") TechTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_tech_type
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int updateByExample(@Param("record") TechType record,
			@Param("example") TechTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_tech_type
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int updateByPrimaryKeySelective(TechType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_tech_type
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int updateByPrimaryKey(TechType record);

	List<MoreTechType> getTreeData(HashMap<String, Integer> map);

	List<MoreTechType> selectAllTechType();

	List<MoreTechType> selectAllTechTypeTest(RowBounds rowBounds);
	 
	public List<MoreTechType> selectTechTypeManage();
	    
	List<TechType> selectLikeByName(HashMap map);
	
	List<TechType> checkTechTypeManage(Integer techTypeId);
}