package com.chinasofti.cetp.admin.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class JobIntentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_job_intent
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_job_intent
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_job_intent
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_job_intent
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public JobIntentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_job_intent
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_job_intent
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_job_intent
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_job_intent
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_job_intent
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_job_intent
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_job_intent
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_job_intent
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_job_intent
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_job_intent
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_job_intent
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andJiIdIsNull() {
            addCriterion("JI_ID is null");
            return (Criteria) this;
        }

        public Criteria andJiIdIsNotNull() {
            addCriterion("JI_ID is not null");
            return (Criteria) this;
        }

        public Criteria andJiIdEqualTo(Integer value) {
            addCriterion("JI_ID =", value, "jiId");
            return (Criteria) this;
        }

        public Criteria andJiIdNotEqualTo(Integer value) {
            addCriterion("JI_ID <>", value, "jiId");
            return (Criteria) this;
        }

        public Criteria andJiIdGreaterThan(Integer value) {
            addCriterion("JI_ID >", value, "jiId");
            return (Criteria) this;
        }

        public Criteria andJiIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("JI_ID >=", value, "jiId");
            return (Criteria) this;
        }

        public Criteria andJiIdLessThan(Integer value) {
            addCriterion("JI_ID <", value, "jiId");
            return (Criteria) this;
        }

        public Criteria andJiIdLessThanOrEqualTo(Integer value) {
            addCriterion("JI_ID <=", value, "jiId");
            return (Criteria) this;
        }

        public Criteria andJiIdIn(List<Integer> values) {
            addCriterion("JI_ID in", values, "jiId");
            return (Criteria) this;
        }

        public Criteria andJiIdNotIn(List<Integer> values) {
            addCriterion("JI_ID not in", values, "jiId");
            return (Criteria) this;
        }

        public Criteria andJiIdBetween(Integer value1, Integer value2) {
            addCriterion("JI_ID between", value1, value2, "jiId");
            return (Criteria) this;
        }

        public Criteria andJiIdNotBetween(Integer value1, Integer value2) {
            addCriterion("JI_ID not between", value1, value2, "jiId");
            return (Criteria) this;
        }

        public Criteria andJiStuIdIsNull() {
            addCriterion("JI_STU_ID is null");
            return (Criteria) this;
        }

        public Criteria andJiStuIdIsNotNull() {
            addCriterion("JI_STU_ID is not null");
            return (Criteria) this;
        }

        public Criteria andJiStuIdEqualTo(Integer value) {
            addCriterion("JI_STU_ID =", value, "jiStuId");
            return (Criteria) this;
        }

        public Criteria andJiStuIdNotEqualTo(Integer value) {
            addCriterion("JI_STU_ID <>", value, "jiStuId");
            return (Criteria) this;
        }

        public Criteria andJiStuIdGreaterThan(Integer value) {
            addCriterion("JI_STU_ID >", value, "jiStuId");
            return (Criteria) this;
        }

        public Criteria andJiStuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("JI_STU_ID >=", value, "jiStuId");
            return (Criteria) this;
        }

        public Criteria andJiStuIdLessThan(Integer value) {
            addCriterion("JI_STU_ID <", value, "jiStuId");
            return (Criteria) this;
        }

        public Criteria andJiStuIdLessThanOrEqualTo(Integer value) {
            addCriterion("JI_STU_ID <=", value, "jiStuId");
            return (Criteria) this;
        }

        public Criteria andJiStuIdIn(List<Integer> values) {
            addCriterion("JI_STU_ID in", values, "jiStuId");
            return (Criteria) this;
        }

        public Criteria andJiStuIdNotIn(List<Integer> values) {
            addCriterion("JI_STU_ID not in", values, "jiStuId");
            return (Criteria) this;
        }

        public Criteria andJiStuIdBetween(Integer value1, Integer value2) {
            addCriterion("JI_STU_ID between", value1, value2, "jiStuId");
            return (Criteria) this;
        }

        public Criteria andJiStuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("JI_STU_ID not between", value1, value2, "jiStuId");
            return (Criteria) this;
        }

        public Criteria andJiSelcity1IsNull() {
            addCriterion("JI_SELCITY1 is null");
            return (Criteria) this;
        }

        public Criteria andJiSelcity1IsNotNull() {
            addCriterion("JI_SELCITY1 is not null");
            return (Criteria) this;
        }

        public Criteria andJiSelcity1EqualTo(String value) {
            addCriterion("JI_SELCITY1 =", value, "jiSelcity1");
            return (Criteria) this;
        }

        public Criteria andJiSelcity1NotEqualTo(String value) {
            addCriterion("JI_SELCITY1 <>", value, "jiSelcity1");
            return (Criteria) this;
        }

        public Criteria andJiSelcity1GreaterThan(String value) {
            addCriterion("JI_SELCITY1 >", value, "jiSelcity1");
            return (Criteria) this;
        }

        public Criteria andJiSelcity1GreaterThanOrEqualTo(String value) {
            addCriterion("JI_SELCITY1 >=", value, "jiSelcity1");
            return (Criteria) this;
        }

        public Criteria andJiSelcity1LessThan(String value) {
            addCriterion("JI_SELCITY1 <", value, "jiSelcity1");
            return (Criteria) this;
        }

        public Criteria andJiSelcity1LessThanOrEqualTo(String value) {
            addCriterion("JI_SELCITY1 <=", value, "jiSelcity1");
            return (Criteria) this;
        }

        public Criteria andJiSelcity1Like(String value) {
            addCriterion("JI_SELCITY1 like", value, "jiSelcity1");
            return (Criteria) this;
        }

        public Criteria andJiSelcity1NotLike(String value) {
            addCriterion("JI_SELCITY1 not like", value, "jiSelcity1");
            return (Criteria) this;
        }

        public Criteria andJiSelcity1In(List<String> values) {
            addCriterion("JI_SELCITY1 in", values, "jiSelcity1");
            return (Criteria) this;
        }

        public Criteria andJiSelcity1NotIn(List<String> values) {
            addCriterion("JI_SELCITY1 not in", values, "jiSelcity1");
            return (Criteria) this;
        }

        public Criteria andJiSelcity1Between(String value1, String value2) {
            addCriterion("JI_SELCITY1 between", value1, value2, "jiSelcity1");
            return (Criteria) this;
        }

        public Criteria andJiSelcity1NotBetween(String value1, String value2) {
            addCriterion("JI_SELCITY1 not between", value1, value2, "jiSelcity1");
            return (Criteria) this;
        }

        public Criteria andJiSelcity2IsNull() {
            addCriterion("JI_SELCITY2 is null");
            return (Criteria) this;
        }

        public Criteria andJiSelcity2IsNotNull() {
            addCriterion("JI_SELCITY2 is not null");
            return (Criteria) this;
        }

        public Criteria andJiSelcity2EqualTo(String value) {
            addCriterion("JI_SELCITY2 =", value, "jiSelcity2");
            return (Criteria) this;
        }

        public Criteria andJiSelcity2NotEqualTo(String value) {
            addCriterion("JI_SELCITY2 <>", value, "jiSelcity2");
            return (Criteria) this;
        }

        public Criteria andJiSelcity2GreaterThan(String value) {
            addCriterion("JI_SELCITY2 >", value, "jiSelcity2");
            return (Criteria) this;
        }

        public Criteria andJiSelcity2GreaterThanOrEqualTo(String value) {
            addCriterion("JI_SELCITY2 >=", value, "jiSelcity2");
            return (Criteria) this;
        }

        public Criteria andJiSelcity2LessThan(String value) {
            addCriterion("JI_SELCITY2 <", value, "jiSelcity2");
            return (Criteria) this;
        }

        public Criteria andJiSelcity2LessThanOrEqualTo(String value) {
            addCriterion("JI_SELCITY2 <=", value, "jiSelcity2");
            return (Criteria) this;
        }

        public Criteria andJiSelcity2Like(String value) {
            addCriterion("JI_SELCITY2 like", value, "jiSelcity2");
            return (Criteria) this;
        }

        public Criteria andJiSelcity2NotLike(String value) {
            addCriterion("JI_SELCITY2 not like", value, "jiSelcity2");
            return (Criteria) this;
        }

        public Criteria andJiSelcity2In(List<String> values) {
            addCriterion("JI_SELCITY2 in", values, "jiSelcity2");
            return (Criteria) this;
        }

        public Criteria andJiSelcity2NotIn(List<String> values) {
            addCriterion("JI_SELCITY2 not in", values, "jiSelcity2");
            return (Criteria) this;
        }

        public Criteria andJiSelcity2Between(String value1, String value2) {
            addCriterion("JI_SELCITY2 between", value1, value2, "jiSelcity2");
            return (Criteria) this;
        }

        public Criteria andJiSelcity2NotBetween(String value1, String value2) {
            addCriterion("JI_SELCITY2 not between", value1, value2, "jiSelcity2");
            return (Criteria) this;
        }

        public Criteria andJiWorkYearsIsNull() {
            addCriterion("JI_WORK_YEARS is null");
            return (Criteria) this;
        }

        public Criteria andJiWorkYearsIsNotNull() {
            addCriterion("JI_WORK_YEARS is not null");
            return (Criteria) this;
        }

        public Criteria andJiWorkYearsEqualTo(Integer value) {
            addCriterion("JI_WORK_YEARS =", value, "jiWorkYears");
            return (Criteria) this;
        }

        public Criteria andJiWorkYearsNotEqualTo(Integer value) {
            addCriterion("JI_WORK_YEARS <>", value, "jiWorkYears");
            return (Criteria) this;
        }

        public Criteria andJiWorkYearsGreaterThan(Integer value) {
            addCriterion("JI_WORK_YEARS >", value, "jiWorkYears");
            return (Criteria) this;
        }

        public Criteria andJiWorkYearsGreaterThanOrEqualTo(Integer value) {
            addCriterion("JI_WORK_YEARS >=", value, "jiWorkYears");
            return (Criteria) this;
        }

        public Criteria andJiWorkYearsLessThan(Integer value) {
            addCriterion("JI_WORK_YEARS <", value, "jiWorkYears");
            return (Criteria) this;
        }

        public Criteria andJiWorkYearsLessThanOrEqualTo(Integer value) {
            addCriterion("JI_WORK_YEARS <=", value, "jiWorkYears");
            return (Criteria) this;
        }

        public Criteria andJiWorkYearsIn(List<Integer> values) {
            addCriterion("JI_WORK_YEARS in", values, "jiWorkYears");
            return (Criteria) this;
        }

        public Criteria andJiWorkYearsNotIn(List<Integer> values) {
            addCriterion("JI_WORK_YEARS not in", values, "jiWorkYears");
            return (Criteria) this;
        }

        public Criteria andJiWorkYearsBetween(Integer value1, Integer value2) {
            addCriterion("JI_WORK_YEARS between", value1, value2, "jiWorkYears");
            return (Criteria) this;
        }

        public Criteria andJiWorkYearsNotBetween(Integer value1, Integer value2) {
            addCriterion("JI_WORK_YEARS not between", value1, value2, "jiWorkYears");
            return (Criteria) this;
        }

        public Criteria andJiWorkStatusIsNull() {
            addCriterion("JI_WORK_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andJiWorkStatusIsNotNull() {
            addCriterion("JI_WORK_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andJiWorkStatusEqualTo(String value) {
            addCriterion("JI_WORK_STATUS =", value, "jiWorkStatus");
            return (Criteria) this;
        }

        public Criteria andJiWorkStatusNotEqualTo(String value) {
            addCriterion("JI_WORK_STATUS <>", value, "jiWorkStatus");
            return (Criteria) this;
        }

        public Criteria andJiWorkStatusGreaterThan(String value) {
            addCriterion("JI_WORK_STATUS >", value, "jiWorkStatus");
            return (Criteria) this;
        }

        public Criteria andJiWorkStatusGreaterThanOrEqualTo(String value) {
            addCriterion("JI_WORK_STATUS >=", value, "jiWorkStatus");
            return (Criteria) this;
        }

        public Criteria andJiWorkStatusLessThan(String value) {
            addCriterion("JI_WORK_STATUS <", value, "jiWorkStatus");
            return (Criteria) this;
        }

        public Criteria andJiWorkStatusLessThanOrEqualTo(String value) {
            addCriterion("JI_WORK_STATUS <=", value, "jiWorkStatus");
            return (Criteria) this;
        }

        public Criteria andJiWorkStatusLike(String value) {
            addCriterion("JI_WORK_STATUS like", value, "jiWorkStatus");
            return (Criteria) this;
        }

        public Criteria andJiWorkStatusNotLike(String value) {
            addCriterion("JI_WORK_STATUS not like", value, "jiWorkStatus");
            return (Criteria) this;
        }

        public Criteria andJiWorkStatusIn(List<String> values) {
            addCriterion("JI_WORK_STATUS in", values, "jiWorkStatus");
            return (Criteria) this;
        }

        public Criteria andJiWorkStatusNotIn(List<String> values) {
            addCriterion("JI_WORK_STATUS not in", values, "jiWorkStatus");
            return (Criteria) this;
        }

        public Criteria andJiWorkStatusBetween(String value1, String value2) {
            addCriterion("JI_WORK_STATUS between", value1, value2, "jiWorkStatus");
            return (Criteria) this;
        }

        public Criteria andJiWorkStatusNotBetween(String value1, String value2) {
            addCriterion("JI_WORK_STATUS not between", value1, value2, "jiWorkStatus");
            return (Criteria) this;
        }

        public Criteria andJiPositionIsNull() {
            addCriterion("JI_POSITION is null");
            return (Criteria) this;
        }

        public Criteria andJiPositionIsNotNull() {
            addCriterion("JI_POSITION is not null");
            return (Criteria) this;
        }

        public Criteria andJiPositionEqualTo(String value) {
            addCriterion("JI_POSITION =", value, "jiPosition");
            return (Criteria) this;
        }

        public Criteria andJiPositionNotEqualTo(String value) {
            addCriterion("JI_POSITION <>", value, "jiPosition");
            return (Criteria) this;
        }

        public Criteria andJiPositionGreaterThan(String value) {
            addCriterion("JI_POSITION >", value, "jiPosition");
            return (Criteria) this;
        }

        public Criteria andJiPositionGreaterThanOrEqualTo(String value) {
            addCriterion("JI_POSITION >=", value, "jiPosition");
            return (Criteria) this;
        }

        public Criteria andJiPositionLessThan(String value) {
            addCriterion("JI_POSITION <", value, "jiPosition");
            return (Criteria) this;
        }

        public Criteria andJiPositionLessThanOrEqualTo(String value) {
            addCriterion("JI_POSITION <=", value, "jiPosition");
            return (Criteria) this;
        }

        public Criteria andJiPositionLike(String value) {
            addCriterion("JI_POSITION like", value, "jiPosition");
            return (Criteria) this;
        }

        public Criteria andJiPositionNotLike(String value) {
            addCriterion("JI_POSITION not like", value, "jiPosition");
            return (Criteria) this;
        }

        public Criteria andJiPositionIn(List<String> values) {
            addCriterion("JI_POSITION in", values, "jiPosition");
            return (Criteria) this;
        }

        public Criteria andJiPositionNotIn(List<String> values) {
            addCriterion("JI_POSITION not in", values, "jiPosition");
            return (Criteria) this;
        }

        public Criteria andJiPositionBetween(String value1, String value2) {
            addCriterion("JI_POSITION between", value1, value2, "jiPosition");
            return (Criteria) this;
        }

        public Criteria andJiPositionNotBetween(String value1, String value2) {
            addCriterion("JI_POSITION not between", value1, value2, "jiPosition");
            return (Criteria) this;
        }

        public Criteria andJiDateIsNull() {
            addCriterion("JI_DATE is null");
            return (Criteria) this;
        }

        public Criteria andJiDateIsNotNull() {
            addCriterion("JI_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andJiDateEqualTo(Date value) {
            addCriterion("JI_DATE =", value, "jiDate");
            return (Criteria) this;
        }

        public Criteria andJiDateNotEqualTo(Date value) {
            addCriterion("JI_DATE <>", value, "jiDate");
            return (Criteria) this;
        }

        public Criteria andJiDateGreaterThan(Date value) {
            addCriterion("JI_DATE >", value, "jiDate");
            return (Criteria) this;
        }

        public Criteria andJiDateGreaterThanOrEqualTo(Date value) {
            addCriterion("JI_DATE >=", value, "jiDate");
            return (Criteria) this;
        }

        public Criteria andJiDateLessThan(Date value) {
            addCriterion("JI_DATE <", value, "jiDate");
            return (Criteria) this;
        }

        public Criteria andJiDateLessThanOrEqualTo(Date value) {
            addCriterion("JI_DATE <=", value, "jiDate");
            return (Criteria) this;
        }

        public Criteria andJiDateIn(List<Date> values) {
            addCriterion("JI_DATE in", values, "jiDate");
            return (Criteria) this;
        }

        public Criteria andJiDateNotIn(List<Date> values) {
            addCriterion("JI_DATE not in", values, "jiDate");
            return (Criteria) this;
        }

        public Criteria andJiDateBetween(Date value1, Date value2) {
            addCriterion("JI_DATE between", value1, value2, "jiDate");
            return (Criteria) this;
        }

        public Criteria andJiDateNotBetween(Date value1, Date value2) {
            addCriterion("JI_DATE not between", value1, value2, "jiDate");
            return (Criteria) this;
        }

        public Criteria andJiHopePayIsNull() {
            addCriterion("JI_HOPE_PAY is null");
            return (Criteria) this;
        }

        public Criteria andJiHopePayIsNotNull() {
            addCriterion("JI_HOPE_PAY is not null");
            return (Criteria) this;
        }

        public Criteria andJiHopePayEqualTo(String value) {
            addCriterion("JI_HOPE_PAY =", value, "jiHopePay");
            return (Criteria) this;
        }

        public Criteria andJiHopePayNotEqualTo(String value) {
            addCriterion("JI_HOPE_PAY <>", value, "jiHopePay");
            return (Criteria) this;
        }

        public Criteria andJiHopePayGreaterThan(String value) {
            addCriterion("JI_HOPE_PAY >", value, "jiHopePay");
            return (Criteria) this;
        }

        public Criteria andJiHopePayGreaterThanOrEqualTo(String value) {
            addCriterion("JI_HOPE_PAY >=", value, "jiHopePay");
            return (Criteria) this;
        }

        public Criteria andJiHopePayLessThan(String value) {
            addCriterion("JI_HOPE_PAY <", value, "jiHopePay");
            return (Criteria) this;
        }

        public Criteria andJiHopePayLessThanOrEqualTo(String value) {
            addCriterion("JI_HOPE_PAY <=", value, "jiHopePay");
            return (Criteria) this;
        }

        public Criteria andJiHopePayLike(String value) {
            addCriterion("JI_HOPE_PAY like", value, "jiHopePay");
            return (Criteria) this;
        }

        public Criteria andJiHopePayNotLike(String value) {
            addCriterion("JI_HOPE_PAY not like", value, "jiHopePay");
            return (Criteria) this;
        }

        public Criteria andJiHopePayIn(List<String> values) {
            addCriterion("JI_HOPE_PAY in", values, "jiHopePay");
            return (Criteria) this;
        }

        public Criteria andJiHopePayNotIn(List<String> values) {
            addCriterion("JI_HOPE_PAY not in", values, "jiHopePay");
            return (Criteria) this;
        }

        public Criteria andJiHopePayBetween(String value1, String value2) {
            addCriterion("JI_HOPE_PAY between", value1, value2, "jiHopePay");
            return (Criteria) this;
        }

        public Criteria andJiHopePayNotBetween(String value1, String value2) {
            addCriterion("JI_HOPE_PAY not between", value1, value2, "jiHopePay");
            return (Criteria) this;
        }

        public Criteria andJiResumeNameIsNull() {
            addCriterion("JI_RESUME_NAME is null");
            return (Criteria) this;
        }

        public Criteria andJiResumeNameIsNotNull() {
            addCriterion("JI_RESUME_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andJiResumeNameEqualTo(String value) {
            addCriterion("JI_RESUME_NAME =", value, "jiResumeName");
            return (Criteria) this;
        }

        public Criteria andJiResumeNameNotEqualTo(String value) {
            addCriterion("JI_RESUME_NAME <>", value, "jiResumeName");
            return (Criteria) this;
        }

        public Criteria andJiResumeNameGreaterThan(String value) {
            addCriterion("JI_RESUME_NAME >", value, "jiResumeName");
            return (Criteria) this;
        }

        public Criteria andJiResumeNameGreaterThanOrEqualTo(String value) {
            addCriterion("JI_RESUME_NAME >=", value, "jiResumeName");
            return (Criteria) this;
        }

        public Criteria andJiResumeNameLessThan(String value) {
            addCriterion("JI_RESUME_NAME <", value, "jiResumeName");
            return (Criteria) this;
        }

        public Criteria andJiResumeNameLessThanOrEqualTo(String value) {
            addCriterion("JI_RESUME_NAME <=", value, "jiResumeName");
            return (Criteria) this;
        }

        public Criteria andJiResumeNameLike(String value) {
            addCriterion("JI_RESUME_NAME like", value, "jiResumeName");
            return (Criteria) this;
        }

        public Criteria andJiResumeNameNotLike(String value) {
            addCriterion("JI_RESUME_NAME not like", value, "jiResumeName");
            return (Criteria) this;
        }

        public Criteria andJiResumeNameIn(List<String> values) {
            addCriterion("JI_RESUME_NAME in", values, "jiResumeName");
            return (Criteria) this;
        }

        public Criteria andJiResumeNameNotIn(List<String> values) {
            addCriterion("JI_RESUME_NAME not in", values, "jiResumeName");
            return (Criteria) this;
        }

        public Criteria andJiResumeNameBetween(String value1, String value2) {
            addCriterion("JI_RESUME_NAME between", value1, value2, "jiResumeName");
            return (Criteria) this;
        }

        public Criteria andJiResumeNameNotBetween(String value1, String value2) {
            addCriterion("JI_RESUME_NAME not between", value1, value2, "jiResumeName");
            return (Criteria) this;
        }

        public Criteria andJiResumeUrlIsNull() {
            addCriterion("JI_RESUME_URL is null");
            return (Criteria) this;
        }

        public Criteria andJiResumeUrlIsNotNull() {
            addCriterion("JI_RESUME_URL is not null");
            return (Criteria) this;
        }

        public Criteria andJiResumeUrlEqualTo(String value) {
            addCriterion("JI_RESUME_URL =", value, "jiResumeUrl");
            return (Criteria) this;
        }

        public Criteria andJiResumeUrlNotEqualTo(String value) {
            addCriterion("JI_RESUME_URL <>", value, "jiResumeUrl");
            return (Criteria) this;
        }

        public Criteria andJiResumeUrlGreaterThan(String value) {
            addCriterion("JI_RESUME_URL >", value, "jiResumeUrl");
            return (Criteria) this;
        }

        public Criteria andJiResumeUrlGreaterThanOrEqualTo(String value) {
            addCriterion("JI_RESUME_URL >=", value, "jiResumeUrl");
            return (Criteria) this;
        }

        public Criteria andJiResumeUrlLessThan(String value) {
            addCriterion("JI_RESUME_URL <", value, "jiResumeUrl");
            return (Criteria) this;
        }

        public Criteria andJiResumeUrlLessThanOrEqualTo(String value) {
            addCriterion("JI_RESUME_URL <=", value, "jiResumeUrl");
            return (Criteria) this;
        }

        public Criteria andJiResumeUrlLike(String value) {
            addCriterion("JI_RESUME_URL like", value, "jiResumeUrl");
            return (Criteria) this;
        }

        public Criteria andJiResumeUrlNotLike(String value) {
            addCriterion("JI_RESUME_URL not like", value, "jiResumeUrl");
            return (Criteria) this;
        }

        public Criteria andJiResumeUrlIn(List<String> values) {
            addCriterion("JI_RESUME_URL in", values, "jiResumeUrl");
            return (Criteria) this;
        }

        public Criteria andJiResumeUrlNotIn(List<String> values) {
            addCriterion("JI_RESUME_URL not in", values, "jiResumeUrl");
            return (Criteria) this;
        }

        public Criteria andJiResumeUrlBetween(String value1, String value2) {
            addCriterion("JI_RESUME_URL between", value1, value2, "jiResumeUrl");
            return (Criteria) this;
        }

        public Criteria andJiResumeUrlNotBetween(String value1, String value2) {
            addCriterion("JI_RESUME_URL not between", value1, value2, "jiResumeUrl");
            return (Criteria) this;
        }

        public Criteria andJiChangeFlagIsNull() {
            addCriterion("JI_CHANGE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andJiChangeFlagIsNotNull() {
            addCriterion("JI_CHANGE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andJiChangeFlagEqualTo(String value) {
            addCriterion("JI_CHANGE_FLAG =", value, "jiChangeFlag");
            return (Criteria) this;
        }

        public Criteria andJiChangeFlagNotEqualTo(String value) {
            addCriterion("JI_CHANGE_FLAG <>", value, "jiChangeFlag");
            return (Criteria) this;
        }

        public Criteria andJiChangeFlagGreaterThan(String value) {
            addCriterion("JI_CHANGE_FLAG >", value, "jiChangeFlag");
            return (Criteria) this;
        }

        public Criteria andJiChangeFlagGreaterThanOrEqualTo(String value) {
            addCriterion("JI_CHANGE_FLAG >=", value, "jiChangeFlag");
            return (Criteria) this;
        }

        public Criteria andJiChangeFlagLessThan(String value) {
            addCriterion("JI_CHANGE_FLAG <", value, "jiChangeFlag");
            return (Criteria) this;
        }

        public Criteria andJiChangeFlagLessThanOrEqualTo(String value) {
            addCriterion("JI_CHANGE_FLAG <=", value, "jiChangeFlag");
            return (Criteria) this;
        }

        public Criteria andJiChangeFlagLike(String value) {
            addCriterion("JI_CHANGE_FLAG like", value, "jiChangeFlag");
            return (Criteria) this;
        }

        public Criteria andJiChangeFlagNotLike(String value) {
            addCriterion("JI_CHANGE_FLAG not like", value, "jiChangeFlag");
            return (Criteria) this;
        }

        public Criteria andJiChangeFlagIn(List<String> values) {
            addCriterion("JI_CHANGE_FLAG in", values, "jiChangeFlag");
            return (Criteria) this;
        }

        public Criteria andJiChangeFlagNotIn(List<String> values) {
            addCriterion("JI_CHANGE_FLAG not in", values, "jiChangeFlag");
            return (Criteria) this;
        }

        public Criteria andJiChangeFlagBetween(String value1, String value2) {
            addCriterion("JI_CHANGE_FLAG between", value1, value2, "jiChangeFlag");
            return (Criteria) this;
        }

        public Criteria andJiChangeFlagNotBetween(String value1, String value2) {
            addCriterion("JI_CHANGE_FLAG not between", value1, value2, "jiChangeFlag");
            return (Criteria) this;
        }

        public Criteria andJiHopeJobIsNull() {
            addCriterion("JI_HOPE_JOB is null");
            return (Criteria) this;
        }

        public Criteria andJiHopeJobIsNotNull() {
            addCriterion("JI_HOPE_JOB is not null");
            return (Criteria) this;
        }

        public Criteria andJiHopeJobEqualTo(String value) {
            addCriterion("JI_HOPE_JOB =", value, "jiHopeJob");
            return (Criteria) this;
        }

        public Criteria andJiHopeJobNotEqualTo(String value) {
            addCriterion("JI_HOPE_JOB <>", value, "jiHopeJob");
            return (Criteria) this;
        }

        public Criteria andJiHopeJobGreaterThan(String value) {
            addCriterion("JI_HOPE_JOB >", value, "jiHopeJob");
            return (Criteria) this;
        }

        public Criteria andJiHopeJobGreaterThanOrEqualTo(String value) {
            addCriterion("JI_HOPE_JOB >=", value, "jiHopeJob");
            return (Criteria) this;
        }

        public Criteria andJiHopeJobLessThan(String value) {
            addCriterion("JI_HOPE_JOB <", value, "jiHopeJob");
            return (Criteria) this;
        }

        public Criteria andJiHopeJobLessThanOrEqualTo(String value) {
            addCriterion("JI_HOPE_JOB <=", value, "jiHopeJob");
            return (Criteria) this;
        }

        public Criteria andJiHopeJobLike(String value) {
            addCriterion("JI_HOPE_JOB like", value, "jiHopeJob");
            return (Criteria) this;
        }

        public Criteria andJiHopeJobNotLike(String value) {
            addCriterion("JI_HOPE_JOB not like", value, "jiHopeJob");
            return (Criteria) this;
        }

        public Criteria andJiHopeJobIn(List<String> values) {
            addCriterion("JI_HOPE_JOB in", values, "jiHopeJob");
            return (Criteria) this;
        }

        public Criteria andJiHopeJobNotIn(List<String> values) {
            addCriterion("JI_HOPE_JOB not in", values, "jiHopeJob");
            return (Criteria) this;
        }

        public Criteria andJiHopeJobBetween(String value1, String value2) {
            addCriterion("JI_HOPE_JOB between", value1, value2, "jiHopeJob");
            return (Criteria) this;
        }

        public Criteria andJiHopeJobNotBetween(String value1, String value2) {
            addCriterion("JI_HOPE_JOB not between", value1, value2, "jiHopeJob");
            return (Criteria) this;
        }

        public Criteria andJiRegtimeIsNull() {
            addCriterion("JI_REGTIME is null");
            return (Criteria) this;
        }

        public Criteria andJiRegtimeIsNotNull() {
            addCriterion("JI_REGTIME is not null");
            return (Criteria) this;
        }

        public Criteria andJiRegtimeEqualTo(Date value) {
            addCriterion("JI_REGTIME =", value, "jiRegtime");
            return (Criteria) this;
        }

        public Criteria andJiRegtimeNotEqualTo(Date value) {
            addCriterion("JI_REGTIME <>", value, "jiRegtime");
            return (Criteria) this;
        }

        public Criteria andJiRegtimeGreaterThan(Date value) {
            addCriterion("JI_REGTIME >", value, "jiRegtime");
            return (Criteria) this;
        }

        public Criteria andJiRegtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("JI_REGTIME >=", value, "jiRegtime");
            return (Criteria) this;
        }

        public Criteria andJiRegtimeLessThan(Date value) {
            addCriterion("JI_REGTIME <", value, "jiRegtime");
            return (Criteria) this;
        }

        public Criteria andJiRegtimeLessThanOrEqualTo(Date value) {
            addCriterion("JI_REGTIME <=", value, "jiRegtime");
            return (Criteria) this;
        }

        public Criteria andJiRegtimeIn(List<Date> values) {
            addCriterion("JI_REGTIME in", values, "jiRegtime");
            return (Criteria) this;
        }

        public Criteria andJiRegtimeNotIn(List<Date> values) {
            addCriterion("JI_REGTIME not in", values, "jiRegtime");
            return (Criteria) this;
        }

        public Criteria andJiRegtimeBetween(Date value1, Date value2) {
            addCriterion("JI_REGTIME between", value1, value2, "jiRegtime");
            return (Criteria) this;
        }

        public Criteria andJiRegtimeNotBetween(Date value1, Date value2) {
            addCriterion("JI_REGTIME not between", value1, value2, "jiRegtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_job_intent
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 25 19:01:39 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_job_intent
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}