package com.chinasofti.cetp.study.model;

import java.util.Date;
import java.util.List;

public class TreeChapter extends Chapter {
	private String idFied;
	public String getIdFied() {
    	return idFied;
    }

	public void setIdFied(String idFied) {
    	this.idFied = idFied;
    }

	private Integer hsId;
	
	private Integer exerId;
	private String exerName;
	
	public Integer getHsId() {
		return hsId;
	}

	public void setHsId(Integer hsId) {
		this.hsId = hsId;
	}

	public Integer getExerId() {
		return exerId;
	}

	public void setExerId(Integer exerId) {
		this.exerId = exerId;
	}

	public String getExerName() {
		return exerName;
	}

	public void setExerName(String exerName) {
		this.exerName = exerName;
	}



	private Integer scVideo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tp_sub_courseware.SC_ID
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	private Integer scId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tp_sub_courseware.COURSE_ID
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	private Integer courseId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tp_sub_courseware.SC_NAME
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	private String scName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tp_sub_courseware.SC_PLAY_TIME
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	private Integer scPlayTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tp_sub_courseware.SC_URL
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	private String scUrl;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tp_sub_courseware.SC_DOC_URL
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	private String scDocUrl;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tp_sub_courseware.SC_REGTIME
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	private Date scRegtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_sub_courseware.SC_ID
	 * 
	 * @return the value of tp_sub_courseware.SC_ID
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public Integer getScId() {
		return scId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_sub_courseware.SC_ID
	 * 
	 * @param scId
	 *            the value for tp_sub_courseware.SC_ID
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setScId(Integer scId) {
		this.scId = scId;
	}

	public Integer getScVideo() {
    	return scVideo;
    }

	public void setScVideo(Integer scVideo) {
    	this.scVideo = scVideo;
    }

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_sub_courseware.COURSE_ID
	 * 
	 * @return the value of tp_sub_courseware.COURSE_ID
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public Integer getCourseId() {
		return courseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_sub_courseware.COURSE_ID
	 * 
	 * @param courseId
	 *            the value for tp_sub_courseware.COURSE_ID
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_sub_courseware.SC_NAME
	 * 
	 * @return the value of tp_sub_courseware.SC_NAME
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public String getScName() {
		return scName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_sub_courseware.SC_NAME
	 * 
	 * @param scName
	 *            the value for tp_sub_courseware.SC_NAME
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setScName(String scName) {
		this.scName = scName == null ? null : scName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_sub_courseware.SC_PLAY_TIME
	 * 
	 * @return the value of tp_sub_courseware.SC_PLAY_TIME
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public Integer getScPlayTime() {
		return scPlayTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_sub_courseware.SC_PLAY_TIME
	 * 
	 * @param scPlayTime
	 *            the value for tp_sub_courseware.SC_PLAY_TIME
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setScPlayTime(Integer scPlayTime) {
		this.scPlayTime = scPlayTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_sub_courseware.SC_URL
	 * 
	 * @return the value of tp_sub_courseware.SC_URL
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public String getScUrl() {
		return scUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_sub_courseware.SC_URL
	 * 
	 * @param scUrl
	 *            the value for tp_sub_courseware.SC_URL
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setScUrl(String scUrl) {
		this.scUrl = scUrl == null ? null : scUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_sub_courseware.SC_DOC_URL
	 * 
	 * @return the value of tp_sub_courseware.SC_DOC_URL
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public String getScDocUrl() {
		return scDocUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_sub_courseware.SC_DOC_URL
	 * 
	 * @param scDocUrl
	 *            the value for tp_sub_courseware.SC_DOC_URL
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setScDocUrl(String scDocUrl) {
		this.scDocUrl = scDocUrl == null ? null : scDocUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_sub_courseware.SC_REGTIME
	 * 
	 * @return the value of tp_sub_courseware.SC_REGTIME
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public Date getScRegtime() {
		return scRegtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_sub_courseware.SC_REGTIME
	 * 
	 * @param scRegtime
	 *            the value for tp_sub_courseware.SC_REGTIME
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	public void setScRegtime(Date scRegtime) {
		this.scRegtime = scRegtime;
	}

	private List<TreeChapter> children;
	private String state;

	public List<TreeChapter> getChildren() {
		return children;
	}

	public void setChildren(List<TreeChapter> children) {
		this.children = children;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
