package com.chinasofti.cetp.practice.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PersonAchivementExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_person_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_person_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_person_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_person_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public PersonAchivementExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_person_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_person_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_person_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_person_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_person_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_person_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_person_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_person_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_person_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_person_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_person_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPaResultIdIsNull() {
            addCriterion("PA_RESULT_ID is null");
            return (Criteria) this;
        }

        public Criteria andPaResultIdIsNotNull() {
            addCriterion("PA_RESULT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPaResultIdEqualTo(Integer value) {
            addCriterion("PA_RESULT_ID =", value, "paResultId");
            return (Criteria) this;
        }

        public Criteria andPaResultIdNotEqualTo(Integer value) {
            addCriterion("PA_RESULT_ID <>", value, "paResultId");
            return (Criteria) this;
        }

        public Criteria andPaResultIdGreaterThan(Integer value) {
            addCriterion("PA_RESULT_ID >", value, "paResultId");
            return (Criteria) this;
        }

        public Criteria andPaResultIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("PA_RESULT_ID >=", value, "paResultId");
            return (Criteria) this;
        }

        public Criteria andPaResultIdLessThan(Integer value) {
            addCriterion("PA_RESULT_ID <", value, "paResultId");
            return (Criteria) this;
        }

        public Criteria andPaResultIdLessThanOrEqualTo(Integer value) {
            addCriterion("PA_RESULT_ID <=", value, "paResultId");
            return (Criteria) this;
        }

        public Criteria andPaResultIdIn(List<Integer> values) {
            addCriterion("PA_RESULT_ID in", values, "paResultId");
            return (Criteria) this;
        }

        public Criteria andPaResultIdNotIn(List<Integer> values) {
            addCriterion("PA_RESULT_ID not in", values, "paResultId");
            return (Criteria) this;
        }

        public Criteria andPaResultIdBetween(Integer value1, Integer value2) {
            addCriterion("PA_RESULT_ID between", value1, value2, "paResultId");
            return (Criteria) this;
        }

        public Criteria andPaResultIdNotBetween(Integer value1, Integer value2) {
            addCriterion("PA_RESULT_ID not between", value1, value2, "paResultId");
            return (Criteria) this;
        }

        public Criteria andPaStuIdIsNull() {
            addCriterion("PA_STU_ID is null");
            return (Criteria) this;
        }

        public Criteria andPaStuIdIsNotNull() {
            addCriterion("PA_STU_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPaStuIdEqualTo(Integer value) {
            addCriterion("PA_STU_ID =", value, "paStuId");
            return (Criteria) this;
        }

        public Criteria andPaStuIdNotEqualTo(Integer value) {
            addCriterion("PA_STU_ID <>", value, "paStuId");
            return (Criteria) this;
        }

        public Criteria andPaStuIdGreaterThan(Integer value) {
            addCriterion("PA_STU_ID >", value, "paStuId");
            return (Criteria) this;
        }

        public Criteria andPaStuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("PA_STU_ID >=", value, "paStuId");
            return (Criteria) this;
        }

        public Criteria andPaStuIdLessThan(Integer value) {
            addCriterion("PA_STU_ID <", value, "paStuId");
            return (Criteria) this;
        }

        public Criteria andPaStuIdLessThanOrEqualTo(Integer value) {
            addCriterion("PA_STU_ID <=", value, "paStuId");
            return (Criteria) this;
        }

        public Criteria andPaStuIdIn(List<Integer> values) {
            addCriterion("PA_STU_ID in", values, "paStuId");
            return (Criteria) this;
        }

        public Criteria andPaStuIdNotIn(List<Integer> values) {
            addCriterion("PA_STU_ID not in", values, "paStuId");
            return (Criteria) this;
        }

        public Criteria andPaStuIdBetween(Integer value1, Integer value2) {
            addCriterion("PA_STU_ID between", value1, value2, "paStuId");
            return (Criteria) this;
        }

        public Criteria andPaStuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("PA_STU_ID not between", value1, value2, "paStuId");
            return (Criteria) this;
        }

        public Criteria andPaPracIdIsNull() {
            addCriterion("PA_PRAC_ID is null");
            return (Criteria) this;
        }

        public Criteria andPaPracIdIsNotNull() {
            addCriterion("PA_PRAC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPaPracIdEqualTo(Integer value) {
            addCriterion("PA_PRAC_ID =", value, "paPracId");
            return (Criteria) this;
        }

        public Criteria andPaPracIdNotEqualTo(Integer value) {
            addCriterion("PA_PRAC_ID <>", value, "paPracId");
            return (Criteria) this;
        }

        public Criteria andPaPracIdGreaterThan(Integer value) {
            addCriterion("PA_PRAC_ID >", value, "paPracId");
            return (Criteria) this;
        }

        public Criteria andPaPracIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("PA_PRAC_ID >=", value, "paPracId");
            return (Criteria) this;
        }

        public Criteria andPaPracIdLessThan(Integer value) {
            addCriterion("PA_PRAC_ID <", value, "paPracId");
            return (Criteria) this;
        }

        public Criteria andPaPracIdLessThanOrEqualTo(Integer value) {
            addCriterion("PA_PRAC_ID <=", value, "paPracId");
            return (Criteria) this;
        }

        public Criteria andPaPracIdIn(List<Integer> values) {
            addCriterion("PA_PRAC_ID in", values, "paPracId");
            return (Criteria) this;
        }

        public Criteria andPaPracIdNotIn(List<Integer> values) {
            addCriterion("PA_PRAC_ID not in", values, "paPracId");
            return (Criteria) this;
        }

        public Criteria andPaPracIdBetween(Integer value1, Integer value2) {
            addCriterion("PA_PRAC_ID between", value1, value2, "paPracId");
            return (Criteria) this;
        }

        public Criteria andPaPracIdNotBetween(Integer value1, Integer value2) {
            addCriterion("PA_PRAC_ID not between", value1, value2, "paPracId");
            return (Criteria) this;
        }

        public Criteria andPaProIdIsNull() {
            addCriterion("PA_PRO_ID is null");
            return (Criteria) this;
        }

        public Criteria andPaProIdIsNotNull() {
            addCriterion("PA_PRO_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPaProIdEqualTo(Integer value) {
            addCriterion("PA_PRO_ID =", value, "paProId");
            return (Criteria) this;
        }

        public Criteria andPaProIdNotEqualTo(Integer value) {
            addCriterion("PA_PRO_ID <>", value, "paProId");
            return (Criteria) this;
        }

        public Criteria andPaProIdGreaterThan(Integer value) {
            addCriterion("PA_PRO_ID >", value, "paProId");
            return (Criteria) this;
        }

        public Criteria andPaProIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("PA_PRO_ID >=", value, "paProId");
            return (Criteria) this;
        }

        public Criteria andPaProIdLessThan(Integer value) {
            addCriterion("PA_PRO_ID <", value, "paProId");
            return (Criteria) this;
        }

        public Criteria andPaProIdLessThanOrEqualTo(Integer value) {
            addCriterion("PA_PRO_ID <=", value, "paProId");
            return (Criteria) this;
        }

        public Criteria andPaProIdIn(List<Integer> values) {
            addCriterion("PA_PRO_ID in", values, "paProId");
            return (Criteria) this;
        }

        public Criteria andPaProIdNotIn(List<Integer> values) {
            addCriterion("PA_PRO_ID not in", values, "paProId");
            return (Criteria) this;
        }

        public Criteria andPaProIdBetween(Integer value1, Integer value2) {
            addCriterion("PA_PRO_ID between", value1, value2, "paProId");
            return (Criteria) this;
        }

        public Criteria andPaProIdNotBetween(Integer value1, Integer value2) {
            addCriterion("PA_PRO_ID not between", value1, value2, "paProId");
            return (Criteria) this;
        }

        public Criteria andPaResultNameIsNull() {
            addCriterion("PA_RESULT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andPaResultNameIsNotNull() {
            addCriterion("PA_RESULT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andPaResultNameEqualTo(String value) {
            addCriterion("PA_RESULT_NAME =", value, "paResultName");
            return (Criteria) this;
        }

        public Criteria andPaResultNameNotEqualTo(String value) {
            addCriterion("PA_RESULT_NAME <>", value, "paResultName");
            return (Criteria) this;
        }

        public Criteria andPaResultNameGreaterThan(String value) {
            addCriterion("PA_RESULT_NAME >", value, "paResultName");
            return (Criteria) this;
        }

        public Criteria andPaResultNameGreaterThanOrEqualTo(String value) {
            addCriterion("PA_RESULT_NAME >=", value, "paResultName");
            return (Criteria) this;
        }

        public Criteria andPaResultNameLessThan(String value) {
            addCriterion("PA_RESULT_NAME <", value, "paResultName");
            return (Criteria) this;
        }

        public Criteria andPaResultNameLessThanOrEqualTo(String value) {
            addCriterion("PA_RESULT_NAME <=", value, "paResultName");
            return (Criteria) this;
        }

        public Criteria andPaResultNameLike(String value) {
            addCriterion("PA_RESULT_NAME like", value, "paResultName");
            return (Criteria) this;
        }

        public Criteria andPaResultNameNotLike(String value) {
            addCriterion("PA_RESULT_NAME not like", value, "paResultName");
            return (Criteria) this;
        }

        public Criteria andPaResultNameIn(List<String> values) {
            addCriterion("PA_RESULT_NAME in", values, "paResultName");
            return (Criteria) this;
        }

        public Criteria andPaResultNameNotIn(List<String> values) {
            addCriterion("PA_RESULT_NAME not in", values, "paResultName");
            return (Criteria) this;
        }

        public Criteria andPaResultNameBetween(String value1, String value2) {
            addCriterion("PA_RESULT_NAME between", value1, value2, "paResultName");
            return (Criteria) this;
        }

        public Criteria andPaResultNameNotBetween(String value1, String value2) {
            addCriterion("PA_RESULT_NAME not between", value1, value2, "paResultName");
            return (Criteria) this;
        }

        public Criteria andPaResultUrlIsNull() {
            addCriterion("PA_RESULT_URL is null");
            return (Criteria) this;
        }

        public Criteria andPaResultUrlIsNotNull() {
            addCriterion("PA_RESULT_URL is not null");
            return (Criteria) this;
        }

        public Criteria andPaResultUrlEqualTo(String value) {
            addCriterion("PA_RESULT_URL =", value, "paResultUrl");
            return (Criteria) this;
        }

        public Criteria andPaResultUrlNotEqualTo(String value) {
            addCriterion("PA_RESULT_URL <>", value, "paResultUrl");
            return (Criteria) this;
        }

        public Criteria andPaResultUrlGreaterThan(String value) {
            addCriterion("PA_RESULT_URL >", value, "paResultUrl");
            return (Criteria) this;
        }

        public Criteria andPaResultUrlGreaterThanOrEqualTo(String value) {
            addCriterion("PA_RESULT_URL >=", value, "paResultUrl");
            return (Criteria) this;
        }

        public Criteria andPaResultUrlLessThan(String value) {
            addCriterion("PA_RESULT_URL <", value, "paResultUrl");
            return (Criteria) this;
        }

        public Criteria andPaResultUrlLessThanOrEqualTo(String value) {
            addCriterion("PA_RESULT_URL <=", value, "paResultUrl");
            return (Criteria) this;
        }

        public Criteria andPaResultUrlLike(String value) {
            addCriterion("PA_RESULT_URL like", value, "paResultUrl");
            return (Criteria) this;
        }

        public Criteria andPaResultUrlNotLike(String value) {
            addCriterion("PA_RESULT_URL not like", value, "paResultUrl");
            return (Criteria) this;
        }

        public Criteria andPaResultUrlIn(List<String> values) {
            addCriterion("PA_RESULT_URL in", values, "paResultUrl");
            return (Criteria) this;
        }

        public Criteria andPaResultUrlNotIn(List<String> values) {
            addCriterion("PA_RESULT_URL not in", values, "paResultUrl");
            return (Criteria) this;
        }

        public Criteria andPaResultUrlBetween(String value1, String value2) {
            addCriterion("PA_RESULT_URL between", value1, value2, "paResultUrl");
            return (Criteria) this;
        }

        public Criteria andPaResultUrlNotBetween(String value1, String value2) {
            addCriterion("PA_RESULT_URL not between", value1, value2, "paResultUrl");
            return (Criteria) this;
        }

        public Criteria andPaResultVideoUrlIsNull() {
            addCriterion("PA_RESULT_VIDEO_URL is null");
            return (Criteria) this;
        }

        public Criteria andPaResultVideoUrlIsNotNull() {
            addCriterion("PA_RESULT_VIDEO_URL is not null");
            return (Criteria) this;
        }

        public Criteria andPaResultVideoUrlEqualTo(String value) {
            addCriterion("PA_RESULT_VIDEO_URL =", value, "paResultVideoUrl");
            return (Criteria) this;
        }

        public Criteria andPaResultVideoUrlNotEqualTo(String value) {
            addCriterion("PA_RESULT_VIDEO_URL <>", value, "paResultVideoUrl");
            return (Criteria) this;
        }

        public Criteria andPaResultVideoUrlGreaterThan(String value) {
            addCriterion("PA_RESULT_VIDEO_URL >", value, "paResultVideoUrl");
            return (Criteria) this;
        }

        public Criteria andPaResultVideoUrlGreaterThanOrEqualTo(String value) {
            addCriterion("PA_RESULT_VIDEO_URL >=", value, "paResultVideoUrl");
            return (Criteria) this;
        }

        public Criteria andPaResultVideoUrlLessThan(String value) {
            addCriterion("PA_RESULT_VIDEO_URL <", value, "paResultVideoUrl");
            return (Criteria) this;
        }

        public Criteria andPaResultVideoUrlLessThanOrEqualTo(String value) {
            addCriterion("PA_RESULT_VIDEO_URL <=", value, "paResultVideoUrl");
            return (Criteria) this;
        }

        public Criteria andPaResultVideoUrlLike(String value) {
            addCriterion("PA_RESULT_VIDEO_URL like", value, "paResultVideoUrl");
            return (Criteria) this;
        }

        public Criteria andPaResultVideoUrlNotLike(String value) {
            addCriterion("PA_RESULT_VIDEO_URL not like", value, "paResultVideoUrl");
            return (Criteria) this;
        }

        public Criteria andPaResultVideoUrlIn(List<String> values) {
            addCriterion("PA_RESULT_VIDEO_URL in", values, "paResultVideoUrl");
            return (Criteria) this;
        }

        public Criteria andPaResultVideoUrlNotIn(List<String> values) {
            addCriterion("PA_RESULT_VIDEO_URL not in", values, "paResultVideoUrl");
            return (Criteria) this;
        }

        public Criteria andPaResultVideoUrlBetween(String value1, String value2) {
            addCriterion("PA_RESULT_VIDEO_URL between", value1, value2, "paResultVideoUrl");
            return (Criteria) this;
        }

        public Criteria andPaResultVideoUrlNotBetween(String value1, String value2) {
            addCriterion("PA_RESULT_VIDEO_URL not between", value1, value2, "paResultVideoUrl");
            return (Criteria) this;
        }

        public Criteria andPaResultTypeIsNull() {
            addCriterion("PA_RESULT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andPaResultTypeIsNotNull() {
            addCriterion("PA_RESULT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andPaResultTypeEqualTo(String value) {
            addCriterion("PA_RESULT_TYPE =", value, "paResultType");
            return (Criteria) this;
        }

        public Criteria andPaResultTypeNotEqualTo(String value) {
            addCriterion("PA_RESULT_TYPE <>", value, "paResultType");
            return (Criteria) this;
        }

        public Criteria andPaResultTypeGreaterThan(String value) {
            addCriterion("PA_RESULT_TYPE >", value, "paResultType");
            return (Criteria) this;
        }

        public Criteria andPaResultTypeGreaterThanOrEqualTo(String value) {
            addCriterion("PA_RESULT_TYPE >=", value, "paResultType");
            return (Criteria) this;
        }

        public Criteria andPaResultTypeLessThan(String value) {
            addCriterion("PA_RESULT_TYPE <", value, "paResultType");
            return (Criteria) this;
        }

        public Criteria andPaResultTypeLessThanOrEqualTo(String value) {
            addCriterion("PA_RESULT_TYPE <=", value, "paResultType");
            return (Criteria) this;
        }

        public Criteria andPaResultTypeLike(String value) {
            addCriterion("PA_RESULT_TYPE like", value, "paResultType");
            return (Criteria) this;
        }

        public Criteria andPaResultTypeNotLike(String value) {
            addCriterion("PA_RESULT_TYPE not like", value, "paResultType");
            return (Criteria) this;
        }

        public Criteria andPaResultTypeIn(List<String> values) {
            addCriterion("PA_RESULT_TYPE in", values, "paResultType");
            return (Criteria) this;
        }

        public Criteria andPaResultTypeNotIn(List<String> values) {
            addCriterion("PA_RESULT_TYPE not in", values, "paResultType");
            return (Criteria) this;
        }

        public Criteria andPaResultTypeBetween(String value1, String value2) {
            addCriterion("PA_RESULT_TYPE between", value1, value2, "paResultType");
            return (Criteria) this;
        }

        public Criteria andPaResultTypeNotBetween(String value1, String value2) {
            addCriterion("PA_RESULT_TYPE not between", value1, value2, "paResultType");
            return (Criteria) this;
        }

        public Criteria andAchResultRegtimeIsNull() {
            addCriterion("ACH_RESULT_REGTIME is null");
            return (Criteria) this;
        }

        public Criteria andAchResultRegtimeIsNotNull() {
            addCriterion("ACH_RESULT_REGTIME is not null");
            return (Criteria) this;
        }

        public Criteria andAchResultRegtimeEqualTo(Date value) {
            addCriterion("ACH_RESULT_REGTIME =", value, "achResultRegtime");
            return (Criteria) this;
        }

        public Criteria andAchResultRegtimeNotEqualTo(Date value) {
            addCriterion("ACH_RESULT_REGTIME <>", value, "achResultRegtime");
            return (Criteria) this;
        }

        public Criteria andAchResultRegtimeGreaterThan(Date value) {
            addCriterion("ACH_RESULT_REGTIME >", value, "achResultRegtime");
            return (Criteria) this;
        }

        public Criteria andAchResultRegtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ACH_RESULT_REGTIME >=", value, "achResultRegtime");
            return (Criteria) this;
        }

        public Criteria andAchResultRegtimeLessThan(Date value) {
            addCriterion("ACH_RESULT_REGTIME <", value, "achResultRegtime");
            return (Criteria) this;
        }

        public Criteria andAchResultRegtimeLessThanOrEqualTo(Date value) {
            addCriterion("ACH_RESULT_REGTIME <=", value, "achResultRegtime");
            return (Criteria) this;
        }

        public Criteria andAchResultRegtimeIn(List<Date> values) {
            addCriterion("ACH_RESULT_REGTIME in", values, "achResultRegtime");
            return (Criteria) this;
        }

        public Criteria andAchResultRegtimeNotIn(List<Date> values) {
            addCriterion("ACH_RESULT_REGTIME not in", values, "achResultRegtime");
            return (Criteria) this;
        }

        public Criteria andAchResultRegtimeBetween(Date value1, Date value2) {
            addCriterion("ACH_RESULT_REGTIME between", value1, value2, "achResultRegtime");
            return (Criteria) this;
        }

        public Criteria andAchResultRegtimeNotBetween(Date value1, Date value2) {
            addCriterion("ACH_RESULT_REGTIME not between", value1, value2, "achResultRegtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_person_achivement
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 25 19:47:24 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_person_achivement
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}