package com.chinasofti.cetp.practice.model;

public class TaskKnowKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_task_know.TK_KNOW_ID
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    private Integer tkKnowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_task_know.TK_TASK_ID
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    private Integer tkTaskId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_task_know.TK_KNOW_ID
     *
     * @return the value of tp_task_know.TK_KNOW_ID
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public Integer getTkKnowId() {
        return tkKnowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_task_know.TK_KNOW_ID
     *
     * @param tkKnowId the value for tp_task_know.TK_KNOW_ID
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public void setTkKnowId(Integer tkKnowId) {
        this.tkKnowId = tkKnowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_task_know.TK_TASK_ID
     *
     * @return the value of tp_task_know.TK_TASK_ID
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public Integer getTkTaskId() {
        return tkTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_task_know.TK_TASK_ID
     *
     * @param tkTaskId the value for tp_task_know.TK_TASK_ID
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public void setTkTaskId(Integer tkTaskId) {
        this.tkTaskId = tkTaskId;
    }
}