package com.chinasofti.cetp.practice.model;

public class PracPersonWithBLOBs extends PracPerson {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_prac_person.PP_SUMMARY
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    private String ppSummary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_prac_person.PP_EVALUATE
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    private String ppEvaluate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_prac_person.PP_SUMMARY
     *
     * @return the value of tp_prac_person.PP_SUMMARY
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public String getPpSummary() {
        return ppSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_prac_person.PP_SUMMARY
     *
     * @param ppSummary the value for tp_prac_person.PP_SUMMARY
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public void setPpSummary(String ppSummary) {
        this.ppSummary = ppSummary == null ? null : ppSummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_prac_person.PP_EVALUATE
     *
     * @return the value of tp_prac_person.PP_EVALUATE
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public String getPpEvaluate() {
        return ppEvaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_prac_person.PP_EVALUATE
     *
     * @param ppEvaluate the value for tp_prac_person.PP_EVALUATE
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public void setPpEvaluate(String ppEvaluate) {
        this.ppEvaluate = ppEvaluate == null ? null : ppEvaluate.trim();
    }
}