package com.chinasofti.cetp.practice.dao;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.chinasofti.cetp.practice.model.MorePersonAchivement;
import com.chinasofti.cetp.practice.model.PersonAchivement;
import com.chinasofti.cetp.practice.model.PersonAchivementExample;

public interface PersonAchivementMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_person_achivement
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int countByExample(PersonAchivementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_person_achivement
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByExample(PersonAchivementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_person_achivement
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByPrimaryKey(Integer paResultId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_person_achivement
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insert(PersonAchivement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_person_achivement
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insertSelective(PersonAchivement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_person_achivement
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	List<PersonAchivement> selectByExample(PersonAchivementExample example);
	List<PersonAchivement> selectByExample(PersonAchivementExample example,RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_person_achivement
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	PersonAchivement selectByPrimaryKey(Integer paResultId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_person_achivement
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExampleSelective(@Param("record") PersonAchivement record,
			@Param("example") PersonAchivementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_person_achivement
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExample(@Param("record") PersonAchivement record,
			@Param("example") PersonAchivementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_person_achivement
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKeySelective(PersonAchivement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_person_achivement
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKey(PersonAchivement record);

	List<MorePersonAchivement> selectPersonAchivementByStuNo(
			HashMap<String, Object> map,RowBounds rb);
}