package com.chinasofti.cetp.practice.dao;

import com.chinasofti.cetp.practice.model.MoreMorePracPerson;
import com.chinasofti.cetp.practice.model.MoreMorePracticeTeam;
import com.chinasofti.cetp.practice.model.MorePracPerson;
import com.chinasofti.cetp.practice.model.MorePractice;
import com.chinasofti.cetp.practice.model.PracPerson;
import com.chinasofti.cetp.practice.model.PracPersonExample;
import com.chinasofti.cetp.practice.model.PracPersonKey;
import com.chinasofti.cetp.practice.model.PracPersonWithBLOBs;
import com.chinasofti.cetp.practice.model.PracticeTeam;

import java.util.HashMap;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PracPersonMapper {
	// add by yf
	List<MorePracPerson> selectStus(@Param("pracId") Integer pracId,
			@Param("proName") String proName, @Param("stuNo") String stuNo,
			@Param("stuName") String stuName, RowBounds rowBounds);

	List<MorePracPerson> selectStusWithoutProg(@Param("pracId") Integer pracId,
			@Param("proName") String proName, @Param("stuNo") String stuNo,
			@Param("stuName") String stuName, RowBounds rowBounds);

	List<MoreMorePracPerson> selectMoreMorePracPerson(
			@Param("stuNo") Integer stuNo, @Param("proName") String proName,
			@Param("pracName") String pracName, RowBounds rowBounds);

	// end
	public List<MorePracPerson> getSummarygriddata(HashMap map,RowBounds rowBounds);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_prac_person
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int countByExample(PracPersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_prac_person
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByExample(PracPersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_prac_person
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByPrimaryKey(PracPersonKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_prac_person
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insert(PracPersonWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_prac_person
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insertSelective(PracPersonWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_prac_person
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	List<PracPersonWithBLOBs> selectByExampleWithBLOBs(PracPersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_prac_person
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	List<PracPerson> selectByExample(PracPersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_prac_person
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	PracPersonWithBLOBs selectByPrimaryKey(PracPersonKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_prac_person
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExampleSelective(@Param("record") PracPersonWithBLOBs record,
			@Param("example") PracPersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_prac_person
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExampleWithBLOBs(@Param("record") PracPersonWithBLOBs record,
			@Param("example") PracPersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_prac_person
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExample(@Param("record") PracPerson record,
			@Param("example") PracPersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_prac_person
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKeySelective(PracPersonWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_prac_person
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKeyWithBLOBs(PracPersonWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_prac_person
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKey(PracPerson record);

	/* start add by wang-hw 2013-08-11 */
	int insPersonPractice(HashMap map);

	/* end */
	
	List<MorePracPerson> getStuForPrac(Integer pracId);
	
	Integer getStuPracId(Integer stuNo);

}