package com.chinasofti.cetp.practice.dao;

import com.chinasofti.cetp.practice.model.MorePracQuestion;
import com.chinasofti.cetp.practice.model.PracQuestion;
import com.chinasofti.cetp.practice.model.PracQuestionExample;

import java.util.HashMap;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PracQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_prac_question
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int countByExample(PracQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_prac_question
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int deleteByExample(PracQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_prac_question
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int deleteByPrimaryKey(Integer pqQuestionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_prac_question
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int insert(PracQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_prac_question
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int insertSelective(PracQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_prac_question
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    List<PracQuestion> selectByExampleWithBLOBs(PracQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_prac_question
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    List<PracQuestion> selectByExample(PracQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_prac_question
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    PracQuestion selectByPrimaryKey(Integer pqQuestionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_prac_question
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int updateByExampleSelective(@Param("record") PracQuestion record, @Param("example") PracQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_prac_question
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int updateByExampleWithBLOBs(@Param("record") PracQuestion record, @Param("example") PracQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_prac_question
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int updateByExample(@Param("record") PracQuestion record, @Param("example") PracQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_prac_question
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int updateByPrimaryKeySelective(PracQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_prac_question
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int updateByPrimaryKeyWithBLOBs(PracQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_prac_question
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int updateByPrimaryKey(PracQuestion record);
    
    List<MorePracQuestion> getPracticeQuestionList(HashMap<String, Object>map,RowBounds rb);
    
    //add by YF 2013-11-28
    Integer getQueTeacher(Integer pqQuestionId);
    //end
}