package com.chinasofti.cetp.practice.dao;

import com.chinasofti.cetp.practice.model.ProDemoImg;
import com.chinasofti.cetp.practice.model.ProDemoImgExample;

import java.util.HashMap;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProDemoImgMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_demo_img
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int countByExample(ProDemoImgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_demo_img
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByExample(ProDemoImgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_demo_img
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByPrimaryKey(Integer demoImgId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_demo_img
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insert(ProDemoImg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_demo_img
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insertSelective(ProDemoImg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_demo_img
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	List<ProDemoImg> selectByExample(ProDemoImgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_demo_img
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	ProDemoImg selectByPrimaryKey(Integer demoImgId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_demo_img
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExampleSelective(@Param("record") ProDemoImg record, @Param("example") ProDemoImgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_demo_img
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExample(@Param("record") ProDemoImg record, @Param("example") ProDemoImgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_demo_img
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKeySelective(ProDemoImg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_demo_img
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKey(ProDemoImg record);

	List<ProDemoImg> selectDemoImgName(HashMap<String, Integer> map);

	int deleteByDemoProId(HashMap<String, Integer> map);

	int copyItems(@Param("from") Integer from, @Param("to") Integer to);

}