package com.chinasofti.cetp.practice.dao;

import com.chinasofti.cetp.practice.model.ProResult;
import com.chinasofti.cetp.practice.model.ProResultExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ProResultMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_result
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int countByExample(ProResultExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_result
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByExample(ProResultExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_result
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByPrimaryKey(Integer prResultId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_result
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insert(ProResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_result
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insertSelective(ProResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_result
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	List<ProResult> selectByExample(ProResultExample example);

	List<ProResult> selectByExample(ProResultExample example,
			RowBounds rowbounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_result
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	ProResult selectByPrimaryKey(Integer prResultId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_result
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExampleSelective(@Param("record") ProResult record,
			@Param("example") ProResultExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_result
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExample(@Param("record") ProResult record,
			@Param("example") ProResultExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_result
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKeySelective(ProResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_result
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKey(ProResult record);
}