package com.chinasofti.cetp.practice.dao;

import com.chinasofti.cetp.practice.model.ProTools;
import com.chinasofti.cetp.practice.model.ProToolsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ProToolsMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_tools
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int countByExample(ProToolsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_tools
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByExample(ProToolsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_tools
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByPrimaryKey(Integer ptToolsId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_tools
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insert(ProTools record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_tools
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insertSelective(ProTools record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_tools
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	List<ProTools> selectByExample(ProToolsExample example);

	List<ProTools> selectByExample(ProToolsExample example, RowBounds rowbounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_tools
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	ProTools selectByPrimaryKey(Integer ptToolsId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_tools
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExampleSelective(@Param("record") ProTools record,
			@Param("example") ProToolsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_tools
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExample(@Param("record") ProTools record,
			@Param("example") ProToolsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_tools
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKeySelective(ProTools record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_pro_tools
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKey(ProTools record);
	
	int copyItems(@Param("from") Integer from, @Param("to") Integer to);
}