package com.chinasofti.cetp.practice.dao;

import com.chinasofti.cetp.practice.model.MoreStuLog;
import com.chinasofti.cetp.practice.model.StuLog;
import com.chinasofti.cetp.practice.model.StuLogExample;
import com.chinasofti.cetp.practice.model.StuWithLastUpdDate;

import java.util.HashMap;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface StuLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_stu_log
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int countByExample(StuLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_stu_log
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int deleteByExample(StuLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_stu_log
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int deleteByPrimaryKey(Integer slLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_stu_log
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int insert(StuLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_stu_log
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int insertSelective(StuLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_stu_log
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    List<StuLog> selectByExample(StuLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_stu_log
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    StuLog selectByPrimaryKey(Integer slLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_stu_log
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int updateByExampleSelective(@Param("record") StuLog record, @Param("example") StuLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_stu_log
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int updateByExample(@Param("record") StuLog record, @Param("example") StuLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_stu_log
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int updateByPrimaryKeySelective(StuLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_stu_log
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int updateByPrimaryKey(StuLog record);
    public List<MoreStuLog> selectLog(RowBounds rowBounds);
    public List<MoreStuLog> selectLog1(Integer stuNo,RowBounds rowBounds);
    
    public List<MoreStuLog> selectQueryLog(HashMap map,RowBounds rowBounds);
    
    List<StuWithLastUpdDate> getStuListWithLastUpdDate(Integer pracId);
}