package com.chinasofti.cetp.practice.dao;

import com.chinasofti.cetp.practice.model.MoreStuWeekly;
import com.chinasofti.cetp.practice.model.StuWeekly;
import com.chinasofti.cetp.practice.model.StuWeeklyExample;

import java.util.HashMap;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface StuWeeklyMapper {
	
	
	//add by YF
	List<StuWeekly> selectByExample(StuWeeklyExample example,RowBounds rowBounds);
	//end
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_stu_weekly
	 * 
	 * @mbggenerated Mon Jul 29 15:08:33 CST 2013
	 */
	int countByExample(StuWeeklyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_stu_weekly
	 * 
	 * @mbggenerated Mon Jul 29 15:08:33 CST 2013
	 */
	int deleteByExample(StuWeeklyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_stu_weekly
	 * 
	 * @mbggenerated Mon Jul 29 15:08:33 CST 2013
	 */
	int deleteByPrimaryKey(Integer swWeeklyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_stu_weekly
	 * 
	 * @mbggenerated Mon Jul 29 15:08:33 CST 2013
	 */
	int insert(StuWeekly record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_stu_weekly
	 * 
	 * @mbggenerated Mon Jul 29 15:08:33 CST 2013
	 */
	int insertSelective(StuWeekly record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_stu_weekly
	 * 
	 * @mbggenerated Mon Jul 29 15:08:33 CST 2013
	 */
	List<StuWeekly> selectByExample(StuWeeklyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_stu_weekly
	 * 
	 * @mbggenerated Mon Jul 29 15:08:33 CST 2013
	 */
	StuWeekly selectByPrimaryKey(Integer swWeeklyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_stu_weekly
	 * 
	 * @mbggenerated Mon Jul 29 15:08:33 CST 2013
	 */
	int updateByExampleSelective(@Param("record") StuWeekly record,
			@Param("example") StuWeeklyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_stu_weekly
	 * 
	 * @mbggenerated Mon Jul 29 15:08:33 CST 2013
	 */
	int updateByExample(@Param("record") StuWeekly record,
			@Param("example") StuWeeklyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_stu_weekly
	 * 
	 * @mbggenerated Mon Jul 29 15:08:33 CST 2013
	 */
	int updateByPrimaryKeySelective(StuWeekly record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_stu_weekly
	 * 
	 * @mbggenerated Mon Jul 29 15:08:33 CST 2013
	 */
	int updateByPrimaryKey(StuWeekly record);

	List<MoreStuWeekly> selectStuWeekly(RowBounds rowBounds);
	
	public List<MoreStuWeekly> selectQueryWeekly(HashMap map,RowBounds rowBounds);
	
	MoreStuWeekly selectByWeeklyId(Integer swWeeklyId);
}