package com.chinasofti.cetp.practice.dao;

import com.chinasofti.cetp.practice.model.MoreMoreTeamPlan;
import com.chinasofti.cetp.practice.model.MoreTeamPlan;
import com.chinasofti.cetp.practice.model.MoreTeamPlanWithTask;
import com.chinasofti.cetp.practice.model.ProgressRanking;
import com.chinasofti.cetp.practice.model.TeamMemberScore;
import com.chinasofti.cetp.practice.model.TeamPlan;
import com.chinasofti.cetp.practice.model.TeamPlanExample;
import com.chinasofti.cetp.practice.model.TreeTeamScore;

import java.util.HashMap;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TeamPlanMapper {
	// add by YF
	List<MoreTeamPlanWithTask> selectWithTask(@Param("stuNo") Integer stuNo, @Param("teamId") Integer teamId);

	MoreTeamPlan getMoreTeamPlan(HashMap<String, Object> map);

	List<MoreMoreTeamPlan> getTeamProgress(Integer teamId);

	List<ProgressRanking> getTeamProgressRanking(Integer pracId, RowBounds rowBounds);

	List<ProgressRanking> getPracPerProgressRanking(Integer pracId, RowBounds rowBounds);

	List<ProgressRanking> getTeamPerProgressRanking(Integer teamId, RowBounds rowBounds);

	List<ProgressRanking> getTeamProgressRanking(Integer pracId);

	List<ProgressRanking> getPracPerProgressRanking(Integer pracId);

	List<ProgressRanking> getTeamPerProgressRanking(Integer teamId);

//	Integer getTeamRank(@Param("pracId") Integer pracId, @Param("plTeamId") Integer plTeamId);
//
//	Integer getPracPerRank(@Param("pracId") Integer pracId, @Param("stuNo") Integer stuNo);
//
//	Integer getTeamPerRank(@Param("teamId") Integer teamId, @Param("stuNo") Integer stuNo);

	// 2013-9-25
	List<TeamMemberScore> getTeamMemberScore(Integer teamId);

	List<TreeTeamScore> getTreeTeamScore(@Param("teamId") Integer teamId, @Param("proId") Integer proId, @Param("parentId") Integer parentId);

	//
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_team_plan
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int countByExample(TeamPlanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_team_plan
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByExample(TeamPlanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_team_plan
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByPrimaryKey(Integer plPlanId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_team_plan
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insert(TeamPlan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_team_plan
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insertSelective(TeamPlan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_team_plan
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	List<TeamPlan> selectByExample(TeamPlanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_team_plan
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	TeamPlan selectByPrimaryKey(Integer plPlanId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_team_plan
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExampleSelective(@Param("record") TeamPlan record, @Param("example") TeamPlanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_team_plan
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExample(@Param("record") TeamPlan record, @Param("example") TeamPlanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_team_plan
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKeySelective(TeamPlan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_team_plan
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKey(TeamPlan record);
}