package com.chinasofti.cetp.practice.dao;

import com.chinasofti.cetp.practice.model.Know;
import com.chinasofti.cetp.practice.model.KnowExample;
import com.chinasofti.cetp.practice.model.MoreKnow;

import java.util.HashMap;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface KnowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_know
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int countByExample(KnowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_know
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int deleteByExample(KnowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_know
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int deleteByPrimaryKey(Integer knowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_know
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int insert(Know record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_know
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int insertSelective(Know record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_know
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    List<Know> selectByExampleWithBLOBs(KnowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_know
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    List<Know> selectByExample(KnowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_know
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    Know selectByPrimaryKey(Integer knowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_know
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int updateByExampleSelective(@Param("record") Know record, @Param("example") KnowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_know
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int updateByExampleWithBLOBs(@Param("record") Know record, @Param("example") KnowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_know
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int updateByExample(@Param("record") Know record, @Param("example") KnowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_know
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int updateByPrimaryKeySelective(Know record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_know
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int updateByPrimaryKeyWithBLOBs(Know record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_know
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    int updateByPrimaryKey(Know record);
    
    public List<MoreKnow> selectKnowledge(RowBounds rowBounds);
    
    public List<MoreKnow> selectQueryKnowledge(HashMap map,RowBounds rowBounds);
    
    MoreKnow selectByPrimaryKey1(Integer knowId);
    
    int deleteKnowledgeFileUrl(Integer knowId);
    
//    public Integer deleteKnowledgeFileUrl(String techTypeName);
}