package com.chinasofti.cetp.practice.dao;

import com.chinasofti.cetp.practice.model.MorePersonPlan;
import com.chinasofti.cetp.practice.model.PersonPlan;
import com.chinasofti.cetp.practice.model.PersonPlanExample;
import com.chinasofti.cetp.practice.model.ProgressRanking;
import com.chinasofti.cetp.practice.model.TreeStuScore;
import com.chinasofti.cetp.practice.model.TreeTeamScore;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PersonPlanMapper {
	//add by YF 2014-03-19
	Integer deleteByProId(@Param("proId") Integer proId,
			@Param("stuNo") Integer stuNo);
	
	//add by YF 2014-03-11
	Integer countPP(@Param("proId") Integer proId,
			@Param("stuNo") Integer stuNo);
	
	// add by YF 2013-9-17
	List<MorePersonPlan> getStuProgress(@Param("proId") Integer proId,
			@Param("stuNo") Integer stuNo);

	// add by YF 2013-9-24
	List<ProgressRanking> getPersonalPracPerProgressRanking(Integer pracId,
			RowBounds rowBounds);
	List<ProgressRanking> getPersonalPracPerProgressRanking(Integer pracId);

//	Integer getPersonalPracPerRank(@Param("pracId") Integer pracId,
//			@Param("proId") Integer proId, @Param("stuNo") Integer stuNo);

	List<TreeStuScore> getTreeStuScore(@Param("stuNo") Integer stuNo,
			@Param("proId") Integer proId, @Param("parentId") Integer parentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_person_plan
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int countByExample(PersonPlanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_person_plan
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByExample(PersonPlanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_person_plan
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByPrimaryKey(Integer pnPlanId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_person_plan
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insert(PersonPlan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_person_plan
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insertSelective(PersonPlan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_person_plan
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	List<PersonPlan> selectByExample(PersonPlanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_person_plan
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	PersonPlan selectByPrimaryKey(Integer pnPlanId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_person_plan
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExampleSelective(@Param("record") PersonPlan record,
			@Param("example") PersonPlanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_person_plan
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExample(@Param("record") PersonPlan record,
			@Param("example") PersonPlanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_person_plan
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKeySelective(PersonPlan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_person_plan
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKey(PersonPlan record);
}