package com.chinasofti.cetp.study.dao;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.chinasofti.cetp.study.model.CompScore;
import com.chinasofti.cetp.study.model.CompScoreExample;
import com.chinasofti.cetp.study.model.CompScoreKey;
import com.chinasofti.cetp.study.model.MoreCompScore;

public interface CompScoreMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_comp_score
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int countByExample(CompScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_comp_score
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int deleteByExample(CompScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_comp_score
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int deleteByPrimaryKey(CompScoreKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_comp_score
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int insert(CompScore record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_comp_score
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int insertSelective(CompScore record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_comp_score
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	List<CompScore> selectByExample(CompScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_comp_score
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	CompScore selectByPrimaryKey(CompScoreKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_comp_score
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int updateByExampleSelective(@Param("record") CompScore record,
			@Param("example") CompScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_comp_score
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int updateByExample(@Param("record") CompScore record,
			@Param("example") CompScoreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_comp_score
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int updateByPrimaryKeySelective(CompScore record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_comp_score
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int updateByPrimaryKey(CompScore record);

	List<MoreCompScore> selectChapterCompScore(HashMap<String, Object> map,RowBounds rb);
	List<MoreCompScore> selectChapterScoreForShow(HashMap<String, Object> map,RowBounds rb);
	
	MoreCompScore selectCompScoreForSpecIdAndStuNo(HashMap<String, Object>mpa);
}