package com.chinasofti.cetp.ability.dao;

import com.chinasofti.cetp.ability.model.Profession;
import com.chinasofti.cetp.ability.model.ProfessionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ProfessionMapper {
	/**
	 * <p>
	 * 		method:selectProfession
	 * 		<br>
	 * 		description:获取岗位列表的方法
	 * </p>
	 * @return int
	 * */
	int selectProfession(Integer profId);
	/**
	 * <p>
	 * 		method:selectProfession
	 * 		<br>
	 * 		description:获取岗位列表的方法
	 * </p>
	 * @return int
	 * */
	int selectProfession1(Integer profId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_profession
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int countByExample(ProfessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_profession
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int deleteByExample(ProfessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_profession
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int deleteByPrimaryKey(Integer profId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_profession
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int insert(Profession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_profession
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int insertSelective(Profession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_profession
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    List<Profession> selectByExample(ProfessionExample example);
    List<Profession> selectByExample(ProfessionExample example,RowBounds rowBounds);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_profession
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    Profession selectByPrimaryKey(Integer profId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_profession
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int updateByExampleSelective(@Param("record") Profession record, @Param("example") ProfessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_profession
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int updateByExample(@Param("record") Profession record, @Param("example") ProfessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_profession
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int updateByPrimaryKeySelective(Profession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_profession
     *
     * @mbggenerated Fri Aug 09 09:51:47 CST 2013
     */
    int updateByPrimaryKey(Profession record);
}