package com.chinasofti.cetp.survey.model;

public class ModelQueKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_model_que.MQ_MODEL_ID
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    private Integer mqModelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_model_que.MQ_QUE_ID
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    private Integer mqQueId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_model_que.MQ_MODEL_ID
     *
     * @return the value of tp_model_que.MQ_MODEL_ID
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public Integer getMqModelId() {
        return mqModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_model_que.MQ_MODEL_ID
     *
     * @param mqModelId the value for tp_model_que.MQ_MODEL_ID
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public void setMqModelId(Integer mqModelId) {
        this.mqModelId = mqModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_model_que.MQ_QUE_ID
     *
     * @return the value of tp_model_que.MQ_QUE_ID
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public Integer getMqQueId() {
        return mqQueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_model_que.MQ_QUE_ID
     *
     * @param mqQueId the value for tp_model_que.MQ_QUE_ID
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public void setMqQueId(Integer mqQueId) {
        this.mqQueId = mqQueId;
    }
}