package com.chinasofti.cetp.survey.model;

import java.util.Date;

public class Quetionaire {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_quetionaire.QA_ID
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    private Integer qaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_quetionaire.QA_PROP
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    private String qaProp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_quetionaire.QA_TYPE
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    private String qaType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_quetionaire.QA_ENABLE
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    private String qaEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_quetionaire.QA_USER_NO
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    private Integer qaUserNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_quetionaire.QA_REGTIME
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    private Date qaRegtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_quetionaire.QA_TITLE
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    private String qaTitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_quetionaire.QA_ID
     *
     * @return the value of tp_quetionaire.QA_ID
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public Integer getQaId() {
        return qaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_quetionaire.QA_ID
     *
     * @param qaId the value for tp_quetionaire.QA_ID
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public void setQaId(Integer qaId) {
        this.qaId = qaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_quetionaire.QA_PROP
     *
     * @return the value of tp_quetionaire.QA_PROP
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public String getQaProp() {
        return qaProp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_quetionaire.QA_PROP
     *
     * @param qaProp the value for tp_quetionaire.QA_PROP
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public void setQaProp(String qaProp) {
        this.qaProp = qaProp == null ? null : qaProp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_quetionaire.QA_TYPE
     *
     * @return the value of tp_quetionaire.QA_TYPE
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public String getQaType() {
        return qaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_quetionaire.QA_TYPE
     *
     * @param qaType the value for tp_quetionaire.QA_TYPE
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public void setQaType(String qaType) {
        this.qaType = qaType == null ? null : qaType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_quetionaire.QA_ENABLE
     *
     * @return the value of tp_quetionaire.QA_ENABLE
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public String getQaEnable() {
        return qaEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_quetionaire.QA_ENABLE
     *
     * @param qaEnable the value for tp_quetionaire.QA_ENABLE
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public void setQaEnable(String qaEnable) {
        this.qaEnable = qaEnable == null ? null : qaEnable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_quetionaire.QA_USER_NO
     *
     * @return the value of tp_quetionaire.QA_USER_NO
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public Integer getQaUserNo() {
        return qaUserNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_quetionaire.QA_USER_NO
     *
     * @param qaUserNo the value for tp_quetionaire.QA_USER_NO
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public void setQaUserNo(Integer qaUserNo) {
        this.qaUserNo = qaUserNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_quetionaire.QA_REGTIME
     *
     * @return the value of tp_quetionaire.QA_REGTIME
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public Date getQaRegtime() {
        return qaRegtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_quetionaire.QA_REGTIME
     *
     * @param qaRegtime the value for tp_quetionaire.QA_REGTIME
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public void setQaRegtime(Date qaRegtime) {
        this.qaRegtime = qaRegtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_quetionaire.QA_TITLE
     *
     * @return the value of tp_quetionaire.QA_TITLE
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public String getQaTitle() {
        return qaTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_quetionaire.QA_TITLE
     *
     * @param qaTitle the value for tp_quetionaire.QA_TITLE
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public void setQaTitle(String qaTitle) {
        this.qaTitle = qaTitle == null ? null : qaTitle.trim();
    }
}