package com.chinasofti.cetp.survey.model;

import java.util.Date;

public class Survey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_survey.SY_SURVEY_ID
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    private Integer sySurveyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_survey.SY_TYPE
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    private String syType;
    
    
    private String syTitle;
    
    public String getSyTitle() {
		return syTitle;
	}

	public void setSyTitle(String syTitle) {
		this.syTitle = syTitle;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_survey.SY_EVENT_IDS
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    private String syEventIds;
    private String syEventNames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_survey.SY_ENABLE
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    private String syEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_survey.SY_START_DATE
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    private Date syStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_survey.SY_END_DATE
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    private Date syEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_survey.SY_USER_NO
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    private Integer syUserNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_survey.SY_REGTIME
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    private Date syRegtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_survey.SY_INTRO
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    private String syIntro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_survey.SY_SURVEY_ID
     *
     * @return the value of tp_survey.SY_SURVEY_ID
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public Integer getSySurveyId() {
        return sySurveyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_survey.SY_SURVEY_ID
     *
     * @param sySurveyId the value for tp_survey.SY_SURVEY_ID
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public void setSySurveyId(Integer sySurveyId) {
        this.sySurveyId = sySurveyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_survey.SY_TYPE
     *
     * @return the value of tp_survey.SY_TYPE
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public String getSyType() {
        return syType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_survey.SY_TYPE
     *
     * @param syType the value for tp_survey.SY_TYPE
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public void setSyType(String syType) {
        this.syType = syType == null ? null : syType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_survey.SY_EVENT_IDS
     *
     * @return the value of tp_survey.SY_EVENT_IDS
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public String getSyEventIds() {
        return syEventIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_survey.SY_EVENT_IDS
     *
     * @param syEventIds the value for tp_survey.SY_EVENT_IDS
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public void setSyEventIds(String syEventIds) {
        this.syEventIds = syEventIds == null ? null : syEventIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_survey.SY_ENABLE
     *
     * @return the value of tp_survey.SY_ENABLE
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public String getSyEnable() {
        return syEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_survey.SY_ENABLE
     *
     * @param syEnable the value for tp_survey.SY_ENABLE
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public void setSyEnable(String syEnable) {
        this.syEnable = syEnable == null ? null : syEnable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_survey.SY_START_DATE
     *
     * @return the value of tp_survey.SY_START_DATE
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public Date getSyStartDate() {
        return syStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_survey.SY_START_DATE
     *
     * @param syStartDate the value for tp_survey.SY_START_DATE
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public void setSyStartDate(Date syStartDate) {
        this.syStartDate = syStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_survey.SY_END_DATE
     *
     * @return the value of tp_survey.SY_END_DATE
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public Date getSyEndDate() {
        return syEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_survey.SY_END_DATE
     *
     * @param syEndDate the value for tp_survey.SY_END_DATE
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public void setSyEndDate(Date syEndDate) {
        this.syEndDate = syEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_survey.SY_USER_NO
     *
     * @return the value of tp_survey.SY_USER_NO
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public Integer getSyUserNo() {
        return syUserNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_survey.SY_USER_NO
     *
     * @param syUserNo the value for tp_survey.SY_USER_NO
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public void setSyUserNo(Integer syUserNo) {
        this.syUserNo = syUserNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_survey.SY_REGTIME
     *
     * @return the value of tp_survey.SY_REGTIME
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public Date getSyRegtime() {
        return syRegtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_survey.SY_REGTIME
     *
     * @param syRegtime the value for tp_survey.SY_REGTIME
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public void setSyRegtime(Date syRegtime) {
        this.syRegtime = syRegtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_survey.SY_INTRO
     *
     * @return the value of tp_survey.SY_INTRO
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public String getSyIntro() {
        return syIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_survey.SY_INTRO
     *
     * @param syIntro the value for tp_survey.SY_INTRO
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public void setSyIntro(String syIntro) {
        this.syIntro = syIntro == null ? null : syIntro.trim();
    }

	public String getSyEventNames() {
		return syEventNames;
	}

	public void setSyEventNames(String syEventNames) {
		this.syEventNames = syEventNames;
	}
    
}