package com.chinasofti.cetp.survey.model;

import java.util.Date;

public class SurveyModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_survey_model.SM_MODEL_ID
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    private Integer smModelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_survey_model.SM_MODEL_TITLE
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    private String smModelTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_survey_model.SM_INTRO
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    private String smIntro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_survey_model.SM_TYPE
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    private String smType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_survey_model.SM_ENABLE
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    private String smEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_survey_model.SM_USER_NO
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    private Integer smUserNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_survey_model.SM_REGTIME
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    private Date smRegtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_survey_model.SM_MODEL_ID
     *
     * @return the value of tp_survey_model.SM_MODEL_ID
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public Integer getSmModelId() {
        return smModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_survey_model.SM_MODEL_ID
     *
     * @param smModelId the value for tp_survey_model.SM_MODEL_ID
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public void setSmModelId(Integer smModelId) {
        this.smModelId = smModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_survey_model.SM_MODEL_TITLE
     *
     * @return the value of tp_survey_model.SM_MODEL_TITLE
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public String getSmModelTitle() {
        return smModelTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_survey_model.SM_MODEL_TITLE
     *
     * @param smModelTitle the value for tp_survey_model.SM_MODEL_TITLE
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public void setSmModelTitle(String smModelTitle) {
        this.smModelTitle = smModelTitle == null ? null : smModelTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_survey_model.SM_INTRO
     *
     * @return the value of tp_survey_model.SM_INTRO
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public String getSmIntro() {
        return smIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_survey_model.SM_INTRO
     *
     * @param smIntro the value for tp_survey_model.SM_INTRO
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public void setSmIntro(String smIntro) {
        this.smIntro = smIntro == null ? null : smIntro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_survey_model.SM_TYPE
     *
     * @return the value of tp_survey_model.SM_TYPE
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public String getSmType() {
        return smType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_survey_model.SM_TYPE
     *
     * @param smType the value for tp_survey_model.SM_TYPE
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public void setSmType(String smType) {
        this.smType = smType == null ? null : smType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_survey_model.SM_ENABLE
     *
     * @return the value of tp_survey_model.SM_ENABLE
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public String getSmEnable() {
        return smEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_survey_model.SM_ENABLE
     *
     * @param smEnable the value for tp_survey_model.SM_ENABLE
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public void setSmEnable(String smEnable) {
        this.smEnable = smEnable == null ? null : smEnable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_survey_model.SM_USER_NO
     *
     * @return the value of tp_survey_model.SM_USER_NO
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public Integer getSmUserNo() {
        return smUserNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_survey_model.SM_USER_NO
     *
     * @param smUserNo the value for tp_survey_model.SM_USER_NO
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public void setSmUserNo(Integer smUserNo) {
        this.smUserNo = smUserNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_survey_model.SM_REGTIME
     *
     * @return the value of tp_survey_model.SM_REGTIME
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public Date getSmRegtime() {
        return smRegtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_survey_model.SM_REGTIME
     *
     * @param smRegtime the value for tp_survey_model.SM_REGTIME
     *
     * @mbggenerated Thu Jul 25 20:01:32 CST 2013
     */
    public void setSmRegtime(Date smRegtime) {
        this.smRegtime = smRegtime;
    }
}