package com.chinasofti.cetp.practice.dao;

import com.chinasofti.cetp.practice.model.TaskAnswer;
import com.chinasofti.cetp.practice.model.TaskAnswerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TaskAnswerMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_answer
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int countByExample(TaskAnswerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_answer
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByExample(TaskAnswerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_answer
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByPrimaryKey(Integer taAnswerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_answer
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insert(TaskAnswer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_answer
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insertSelective(TaskAnswer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_answer
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	List<TaskAnswer> selectByExample(TaskAnswerExample example);

	List<TaskAnswer> selectByExample(TaskAnswerExample example,
			RowBounds rowbounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_answer
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	TaskAnswer selectByPrimaryKey(Integer taAnswerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_answer
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExampleSelective(@Param("record") TaskAnswer record,
			@Param("example") TaskAnswerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_answer
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExample(@Param("record") TaskAnswer record,
			@Param("example") TaskAnswerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_answer
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKeySelective(TaskAnswer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_answer
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKey(TaskAnswer record);
}