package com.chinasofti.cetp.study.model;

import java.util.Date;

public class NormalScore extends NormalScoreKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_normal_score.NS_SCORE
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    private Integer nsScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_normal_score.NS_REGTIME
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    private Date nsRegtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_normal_score.NS_SCORE
     *
     * @return the value of tp_normal_score.NS_SCORE
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public Integer getNsScore() {
        return nsScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_normal_score.NS_SCORE
     *
     * @param nsScore the value for tp_normal_score.NS_SCORE
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public void setNsScore(Integer nsScore) {
        this.nsScore = nsScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_normal_score.NS_REGTIME
     *
     * @return the value of tp_normal_score.NS_REGTIME
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public Date getNsRegtime() {
        return nsRegtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_normal_score.NS_REGTIME
     *
     * @param nsRegtime the value for tp_normal_score.NS_REGTIME
     *
     * @mbggenerated Thu Jul 25 19:26:27 CST 2013
     */
    public void setNsRegtime(Date nsRegtime) {
        this.nsRegtime = nsRegtime;
    }
}