package com.chinasofti.cetp.study.dao;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.chinasofti.cetp.study.model.Courseware;
import com.chinasofti.cetp.study.model.CoursewareExample;
import com.chinasofti.cetp.study.model.MoreCourseware;
import com.chinasofti.cetp.utils.RowBoundsWithTotalCount;

public interface CoursewareMapper {

	// 查询章节课件
	Courseware selectCourseWithChapter(int chapId);

	/* 自定义方法 */
	// 查询所有课件的方法
	List<Courseware> selectCourseware(RowBounds rb);

	// 模糊查询
	List<Courseware> selectQureyCourseware(HashMap<String, Object> map,RowBounds rb);
	
	//查询已修普通课件
	List<MoreCourseware> selectFinishCourseForStu(HashMap<String, Object>map,RowBounds rb);

	void addCourseware(HashMap<String, Object> map);

	void updateCourseware(HashMap<String, Object> map);

	/*-------------------------------------------*/

	int countByExample(CoursewareExample example);

	int deleteByExample(CoursewareExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_courseware
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int deleteByPrimaryKey(Integer courseId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_courseware
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int insert(Courseware record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_courseware
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int insertSelective(Courseware record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_courseware
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	List<Courseware> selectByExample(CoursewareExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_courseware
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	MoreCourseware selectByPrimaryKey(Integer courseId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_courseware
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int updateByExampleSelective(@Param("record") Courseware record,
			@Param("example") CoursewareExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_courseware
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int updateByExample(@Param("record") Courseware record,
			@Param("example") CoursewareExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_courseware
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int updateByPrimaryKeySelective(Courseware record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_courseware
	 * 
	 * @mbggenerated Thu Jul 25 19:26:27 CST 2013
	 */
	int updateByPrimaryKey(Courseware record);

	/* 选课mapper */
	Courseware selectSelByPrimaryKey(Integer courseId);

	List<Courseware> selectSelCoursewareByInfo(HashMap<String, Object> map,RowBounds rb);

	List<Courseware> selectSelCoursewareByStuNo(int stuNo);

	List<Courseware> getCheckedCourseByInfo(HashMap<String, Object> map,RowBounds rb);

	List<Courseware> getCheckedCourseByStuNo(int stuNo);
}