package com.chinasofti.cetp.practice.dao;

import com.chinasofti.cetp.admin.model.MoreStudent;
import com.chinasofti.cetp.practice.model.MoreTeamMember;
import com.chinasofti.cetp.practice.model.TeamMember;
import com.chinasofti.cetp.practice.model.TeamMemberExample;
import com.chinasofti.cetp.practice.model.TeamMemberKey;
import com.chinasofti.cetp.practice.model.TeamMemberWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TeamMemberMapper {

	// @todu:根据Session中学号，查询组编号
	Integer getTeamIdByStuNo(Integer stuNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_team_member
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int countByExample(TeamMemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_team_member
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByExample(TeamMemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_team_member
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByPrimaryKey(TeamMemberKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_team_member
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insert(TeamMemberWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_team_member
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insertSelective(TeamMemberWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_team_member
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	List<TeamMemberWithBLOBs> selectByExampleWithBLOBs(TeamMemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_team_member
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	List<TeamMember> selectByExample(TeamMemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_team_member
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	TeamMemberWithBLOBs selectByPrimaryKey(TeamMemberKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_team_member
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExampleSelective(@Param("record") TeamMemberWithBLOBs record,
			@Param("example") TeamMemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_team_member
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExampleWithBLOBs(@Param("record") TeamMemberWithBLOBs record,
			@Param("example") TeamMemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_team_member
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExample(@Param("record") TeamMember record,
			@Param("example") TeamMemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_team_member
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKeySelective(TeamMemberWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_team_member
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKeyWithBLOBs(TeamMemberWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_team_member
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKey(TeamMember record);

	// 根据学员ID查询实训ID,项目ID
	List<MoreTeamMember> getTeamMemberMsg(Integer stuNum);

	TeamMember selectByTeamID(int teamId);

	List<TeamMember> selectByTM_MEMBER_NO(Integer tM_MEMBER_NO);

	List<TeamMember> selectByTEAM_ID(Integer tmTeamId);

	// add by YF 2013-12-02
	List<MoreStudent> getUnselectedTeamMember(@Param("pracId") Integer pracId,
			@Param("teamId") Integer teamId, @Param("stuName") String stuName,
			@Param("className") String className, RowBounds rowBounds);
}