package com.chinasofti.cetp.survey.dao;

import com.chinasofti.cetp.survey.model.Survey;
import com.chinasofti.cetp.survey.model.SurveyEvent;
import com.chinasofti.cetp.survey.model.SurveyExample;
import com.chinasofti.cetp.survey.model.Surveys;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SurveyMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int countByExample(SurveyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int deleteByExample(SurveyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int deleteByPrimaryKey(Integer sySurveyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int insert(Survey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int insertSelective(Survey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	List<Survey> selectByExampleWithBLOBs(SurveyExample example,
			RowBounds rowBounds);

	List<Survey> selectByPage(Map<String, Object> map);

	List<Surveys> selectSurveysByPage(Map<String, Object> map);
	
	int count(Map<String, Object> map);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	List<Survey> selectByExample(SurveyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	Survey selectByPrimaryKey(Integer sySurveyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int updateByExampleSelective(@Param("record") Survey record,
			@Param("example") SurveyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int updateByExampleWithBLOBs(@Param("record") Survey record,
			@Param("example") SurveyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int updateByExample(@Param("record") Survey record,
			@Param("example") SurveyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int updateByPrimaryKeySelective(Survey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int updateByPrimaryKeyWithBLOBs(Survey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_survey
	 * 
	 * @mbggenerated Thu Jul 25 20:01:32 CST 2013
	 */
	int updateByPrimaryKey(Survey record);

	// add by YF
	List<SurveyEvent> selectEventsOfPrac(String eName, RowBounds rowBounds);

	List<SurveyEvent> selectEventsOfSpec(String eName, RowBounds rowBounds);

	List<SurveyEvent> selectEventsOfCourse(String eName, RowBounds rowBounds);

	List<Surveys> selectSurveysByPage2(Map<String, Object> map, RowBounds rowBounds);

	int count2(Map<String, Object> map);
}