package com.chinasofti.cetp.practice.model;

public class TeamMemberWithBLOBs extends TeamMember {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_team_member.TM_SUMMARY
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    private String tmSummary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_team_member.TM_EVALUATE
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    private String tmEvaluate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_team_member.TM_SUMMARY
     *
     * @return the value of tp_team_member.TM_SUMMARY
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public String getTmSummary() {
        return tmSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_team_member.TM_SUMMARY
     *
     * @param tmSummary the value for tp_team_member.TM_SUMMARY
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public void setTmSummary(String tmSummary) {
        this.tmSummary = tmSummary == null ? null : tmSummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_team_member.TM_EVALUATE
     *
     * @return the value of tp_team_member.TM_EVALUATE
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public String getTmEvaluate() {
        return tmEvaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_team_member.TM_EVALUATE
     *
     * @param tmEvaluate the value for tp_team_member.TM_EVALUATE
     *
     * @mbggenerated Thu Jul 25 19:47:24 CST 2013
     */
    public void setTmEvaluate(String tmEvaluate) {
        this.tmEvaluate = tmEvaluate == null ? null : tmEvaluate.trim();
    }
}