package com.chinasofti.cetp.admin.model;

public class Area {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_area.AREA_CODE
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_area.AREA_NAME
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_area.AREA_PARENT
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    private String areaParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_area.AREA_STATUS
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    private String areaStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_area.AREA_CODE
     *
     * @return the value of tp_area.AREA_CODE
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_area.AREA_CODE
     *
     * @param areaCode the value for tp_area.AREA_CODE
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_area.AREA_NAME
     *
     * @return the value of tp_area.AREA_NAME
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_area.AREA_NAME
     *
     * @param areaName the value for tp_area.AREA_NAME
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_area.AREA_PARENT
     *
     * @return the value of tp_area.AREA_PARENT
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public String getAreaParent() {
        return areaParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_area.AREA_PARENT
     *
     * @param areaParent the value for tp_area.AREA_PARENT
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public void setAreaParent(String areaParent) {
        this.areaParent = areaParent == null ? null : areaParent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_area.AREA_STATUS
     *
     * @return the value of tp_area.AREA_STATUS
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public String getAreaStatus() {
        return areaStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_area.AREA_STATUS
     *
     * @param areaStatus the value for tp_area.AREA_STATUS
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public void setAreaStatus(String areaStatus) {
        this.areaStatus = areaStatus == null ? null : areaStatus.trim();
    }
}