package com.chinasofti.cetp.admin.model;

import java.util.Date;

public class Module {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_module.MD_ID
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    private Integer mdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_module.MD_NAME
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    private String mdName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_module.MD_SHOW_NAME
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    private String mdShowName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_module.MD_PARENT
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    private Integer mdParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_module.MD_LEVEL
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    private Integer mdLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_module.MD_IS_LEAF
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    private String mdIsLeaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_module.MD_SEQ
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    private Integer mdSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_module.MD_REGTIME
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    private Date mdRegtime;

    
    private String iconUrl;
    
    public String getIconUrl() {
		return iconUrl;
	}

	public void setIconUrl(String iconUrl) {
		this.iconUrl = iconUrl;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_module.MD_ID
     *
     * @return the value of tp_module.MD_ID
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public Integer getMdId() {
        return mdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_module.MD_ID
     *
     * @param mdId the value for tp_module.MD_ID
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public void setMdId(Integer mdId) {
        this.mdId = mdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_module.MD_NAME
     *
     * @return the value of tp_module.MD_NAME
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public String getMdName() {
        return mdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_module.MD_NAME
     *
     * @param mdName the value for tp_module.MD_NAME
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public void setMdName(String mdName) {
        this.mdName = mdName == null ? null : mdName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_module.MD_SHOW_NAME
     *
     * @return the value of tp_module.MD_SHOW_NAME
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public String getMdShowName() {
        return mdShowName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_module.MD_SHOW_NAME
     *
     * @param mdShowName the value for tp_module.MD_SHOW_NAME
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public void setMdShowName(String mdShowName) {
        this.mdShowName = mdShowName == null ? null : mdShowName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_module.MD_PARENT
     *
     * @return the value of tp_module.MD_PARENT
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public Integer getMdParent() {
        return mdParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_module.MD_PARENT
     *
     * @param mdParent the value for tp_module.MD_PARENT
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public void setMdParent(Integer mdParent) {
        this.mdParent = mdParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_module.MD_LEVEL
     *
     * @return the value of tp_module.MD_LEVEL
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public Integer getMdLevel() {
        return mdLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_module.MD_LEVEL
     *
     * @param mdLevel the value for tp_module.MD_LEVEL
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public void setMdLevel(Integer mdLevel) {
        this.mdLevel = mdLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_module.MD_IS_LEAF
     *
     * @return the value of tp_module.MD_IS_LEAF
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public String getMdIsLeaf() {
        return mdIsLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_module.MD_IS_LEAF
     *
     * @param mdIsLeaf the value for tp_module.MD_IS_LEAF
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public void setMdIsLeaf(String mdIsLeaf) {
        this.mdIsLeaf = mdIsLeaf == null ? null : mdIsLeaf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_module.MD_SEQ
     *
     * @return the value of tp_module.MD_SEQ
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public Integer getMdSeq() {
        return mdSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_module.MD_SEQ
     *
     * @param mdSeq the value for tp_module.MD_SEQ
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public void setMdSeq(Integer mdSeq) {
        this.mdSeq = mdSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_module.MD_REGTIME
     *
     * @return the value of tp_module.MD_REGTIME
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public Date getMdRegtime() {
        return mdRegtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_module.MD_REGTIME
     *
     * @param mdRegtime the value for tp_module.MD_REGTIME
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public void setMdRegtime(Date mdRegtime) {
        this.mdRegtime = mdRegtime;
    }
}