package com.chinasofti.cetp.admin.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ModuleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_module
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_module
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_module
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_module
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public ModuleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_module
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_module
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_module
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_module
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_module
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_module
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_module
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_module
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_module
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_module
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_module
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMdIdIsNull() {
            addCriterion("MD_ID is null");
            return (Criteria) this;
        }

        public Criteria andMdIdIsNotNull() {
            addCriterion("MD_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMdIdEqualTo(Integer value) {
            addCriterion("MD_ID =", value, "mdId");
            return (Criteria) this;
        }

        public Criteria andMdIdNotEqualTo(Integer value) {
            addCriterion("MD_ID <>", value, "mdId");
            return (Criteria) this;
        }

        public Criteria andMdIdGreaterThan(Integer value) {
            addCriterion("MD_ID >", value, "mdId");
            return (Criteria) this;
        }

        public Criteria andMdIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("MD_ID >=", value, "mdId");
            return (Criteria) this;
        }

        public Criteria andMdIdLessThan(Integer value) {
            addCriterion("MD_ID <", value, "mdId");
            return (Criteria) this;
        }

        public Criteria andMdIdLessThanOrEqualTo(Integer value) {
            addCriterion("MD_ID <=", value, "mdId");
            return (Criteria) this;
        }

        public Criteria andMdIdIn(List<Integer> values) {
            addCriterion("MD_ID in", values, "mdId");
            return (Criteria) this;
        }

        public Criteria andMdIdNotIn(List<Integer> values) {
            addCriterion("MD_ID not in", values, "mdId");
            return (Criteria) this;
        }

        public Criteria andMdIdBetween(Integer value1, Integer value2) {
            addCriterion("MD_ID between", value1, value2, "mdId");
            return (Criteria) this;
        }

        public Criteria andMdIdNotBetween(Integer value1, Integer value2) {
            addCriterion("MD_ID not between", value1, value2, "mdId");
            return (Criteria) this;
        }

        public Criteria andMdNameIsNull() {
            addCriterion("MD_NAME is null");
            return (Criteria) this;
        }

        public Criteria andMdNameIsNotNull() {
            addCriterion("MD_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andMdNameEqualTo(String value) {
            addCriterion("MD_NAME =", value, "mdName");
            return (Criteria) this;
        }

        public Criteria andMdNameNotEqualTo(String value) {
            addCriterion("MD_NAME <>", value, "mdName");
            return (Criteria) this;
        }

        public Criteria andMdNameGreaterThan(String value) {
            addCriterion("MD_NAME >", value, "mdName");
            return (Criteria) this;
        }

        public Criteria andMdNameGreaterThanOrEqualTo(String value) {
            addCriterion("MD_NAME >=", value, "mdName");
            return (Criteria) this;
        }

        public Criteria andMdNameLessThan(String value) {
            addCriterion("MD_NAME <", value, "mdName");
            return (Criteria) this;
        }

        public Criteria andMdNameLessThanOrEqualTo(String value) {
            addCriterion("MD_NAME <=", value, "mdName");
            return (Criteria) this;
        }

        public Criteria andMdNameLike(String value) {
            addCriterion("MD_NAME like", value, "mdName");
            return (Criteria) this;
        }

        public Criteria andMdNameNotLike(String value) {
            addCriterion("MD_NAME not like", value, "mdName");
            return (Criteria) this;
        }

        public Criteria andMdNameIn(List<String> values) {
            addCriterion("MD_NAME in", values, "mdName");
            return (Criteria) this;
        }

        public Criteria andMdNameNotIn(List<String> values) {
            addCriterion("MD_NAME not in", values, "mdName");
            return (Criteria) this;
        }

        public Criteria andMdNameBetween(String value1, String value2) {
            addCriterion("MD_NAME between", value1, value2, "mdName");
            return (Criteria) this;
        }

        public Criteria andMdNameNotBetween(String value1, String value2) {
            addCriterion("MD_NAME not between", value1, value2, "mdName");
            return (Criteria) this;
        }

        public Criteria andMdShowNameIsNull() {
            addCriterion("MD_SHOW_NAME is null");
            return (Criteria) this;
        }

        public Criteria andMdShowNameIsNotNull() {
            addCriterion("MD_SHOW_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andMdShowNameEqualTo(String value) {
            addCriterion("MD_SHOW_NAME =", value, "mdShowName");
            return (Criteria) this;
        }

        public Criteria andMdShowNameNotEqualTo(String value) {
            addCriterion("MD_SHOW_NAME <>", value, "mdShowName");
            return (Criteria) this;
        }

        public Criteria andMdShowNameGreaterThan(String value) {
            addCriterion("MD_SHOW_NAME >", value, "mdShowName");
            return (Criteria) this;
        }

        public Criteria andMdShowNameGreaterThanOrEqualTo(String value) {
            addCriterion("MD_SHOW_NAME >=", value, "mdShowName");
            return (Criteria) this;
        }

        public Criteria andMdShowNameLessThan(String value) {
            addCriterion("MD_SHOW_NAME <", value, "mdShowName");
            return (Criteria) this;
        }

        public Criteria andMdShowNameLessThanOrEqualTo(String value) {
            addCriterion("MD_SHOW_NAME <=", value, "mdShowName");
            return (Criteria) this;
        }

        public Criteria andMdShowNameLike(String value) {
            addCriterion("MD_SHOW_NAME like", value, "mdShowName");
            return (Criteria) this;
        }

        public Criteria andMdShowNameNotLike(String value) {
            addCriterion("MD_SHOW_NAME not like", value, "mdShowName");
            return (Criteria) this;
        }

        public Criteria andMdShowNameIn(List<String> values) {
            addCriterion("MD_SHOW_NAME in", values, "mdShowName");
            return (Criteria) this;
        }

        public Criteria andMdShowNameNotIn(List<String> values) {
            addCriterion("MD_SHOW_NAME not in", values, "mdShowName");
            return (Criteria) this;
        }

        public Criteria andMdShowNameBetween(String value1, String value2) {
            addCriterion("MD_SHOW_NAME between", value1, value2, "mdShowName");
            return (Criteria) this;
        }

        public Criteria andMdShowNameNotBetween(String value1, String value2) {
            addCriterion("MD_SHOW_NAME not between", value1, value2, "mdShowName");
            return (Criteria) this;
        }

        public Criteria andMdParentIsNull() {
            addCriterion("MD_PARENT is null");
            return (Criteria) this;
        }

        public Criteria andMdParentIsNotNull() {
            addCriterion("MD_PARENT is not null");
            return (Criteria) this;
        }

        public Criteria andMdParentEqualTo(Integer value) {
            addCriterion("MD_PARENT =", value, "mdParent");
            return (Criteria) this;
        }

        public Criteria andMdParentNotEqualTo(Integer value) {
            addCriterion("MD_PARENT <>", value, "mdParent");
            return (Criteria) this;
        }

        public Criteria andMdParentGreaterThan(Integer value) {
            addCriterion("MD_PARENT >", value, "mdParent");
            return (Criteria) this;
        }

        public Criteria andMdParentGreaterThanOrEqualTo(Integer value) {
            addCriterion("MD_PARENT >=", value, "mdParent");
            return (Criteria) this;
        }

        public Criteria andMdParentLessThan(Integer value) {
            addCriterion("MD_PARENT <", value, "mdParent");
            return (Criteria) this;
        }

        public Criteria andMdParentLessThanOrEqualTo(Integer value) {
            addCriterion("MD_PARENT <=", value, "mdParent");
            return (Criteria) this;
        }

        public Criteria andMdParentIn(List<Integer> values) {
            addCriterion("MD_PARENT in", values, "mdParent");
            return (Criteria) this;
        }

        public Criteria andMdParentNotIn(List<Integer> values) {
            addCriterion("MD_PARENT not in", values, "mdParent");
            return (Criteria) this;
        }

        public Criteria andMdParentBetween(Integer value1, Integer value2) {
            addCriterion("MD_PARENT between", value1, value2, "mdParent");
            return (Criteria) this;
        }

        public Criteria andMdParentNotBetween(Integer value1, Integer value2) {
            addCriterion("MD_PARENT not between", value1, value2, "mdParent");
            return (Criteria) this;
        }

        public Criteria andMdLevelIsNull() {
            addCriterion("MD_LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andMdLevelIsNotNull() {
            addCriterion("MD_LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andMdLevelEqualTo(Integer value) {
            addCriterion("MD_LEVEL =", value, "mdLevel");
            return (Criteria) this;
        }

        public Criteria andMdLevelNotEqualTo(Integer value) {
            addCriterion("MD_LEVEL <>", value, "mdLevel");
            return (Criteria) this;
        }

        public Criteria andMdLevelGreaterThan(Integer value) {
            addCriterion("MD_LEVEL >", value, "mdLevel");
            return (Criteria) this;
        }

        public Criteria andMdLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("MD_LEVEL >=", value, "mdLevel");
            return (Criteria) this;
        }

        public Criteria andMdLevelLessThan(Integer value) {
            addCriterion("MD_LEVEL <", value, "mdLevel");
            return (Criteria) this;
        }

        public Criteria andMdLevelLessThanOrEqualTo(Integer value) {
            addCriterion("MD_LEVEL <=", value, "mdLevel");
            return (Criteria) this;
        }

        public Criteria andMdLevelIn(List<Integer> values) {
            addCriterion("MD_LEVEL in", values, "mdLevel");
            return (Criteria) this;
        }

        public Criteria andMdLevelNotIn(List<Integer> values) {
            addCriterion("MD_LEVEL not in", values, "mdLevel");
            return (Criteria) this;
        }

        public Criteria andMdLevelBetween(Integer value1, Integer value2) {
            addCriterion("MD_LEVEL between", value1, value2, "mdLevel");
            return (Criteria) this;
        }

        public Criteria andMdLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("MD_LEVEL not between", value1, value2, "mdLevel");
            return (Criteria) this;
        }

        public Criteria andMdIsLeafIsNull() {
            addCriterion("MD_IS_LEAF is null");
            return (Criteria) this;
        }

        public Criteria andMdIsLeafIsNotNull() {
            addCriterion("MD_IS_LEAF is not null");
            return (Criteria) this;
        }

        public Criteria andMdIsLeafEqualTo(String value) {
            addCriterion("MD_IS_LEAF =", value, "mdIsLeaf");
            return (Criteria) this;
        }

        public Criteria andMdIsLeafNotEqualTo(String value) {
            addCriterion("MD_IS_LEAF <>", value, "mdIsLeaf");
            return (Criteria) this;
        }

        public Criteria andMdIsLeafGreaterThan(String value) {
            addCriterion("MD_IS_LEAF >", value, "mdIsLeaf");
            return (Criteria) this;
        }

        public Criteria andMdIsLeafGreaterThanOrEqualTo(String value) {
            addCriterion("MD_IS_LEAF >=", value, "mdIsLeaf");
            return (Criteria) this;
        }

        public Criteria andMdIsLeafLessThan(String value) {
            addCriterion("MD_IS_LEAF <", value, "mdIsLeaf");
            return (Criteria) this;
        }

        public Criteria andMdIsLeafLessThanOrEqualTo(String value) {
            addCriterion("MD_IS_LEAF <=", value, "mdIsLeaf");
            return (Criteria) this;
        }

        public Criteria andMdIsLeafLike(String value) {
            addCriterion("MD_IS_LEAF like", value, "mdIsLeaf");
            return (Criteria) this;
        }

        public Criteria andMdIsLeafNotLike(String value) {
            addCriterion("MD_IS_LEAF not like", value, "mdIsLeaf");
            return (Criteria) this;
        }

        public Criteria andMdIsLeafIn(List<String> values) {
            addCriterion("MD_IS_LEAF in", values, "mdIsLeaf");
            return (Criteria) this;
        }

        public Criteria andMdIsLeafNotIn(List<String> values) {
            addCriterion("MD_IS_LEAF not in", values, "mdIsLeaf");
            return (Criteria) this;
        }

        public Criteria andMdIsLeafBetween(String value1, String value2) {
            addCriterion("MD_IS_LEAF between", value1, value2, "mdIsLeaf");
            return (Criteria) this;
        }

        public Criteria andMdIsLeafNotBetween(String value1, String value2) {
            addCriterion("MD_IS_LEAF not between", value1, value2, "mdIsLeaf");
            return (Criteria) this;
        }

        public Criteria andMdSeqIsNull() {
            addCriterion("MD_SEQ is null");
            return (Criteria) this;
        }

        public Criteria andMdSeqIsNotNull() {
            addCriterion("MD_SEQ is not null");
            return (Criteria) this;
        }

        public Criteria andMdSeqEqualTo(Integer value) {
            addCriterion("MD_SEQ =", value, "mdSeq");
            return (Criteria) this;
        }

        public Criteria andMdSeqNotEqualTo(Integer value) {
            addCriterion("MD_SEQ <>", value, "mdSeq");
            return (Criteria) this;
        }

        public Criteria andMdSeqGreaterThan(Integer value) {
            addCriterion("MD_SEQ >", value, "mdSeq");
            return (Criteria) this;
        }

        public Criteria andMdSeqGreaterThanOrEqualTo(Integer value) {
            addCriterion("MD_SEQ >=", value, "mdSeq");
            return (Criteria) this;
        }

        public Criteria andMdSeqLessThan(Integer value) {
            addCriterion("MD_SEQ <", value, "mdSeq");
            return (Criteria) this;
        }

        public Criteria andMdSeqLessThanOrEqualTo(Integer value) {
            addCriterion("MD_SEQ <=", value, "mdSeq");
            return (Criteria) this;
        }

        public Criteria andMdSeqIn(List<Integer> values) {
            addCriterion("MD_SEQ in", values, "mdSeq");
            return (Criteria) this;
        }

        public Criteria andMdSeqNotIn(List<Integer> values) {
            addCriterion("MD_SEQ not in", values, "mdSeq");
            return (Criteria) this;
        }

        public Criteria andMdSeqBetween(Integer value1, Integer value2) {
            addCriterion("MD_SEQ between", value1, value2, "mdSeq");
            return (Criteria) this;
        }

        public Criteria andMdSeqNotBetween(Integer value1, Integer value2) {
            addCriterion("MD_SEQ not between", value1, value2, "mdSeq");
            return (Criteria) this;
        }

        public Criteria andMdRegtimeIsNull() {
            addCriterion("MD_REGTIME is null");
            return (Criteria) this;
        }

        public Criteria andMdRegtimeIsNotNull() {
            addCriterion("MD_REGTIME is not null");
            return (Criteria) this;
        }

        public Criteria andMdRegtimeEqualTo(Date value) {
            addCriterion("MD_REGTIME =", value, "mdRegtime");
            return (Criteria) this;
        }

        public Criteria andMdRegtimeNotEqualTo(Date value) {
            addCriterion("MD_REGTIME <>", value, "mdRegtime");
            return (Criteria) this;
        }

        public Criteria andMdRegtimeGreaterThan(Date value) {
            addCriterion("MD_REGTIME >", value, "mdRegtime");
            return (Criteria) this;
        }

        public Criteria andMdRegtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MD_REGTIME >=", value, "mdRegtime");
            return (Criteria) this;
        }

        public Criteria andMdRegtimeLessThan(Date value) {
            addCriterion("MD_REGTIME <", value, "mdRegtime");
            return (Criteria) this;
        }

        public Criteria andMdRegtimeLessThanOrEqualTo(Date value) {
            addCriterion("MD_REGTIME <=", value, "mdRegtime");
            return (Criteria) this;
        }

        public Criteria andMdRegtimeIn(List<Date> values) {
            addCriterion("MD_REGTIME in", values, "mdRegtime");
            return (Criteria) this;
        }

        public Criteria andMdRegtimeNotIn(List<Date> values) {
            addCriterion("MD_REGTIME not in", values, "mdRegtime");
            return (Criteria) this;
        }

        public Criteria andMdRegtimeBetween(Date value1, Date value2) {
            addCriterion("MD_REGTIME between", value1, value2, "mdRegtime");
            return (Criteria) this;
        }

        public Criteria andMdRegtimeNotBetween(Date value1, Date value2) {
            addCriterion("MD_REGTIME not between", value1, value2, "mdRegtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_module
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 25 19:01:39 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_module
     *
     * @mbggenerated Thu Jul 25 19:01:39 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}