package com.chinasofti.cetp.practice.dao;

import com.chinasofti.cetp.practice.model.MoreKnow;
import com.chinasofti.cetp.practice.model.TaskKnow;
import com.chinasofti.cetp.practice.model.TaskKnowExample;
import com.chinasofti.cetp.practice.model.TaskKnowKey;

import java.util.HashMap;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TaskKnowMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_know
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int countByExample(TaskKnowExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_know
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByExample(TaskKnowExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_know
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByPrimaryKey(TaskKnowKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_know
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insert(TaskKnow record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_know
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insertSelective(TaskKnow record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_know
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	List<TaskKnow> selectByExample(TaskKnowExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_know
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	TaskKnow selectByPrimaryKey(TaskKnowKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_know
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExampleSelective(@Param("record") TaskKnow record,
			@Param("example") TaskKnowExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_know
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExample(@Param("record") TaskKnow record,
			@Param("example") TaskKnowExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_know
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKeySelective(TaskKnow record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_task_know
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKey(TaskKnow record);

	// add by YF
	List<MoreKnow> selectKnowledgeSelected(Integer taskId, RowBounds rowbounds);
	List<MoreKnow> selectKnowledgeSelected(Integer taskId);

	List<MoreKnow> selectKnowledgeUnSelected(HashMap<String, Object> map,
			RowBounds rowbounds);
	
	int copyItems(@Param("from") Integer from, @Param("to") Integer to);
}