package com.chinasofti.cetp.practice.dao;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.chinasofti.cetp.practice.model.MoreMoreMorePracticeTeam;
import com.chinasofti.cetp.practice.model.MoreMorePracticeTeam;
import com.chinasofti.cetp.practice.model.MorePracticeTeam;
import com.chinasofti.cetp.practice.model.PracPersonKey;
import com.chinasofti.cetp.practice.model.PracticeTeam;
import com.chinasofti.cetp.practice.model.PracticeTeamExample;
import com.chinasofti.cetp.practice.model.PracticeTeamWithBLOBs;
import com.chinasofti.cetp.practice.model.Pro;
import com.chinasofti.cetp.practice.model.Student;
import com.chinasofti.cetp.practice.model.TeamMember;

public interface PracticeTeamMapper {
	public List<MoreMoreMorePracticeTeam> getSummarygriddata(HashMap map,RowBounds rowBounds);
	/*
	 * @todu:根据Session中学号，查询组编号
	 * 
	 * @auther：HQ @CreateDate:2013/9/25
	 */
	Integer getPracIdByStuNo(Integer teamId);

	/*
	 * @todu:根据Session中实训组编号，查询改组已选项目编号
	 * 
	 * @auther：HQ @CreateDate:2013/9/25
	 */
	PracPersonKey getProIdByStuNo(Integer stuNo);
	
	//当前学生用户是否为组长
	Integer isTeamLeader(Integer stuNo);
	Integer fullTeamLeader(Integer stuNo);
	
	Integer isTL(Integer stuNo);

	// add by yf
	PracticeTeam getTeamIdByStuNo(Integer stuNo);

	List<MoreMorePracticeTeam> selectTeams(
			@Param("teamPracId") Integer teamPracId,
			@Param("proName") String proName, @Param("teamId") String teamId,
			@Param("teamName") String teamName, RowBounds rowBounds);

	List<MoreMorePracticeTeam> selectTeamsWithoutProg(
			@Param("teamPracId") Integer teamPracId,
			@Param("proName") String proName, @Param("teamId") String teamId,
			@Param("teamName") String teamName, RowBounds rowBounds);

	List<MoreMoreMorePracticeTeam> selectMoreMoreMorePracticeTeam(
			@Param("stuNo") Integer stuNo, @Param("proName") String proName,
			@Param("pracName") String pracName, RowBounds rowBounds);

	// end
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_practice_team
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int countByExample(PracticeTeamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_practice_team
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByExample(PracticeTeamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_practice_team
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int deleteByPrimaryKey(Integer teamId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_practice_team
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insert(PracticeTeamWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_practice_team
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int insertSelective(PracticeTeamWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_practice_team
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	List<PracticeTeamWithBLOBs> selectByExampleWithBLOBs(
			PracticeTeamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_practice_team
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	List<PracticeTeam> selectByExample(PracticeTeamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_practice_team
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	PracticeTeamWithBLOBs selectByPrimaryKey(Integer teamId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_practice_team
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExampleSelective(@Param("record") PracticeTeamWithBLOBs record,
			@Param("example") PracticeTeamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_practice_team
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExampleWithBLOBs(@Param("record") PracticeTeamWithBLOBs record,
			@Param("example") PracticeTeamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_practice_team
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByExample(@Param("record") PracticeTeam record,
			@Param("example") PracticeTeamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_practice_team
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKeySelective(PracticeTeamWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_practice_team
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKeyWithBLOBs(PracticeTeamWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tp_practice_team
	 * 
	 * @mbggenerated Thu Jul 25 19:47:24 CST 2013
	 */
	int updateByPrimaryKey(PracticeTeam record);

	/* start add by wang-hw 2013-08-09 */
	int updTpPracticeTeam(HashMap map);

	/* end */

	// -------------------------------baoyu---------------------------------------------------------------------

	public List<MorePracticeTeam> selectPer(HashMap map,RowBounds rowBounds);

	public List<MorePracticeTeam> selectQueryPer(HashMap map,RowBounds rowBounds);

	public List<Pro> selectAllProName(Integer pracId);

	public List<Student> selectMember();

	public List<Student> selectQueryMember(HashMap map);

	public void insertBY(MorePracticeTeam record);
	
	public void updateBY(MorePracticeTeam record);

	public MorePracticeTeam selectTeamID(MorePracticeTeam record);

	public void insertMember(TeamMember record);

	public MorePracticeTeam selectTeamByPracIdAndTeamId(HashMap record);

	public List<TeamMember> selectTeamMemberByTeamId(HashMap map);

	public void deleteTeamMemberByPrimaryKey(Integer teamId);

	/* add by wangxb */
	PracticeTeam selectByTEAM_LEADER_NO(Integer TEAM_LEADER_NO);
	/* end */
}